In [1]:
from dataset.EEGEyeNet import EEGEyeNetDataset

EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')
EEGEyeNet_MTL = EEGEyeNetDataset('./dataset/MTL_data/Position_task_with_dots_synchronized_min.npz')
import numpy as np
t=0
f = 0
for index in range(len(EEGEyeNet_MTL)):
    a = EEGEyeNet.trainX[index]
    b = EEGEyeNet_MTL.trainX[index]
    
    if np.array_equal(EEGEyeNet.trainY[index,1:3], EEGEyeNet_MTL.trainY[index,1:3]) and np.array_equal(EEGEyeNet.trainX[index], EEGEyeNet_MTL.trainX[index]):
        t+=1
    else:
        f+=1
        

print(t)
print(f)

loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
loading data...
[[1.000e+00 4.081e+02 3.151e+02 3.323e+03]
 [1.000e+00 6.407e+02 5.191e+02 3.062e+03]
 [1.000e+00 4.042e+02 1.188e+02 3.417e+03]
 ...
 [3.000e+01 1.155e+02 3.061e+02 1.910e+03]
 [3.000e+01 7.320e+02 3.103e+02 1.723e+03]
 [3.000e+01 6.322e+02 3.536e+02 1.763e+03]]
21464
0
