In [3]:
from models.EEGDeiT_pretrained_16stride import EEGViT_pretrained
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch


In [4]:
'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained()
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 129, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 33, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
create dataloader...
HI
training...


2it [00:00,  2.39it/s]

Epoch 0, Batch 0, Loss: 169042.15625 RMSE(mm): 205.57368280618996


102it [00:16,  6.59it/s]

Epoch 0, Batch 100, Loss: 66512.0703125 RMSE(mm): 128.94967071739657


202it [00:31,  6.89it/s]

Epoch 0, Batch 200, Loss: 33443.02734375 RMSE(mm): 91.43717425608416


236it [00:36,  6.50it/s]


Epoch 0, Val Loss: 26787.67793367347, RMSE(mm): 81.83470830532951
Epoch 0, test Loss: 27336.109796262255, RMSE(mm): 82.66817676146948


1it [00:00,  6.55it/s]

Epoch 1, Batch 0, Loss: 25928.578125 RMSE(mm): 80.51176641491602


102it [00:15,  6.78it/s]

Epoch 1, Batch 100, Loss: 24954.509765625 RMSE(mm): 78.9849823789703


202it [00:30,  6.66it/s]

Epoch 1, Batch 200, Loss: 27598.62109375 RMSE(mm): 83.06416359319763


236it [00:35,  6.73it/s]


Epoch 1, Val Loss: 22665.992586096938, RMSE(mm): 75.2761459329862
Epoch 1, test Loss: 22385.564376531864, RMSE(mm): 74.80903083273414


1it [00:00,  6.57it/s]

Epoch 2, Batch 0, Loss: 22479.76171875 RMSE(mm): 74.96626194287334


102it [00:15,  6.70it/s]

Epoch 2, Batch 100, Loss: 23027.32421875 RMSE(mm): 75.87378371142104


202it [00:30,  6.68it/s]

Epoch 2, Batch 200, Loss: 20870.400390625 RMSE(mm): 72.23295714323379


236it [00:35,  6.69it/s]


Epoch 2, Val Loss: 18098.840720663266, RMSE(mm): 67.26596598701171
Epoch 2, test Loss: 16918.789713541668, RMSE(mm): 65.03612402646253


1it [00:00,  6.47it/s]

Epoch 3, Batch 0, Loss: 17502.365234375 RMSE(mm): 66.1482524984126


102it [00:15,  6.89it/s]

Epoch 3, Batch 100, Loss: 14434.43359375 RMSE(mm): 60.07169382028028


202it [00:30,  6.67it/s]

Epoch 3, Batch 200, Loss: 18209.37890625 RMSE(mm): 67.47106584723929


236it [00:35,  6.68it/s]


Epoch 3, Val Loss: 15093.115174585459, RMSE(mm): 61.42702006158499
Epoch 3, test Loss: 12828.392041973038, RMSE(mm): 56.63124588505236


1it [00:00,  6.56it/s]

Epoch 4, Batch 0, Loss: 13686.7021484375 RMSE(mm): 58.49508985469956


102it [00:15,  6.77it/s]

Epoch 4, Batch 100, Loss: 13009.78125 RMSE(mm): 57.03021403168675


202it [00:30,  6.45it/s]

Epoch 4, Batch 200, Loss: 17931.689453125 RMSE(mm): 66.95462914004715


236it [00:35,  6.64it/s]


Epoch 4, Val Loss: 14970.077706473214, RMSE(mm): 61.17613445305533
Epoch 4, test Loss: 12437.51131663603, RMSE(mm): 55.761795426250465


1it [00:00,  6.88it/s]

Epoch 5, Batch 0, Loss: 11766.5927734375 RMSE(mm): 54.2369633493559


102it [00:15,  6.71it/s]

Epoch 5, Batch 100, Loss: 11047.6875 RMSE(mm): 52.553990095900424


202it [00:30,  6.53it/s]

Epoch 5, Batch 200, Loss: 16485.4765625 RMSE(mm): 64.19789046865169


236it [00:35,  6.65it/s]


Epoch 5, Val Loss: 15615.213647959185, RMSE(mm): 62.48042423023227
Epoch 5, test Loss: 12783.946308210785, RMSE(mm): 56.53305738285076


1it [00:00,  6.76it/s]

Epoch 6, Batch 0, Loss: 11588.12109375 RMSE(mm): 53.82406778976762


102it [00:15,  6.79it/s]

Epoch 6, Batch 100, Loss: 12135.943359375 RMSE(mm): 55.081628877909466


202it [00:30,  6.63it/s]

Epoch 6, Batch 200, Loss: 14331.2158203125 RMSE(mm): 59.85652809074483


236it [00:35,  6.68it/s]


Epoch 6, Val Loss: 14490.717235331633, RMSE(mm): 60.18869751733217
Epoch 6, test Loss: 11624.04638671875, RMSE(mm): 53.90743544892196


1it [00:00,  6.51it/s]

Epoch 7, Batch 0, Loss: 9154.7060546875 RMSE(mm): 47.840114064160375


102it [00:14,  6.79it/s]

Epoch 7, Batch 100, Loss: 12009.16796875 RMSE(mm): 54.79317468615503


202it [00:29,  6.81it/s]

Epoch 7, Batch 200, Loss: 14275.9853515625 RMSE(mm): 59.74107747513954


236it [00:34,  6.87it/s]


Epoch 7, Val Loss: 14549.69674744898, RMSE(mm): 60.311061894666096
Epoch 7, test Loss: 11545.424852558212, RMSE(mm): 53.72481934022257


1it [00:00,  7.02it/s]

Epoch 8, Batch 0, Loss: 8579.755859375 RMSE(mm): 46.31348577729547


102it [00:14,  6.83it/s]

Epoch 8, Batch 100, Loss: 11493.5048828125 RMSE(mm): 53.60388251519777


202it [00:28,  9.09it/s]

Epoch 8, Batch 200, Loss: 13972.1591796875 RMSE(mm): 59.10194408749914


236it [00:32,  7.31it/s]


Epoch 8, Val Loss: 14674.587930484693, RMSE(mm): 60.56935679550488
Epoch 8, test Loss: 11517.448797487745, RMSE(mm): 53.65968877446026


1it [00:00,  7.55it/s]

Epoch 9, Batch 0, Loss: 8060.4658203125 RMSE(mm): 44.89004850830666


102it [00:10,  9.44it/s]

Epoch 9, Batch 100, Loss: 11444.025390625 RMSE(mm): 53.48837581808079


202it [00:21,  9.50it/s]

Epoch 9, Batch 200, Loss: 13745.68359375 RMSE(mm): 58.62099366641186


236it [00:24,  9.44it/s]


Epoch 9, Val Loss: 14718.47084263393, RMSE(mm): 60.65985254398895
Epoch 9, test Loss: 11462.23446116728, RMSE(mm): 53.53091270744242


2it [00:00,  9.65it/s]

Epoch 10, Batch 0, Loss: 7571.6201171875 RMSE(mm): 43.50752842091671


102it [00:10,  9.62it/s]

Epoch 10, Batch 100, Loss: 10945.015625 RMSE(mm): 52.30921435320932


202it [00:21,  9.61it/s]

Epoch 10, Batch 200, Loss: 12845.6083984375 RMSE(mm): 56.66923415407495


236it [00:24,  9.62it/s]


Epoch 10, Val Loss: 14900.086874202807, RMSE(mm): 61.03295600370919
Epoch 10, test Loss: 11492.148198146446, RMSE(mm): 53.600718740858426


2it [00:00,  9.69it/s]

Epoch 11, Batch 0, Loss: 7383.3388671875 RMSE(mm): 42.96317861607629


102it [00:10,  9.16it/s]

Epoch 11, Batch 100, Loss: 10480.61328125 RMSE(mm): 51.18743322645217


202it [00:21,  9.61it/s]

Epoch 11, Batch 200, Loss: 12319.564453125 RMSE(mm): 55.49676669213487


236it [00:24,  9.50it/s]


Epoch 11, Val Loss: 15055.485421316964, RMSE(mm): 61.3503981676504
Epoch 11, test Loss: 11603.854291130514, RMSE(mm): 53.860593876995345


1it [00:00,  9.71it/s]

Epoch 12, Batch 0, Loss: 6763.78173828125 RMSE(mm): 41.12110692296977


102it [00:10,  9.43it/s]

Epoch 12, Batch 100, Loss: 10295.59765625 RMSE(mm): 50.73361227098362


203it [00:21,  9.33it/s]

Epoch 12, Batch 200, Loss: 11515.580078125 RMSE(mm): 53.6553354246458


225it [00:23,  9.42it/s]