In [1]:
from models.EEGDeiT_pretrained_16stride import EEGViT_pretrained
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch


In [2]:
'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained()
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 129, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 33, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
create dataloader...
HI
training...


2it [00:00,  3.28it/s]

Epoch 0, Batch 0, Loss: 169178.125 RMSE(mm): 205.65634259608916


102it [00:12,  9.45it/s]

Epoch 0, Batch 100, Loss: 65523.8828125 RMSE(mm): 127.98816626206111


203it [00:22,  9.66it/s]

Epoch 0, Batch 200, Loss: 29969.4453125 RMSE(mm): 86.55842725075935


236it [00:26,  9.06it/s]


Epoch 0, Val Loss: 26456.55715880102, RMSE(mm): 81.32735880194473
Epoch 0, test Loss: 26714.447725183825, RMSE(mm): 81.72277486292273


2it [00:00,  9.34it/s]

Epoch 1, Batch 0, Loss: 24984.796875 RMSE(mm): 79.03289959725633


102it [00:10,  9.46it/s]

Epoch 1, Batch 100, Loss: 25217.69921875 RMSE(mm): 79.40040808892294


202it [00:21,  9.48it/s]

Epoch 1, Batch 200, Loss: 25389.08203125 RMSE(mm): 79.66975905456536


236it [00:24,  9.55it/s]


Epoch 1, Val Loss: 22249.13054049745, RMSE(mm): 74.58071221920827
Epoch 1, test Loss: 21946.08957567402, RMSE(mm): 74.07106313479309


1it [00:00,  9.60it/s]

Epoch 2, Batch 0, Loss: 22072.125 RMSE(mm): 74.28345206033441


102it [00:10,  9.43it/s]

Epoch 2, Batch 100, Loss: 20908.314453125 RMSE(mm): 72.29853811302999


203it [00:21,  9.55it/s]

Epoch 2, Batch 200, Loss: 20629.056640625 RMSE(mm): 71.81409443943612


236it [00:24,  9.49it/s]


Epoch 2, Val Loss: 17216.61503507653, RMSE(mm): 65.60604971166251
Epoch 2, test Loss: 16061.251972273285, RMSE(mm): 63.36649740255746


1it [00:00,  9.65it/s]

Epoch 3, Batch 0, Loss: 16501.33984375 RMSE(mm): 64.22877050775222


102it [00:10,  9.42it/s]

Epoch 3, Batch 100, Loss: 15526.2431640625 RMSE(mm): 62.30217324472417


202it [00:21,  9.48it/s]

Epoch 3, Batch 200, Loss: 19465.390625 RMSE(mm): 69.75921198128603


236it [00:25,  9.43it/s]


Epoch 3, Val Loss: 15244.489556760203, RMSE(mm): 61.7342886019597
Epoch 3, test Loss: 13173.789426317402, RMSE(mm): 57.3885646847815


1it [00:00,  9.43it/s]

Epoch 4, Batch 0, Loss: 13116.759765625 RMSE(mm): 57.26421169811255


102it [00:10,  9.57it/s]

Epoch 4, Batch 100, Loss: 13280.44921875 RMSE(mm): 57.6204156934632


202it [00:21,  9.58it/s]

Epoch 4, Batch 200, Loss: 18314.53125 RMSE(mm): 67.66559548618486


236it [00:24,  9.54it/s]


Epoch 4, Val Loss: 15481.953184789541, RMSE(mm): 62.2132485584653
Epoch 4, test Loss: 13222.427849264706, RMSE(mm): 57.49440809605902


1it [00:00,  9.44it/s]

Epoch 5, Batch 0, Loss: 12254.375 RMSE(mm): 55.349740288460254


102it [00:10,  9.35it/s]

Epoch 5, Batch 100, Loss: 11771.380859375 RMSE(mm): 54.247997334867115


202it [00:21,  9.30it/s]

Epoch 5, Batch 200, Loss: 18210.84375 RMSE(mm): 67.47377962957167


236it [00:24,  9.44it/s]


Epoch 5, Val Loss: 15629.359614158164, RMSE(mm): 62.50871862020162
Epoch 5, test Loss: 13191.564931832108, RMSE(mm): 57.42726907104348


1it [00:00,  9.51it/s]

Epoch 6, Batch 0, Loss: 12487.822265625 RMSE(mm): 55.874462560334756


102it [00:10,  9.44it/s]

Epoch 6, Batch 100, Loss: 14585.9931640625 RMSE(mm): 60.386242564143906


202it [00:21,  9.36it/s]

Epoch 6, Batch 200, Loss: 14815.8203125 RMSE(mm): 60.86012716159078


236it [00:25,  9.42it/s]


Epoch 6, Val Loss: 14462.481206154336, RMSE(mm): 60.13002828486433
Epoch 6, test Loss: 11712.987017463236, RMSE(mm): 54.11327706178779


1it [00:00,  9.69it/s]

Epoch 7, Batch 0, Loss: 10537.328125 RMSE(mm): 51.32574433215752


102it [00:10,  9.50it/s]

Epoch 7, Batch 100, Loss: 14429.125 RMSE(mm): 60.06064643341762


203it [00:21,  9.45it/s]

Epoch 7, Batch 200, Loss: 14694.025390625 RMSE(mm): 60.60945757599428


236it [00:24,  9.54it/s]


Epoch 7, Val Loss: 14431.808374521685, RMSE(mm): 60.06623089249417
Epoch 7, test Loss: 11626.232871859682, RMSE(mm): 53.912505209505156


1it [00:00,  9.29it/s]

Epoch 8, Batch 0, Loss: 10423.1044921875 RMSE(mm): 51.04680325982103


102it [00:10,  9.59it/s]

Epoch 8, Batch 100, Loss: 13970.572265625 RMSE(mm): 59.098587685377474


203it [00:21,  9.52it/s]

Epoch 8, Batch 200, Loss: 14614.7392578125 RMSE(mm): 60.44571791659956


236it [00:24,  9.57it/s]


Epoch 8, Val Loss: 14456.100546077807, RMSE(mm): 60.11676252526787
Epoch 8, test Loss: 11561.536803002451, RMSE(mm): 53.76229348484505


1it [00:00,  9.40it/s]

Epoch 9, Batch 0, Loss: 10021.34765625 RMSE(mm): 50.05334068833468


102it [00:10,  9.39it/s]

Epoch 9, Batch 100, Loss: 13640.53515625 RMSE(mm): 58.396350819743006


202it [00:21,  9.55it/s]

Epoch 9, Batch 200, Loss: 14457.92578125 RMSE(mm): 60.120557593160264


236it [00:25,  9.44it/s]


Epoch 9, Val Loss: 14549.18931361607, RMSE(mm): 60.31001018408153
Epoch 9, test Loss: 11518.50275735294, RMSE(mm): 53.662143912988


2it [00:00,  9.42it/s]

Epoch 10, Batch 0, Loss: 9750.6171875 RMSE(mm): 49.37260674579579


102it [00:10,  9.42it/s]

Epoch 10, Batch 100, Loss: 13162.35546875 RMSE(mm): 57.363654583608074


202it [00:21,  9.42it/s]

Epoch 10, Batch 200, Loss: 14240.19921875 RMSE(mm): 59.66615292347496


236it [00:25,  9.41it/s]


Epoch 10, Val Loss: 14681.403419961734, RMSE(mm): 60.58342062801038
Epoch 10, test Loss: 11527.552715226715, RMSE(mm): 53.68322064487822


1it [00:00,  9.47it/s]

Epoch 11, Batch 0, Loss: 9309.3076171875 RMSE(mm): 48.242376644366054


102it [00:10,  9.25it/s]

Epoch 11, Batch 100, Loss: 13011.146484375 RMSE(mm): 57.033206302063626


202it [00:21,  9.50it/s]

Epoch 11, Batch 200, Loss: 14171.80078125 RMSE(mm): 59.52268639193379


236it [00:25,  9.36it/s]


Epoch 11, Val Loss: 14821.732013313138, RMSE(mm): 60.87226793317532
Epoch 11, test Loss: 11529.176212086397, RMSE(mm): 53.687000782513444


1it [00:00,  9.70it/s]

Epoch 12, Batch 0, Loss: 8785.658203125 RMSE(mm): 46.86592099576461


103it [00:10,  9.40it/s]

Epoch 12, Batch 100, Loss: 12688.3125 RMSE(mm): 56.32120493206799


202it [00:21,  9.37it/s]

Epoch 12, Batch 200, Loss: 13412.443359375 RMSE(mm): 57.90605184126915


236it [00:24,  9.44it/s]


Epoch 12, Val Loss: 14586.083366549745, RMSE(mm): 60.38642928371768
Epoch 12, test Loss: 11215.073270909927, RMSE(mm): 52.95062150463847


2it [00:00,  9.48it/s]

Epoch 13, Batch 0, Loss: 8485.73046875 RMSE(mm): 46.05901233404273


103it [00:10,  9.61it/s]

Epoch 13, Batch 100, Loss: 12494.0390625 RMSE(mm): 55.88836878658206


203it [00:21,  9.61it/s]

Epoch 13, Batch 200, Loss: 13533.72265625 RMSE(mm): 58.16726453996698


236it [00:24,  9.60it/s]


Epoch 13, Val Loss: 14563.949896364797, RMSE(mm): 60.340595572891054
Epoch 13, test Loss: 11170.286238128063, RMSE(mm): 52.844787439557514


1it [00:00,  9.43it/s]

Epoch 14, Batch 0, Loss: 8732.9384765625 RMSE(mm): 46.72509624538643


102it [00:10,  9.52it/s]

Epoch 14, Batch 100, Loss: 12708.7958984375 RMSE(mm): 56.36664771484441


203it [00:21,  9.32it/s]

Epoch 14, Batch 200, Loss: 13738.8955078125 RMSE(mm): 58.6065173590201


236it [00:24,  9.47it/s]


Epoch 14, Val Loss: 14571.983667490435, RMSE(mm): 60.35723582862794
Epoch 14, test Loss: 11159.927667356005, RMSE(mm): 52.82027940894483
