In [1]:
from importlib import reload
from dataset.EEGEyeNet_MTL import EEGEyeNetDataset
import torch
from models.MTLVit_pretrained_pupil_cat import MTLViT_pretrained
from helper_function_pupil import train
'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
EEGEyeNet = EEGEyeNetDataset('./dataset\MTL_data\Position_task_with_dots_synchronized_min.npz')


loading data...
[[1.000e+00 4.081e+02 3.151e+02 3.323e+03]
 [1.000e+00 6.407e+02 5.191e+02 3.062e+03]
 [1.000e+00 4.042e+02 1.188e+02 3.417e+03]
 ...
 [3.000e+01 1.155e+02 3.061e+02 1.910e+03]
 [3.000e+01 7.320e+02 3.103e+02 1.723e+03]
 [3.000e+01 6.322e+02 3.536e+02 1.763e+03]]


In [2]:
import models.MTLVit_pretrained_pupil_cat as MTLVit_pretrained_pupil_cat
import helper_function_pupil
reload(MTLVit_pretrained_pupil_cat)
reload(helper_function_pupil)
from models.MTLVit_pretrained_pupil_cat import MTLViT_pretrained
from helper_function_pupil import train
batch_size = 64
n_epoch = 30
learning_rate = 1e-4
model_name = 'MTL_pupil_cat_VIT_pre_16stride'
i=0
model = MTLViT_pretrained()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
file_name = f'{model_name}_weight_test_{i}'
train(model,EEGEyeNet, optimizer, scheduler,log_name=file_name, batch_size = batch_size ,n_epoch = n_epoch, subtask_weight=i)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-large-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 1024]) in the checkpoint and torch.Size([1, 113, 1024]) in the model instantiated
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([1024, 3, 16, 16]) in the checkpoint and torch.Size([1024, 256, 16, 1]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


1it [00:01,  1.15s/it]

Epoch 0, Batch 0, position loss: 159955.078125 reconstruction loss: 0.0 RMSE(mm): 199.97192185716975


101it [00:45,  2.28it/s]

Epoch 0, Batch 100, position loss: 25834.6015625 reconstruction loss: 0.0 RMSE(mm): 80.36572895597351


201it [01:28,  2.28it/s]

Epoch 0, Batch 200, position loss: 32546.484375 reconstruction loss: 0.0 RMSE(mm): 90.20322108300789


230it [01:41,  2.26it/s]


Epoch 0, Val Loss: 20374.82850060096, RMSE(mm): 71.3702117493723
Epoch 0, test Loss: 22473.299447866586, RMSE(mm): 74.95548586972568


1it [00:00,  2.26it/s]

Epoch 1, Batch 0, position loss: 17995.13671875 reconstruction loss: 0.0 RMSE(mm): 67.07297652324296


101it [00:44,  2.27it/s]

Epoch 1, Batch 100, position loss: 15544.5849609375 reconstruction loss: 0.0 RMSE(mm): 62.33896245715335


201it [01:28,  2.27it/s]

Epoch 1, Batch 200, position loss: 26603.458984375 reconstruction loss: 0.0 RMSE(mm): 81.55283407763184


230it [01:41,  2.27it/s]


Epoch 1, Val Loss: 17388.72832782452, RMSE(mm): 65.93316374902793
Epoch 1, test Loss: 17739.360201322117, RMSE(mm): 66.59459475310688


1it [00:00,  2.26it/s]

Epoch 2, Batch 0, position loss: 14280.5830078125 reconstruction loss: 0.0 RMSE(mm): 59.750696665002366


101it [00:44,  2.28it/s]

Epoch 2, Batch 100, position loss: 13254.28515625 reconstruction loss: 0.0 RMSE(mm): 57.56362817841228


201it [01:28,  2.27it/s]

Epoch 2, Batch 200, position loss: 21707.44140625 reconstruction loss: 0.0 RMSE(mm): 73.66722712008712


230it [01:41,  2.28it/s]


Epoch 2, Val Loss: 17436.934344951922, RMSE(mm): 66.02449232094088
Epoch 2, test Loss: 16953.598013070914, RMSE(mm): 65.10299150782342


1it [00:00,  2.26it/s]

Epoch 3, Batch 0, position loss: 13732.18359375 reconstruction loss: 0.0 RMSE(mm): 58.592199979498126


101it [00:44,  2.26it/s]

Epoch 3, Batch 100, position loss: 12804.517578125 reconstruction loss: 0.0 RMSE(mm): 56.57852414592705


201it [01:31,  2.09it/s]

Epoch 3, Batch 200, position loss: 20006.908203125 reconstruction loss: 0.0 RMSE(mm): 70.72288915748034


230it [01:45,  2.17it/s]


Epoch 3, Val Loss: 16939.905254657453, RMSE(mm): 65.07669562650183
Epoch 3, test Loss: 15880.478365384615, RMSE(mm): 63.008885019068174


1it [00:00,  2.35it/s]

Epoch 4, Batch 0, position loss: 12603.7294921875 reconstruction loss: 0.0 RMSE(mm): 56.13316642633725


101it [00:42,  2.33it/s]

Epoch 4, Batch 100, position loss: 12394.400390625 reconstruction loss: 0.0 RMSE(mm): 55.66507071455357


201it [01:30,  2.35it/s]

Epoch 4, Batch 200, position loss: 18069.103515625 reconstruction loss: 0.0 RMSE(mm): 67.21068277369491


230it [01:42,  2.24it/s]


Epoch 4, Val Loss: 17068.632474459133, RMSE(mm): 65.32348826122794
Epoch 4, test Loss: 15626.96875, RMSE(mm): 62.50393737597656


1it [00:00,  2.34it/s]

Epoch 5, Batch 0, position loss: 12893.3369140625 reconstruction loss: 0.0 RMSE(mm): 56.774415263528915


101it [00:42,  2.37it/s]

Epoch 5, Batch 100, position loss: 11517.3271484375 reconstruction loss: 0.0 RMSE(mm): 53.65940539280486


201it [01:25,  2.38it/s]

Epoch 5, Batch 200, position loss: 17349.5546875 reconstruction loss: 0.0 RMSE(mm): 65.85885416460721


230it [01:37,  2.36it/s]


Epoch 5, Val Loss: 17117.932091346152, RMSE(mm): 65.4177577026035
Epoch 5, test Loss: 15741.106332632211, RMSE(mm): 62.73178287884103


1it [00:00,  2.34it/s]

Epoch 6, Batch 0, position loss: 12435.30078125 reconstruction loss: 0.0 RMSE(mm): 55.756839897114865


101it [00:42,  2.35it/s]

Epoch 6, Batch 100, position loss: 10204.572265625 reconstruction loss: 0.0 RMSE(mm): 50.508841467670294


201it [01:25,  2.35it/s]

Epoch 6, Batch 200, position loss: 13119.38671875 reconstruction loss: 0.0 RMSE(mm): 57.269945693072735


230it [01:37,  2.36it/s]


Epoch 6, Val Loss: 15066.971660907451, RMSE(mm): 61.37379664992922
Epoch 6, test Loss: 12844.61865234375, RMSE(mm): 56.6670509474945


1it [00:00,  2.34it/s]

Epoch 7, Batch 0, position loss: 10619.86328125 reconstruction loss: 0.0 RMSE(mm): 51.52636044116157


101it [00:42,  2.37it/s]

Epoch 7, Batch 100, position loss: 9586.57421875 reconstruction loss: 0.0 RMSE(mm): 48.95552629364227


201it [01:25,  2.37it/s]

Epoch 7, Batch 200, position loss: 12268.107421875 reconstruction loss: 0.0 RMSE(mm): 55.380744446682456


230it [01:37,  2.36it/s]


Epoch 7, Val Loss: 15142.203237680289, RMSE(mm): 61.52682999651512
Epoch 7, test Loss: 12823.942138671875, RMSE(mm): 56.621422930441874


1it [00:00,  2.33it/s]

Epoch 8, Batch 0, position loss: 9862.146484375 reconstruction loss: 0.0 RMSE(mm): 49.65417022862984


101it [00:43,  2.36it/s]

Epoch 8, Batch 100, position loss: 8499.5166015625 reconstruction loss: 0.0 RMSE(mm): 46.09641146977306


201it [01:25,  2.37it/s]

Epoch 8, Batch 200, position loss: 11302.5927734375 reconstruction loss: 0.0 RMSE(mm): 53.156826404135295


230it [01:37,  2.35it/s]


Epoch 8, Val Loss: 15221.765681340145, RMSE(mm): 61.68825998790237
Epoch 8, test Loss: 12675.317063551684, RMSE(mm): 56.292355305919834


1it [00:00,  2.34it/s]

Epoch 9, Batch 0, position loss: 8754.87890625 reconstruction loss: 0.0 RMSE(mm): 46.78375494295536


101it [00:42,  2.32it/s]

Epoch 9, Batch 100, position loss: 8037.05078125 reconstruction loss: 0.0 RMSE(mm): 44.82480000303961


201it [01:25,  2.33it/s]

Epoch 9, Batch 200, position loss: 10532.9287109375 reconstruction loss: 0.0 RMSE(mm): 51.315028770666935


230it [01:38,  2.34it/s]


Epoch 9, Val Loss: 15407.902108999398, RMSE(mm): 62.06428544058048
Epoch 9, test Loss: 12719.644634540264, RMSE(mm): 56.3907009943578


1it [00:00,  2.35it/s]

Epoch 10, Batch 0, position loss: 8199.0205078125 reconstruction loss: 0.0 RMSE(mm): 45.27422143950269


101it [00:42,  2.37it/s]

Epoch 10, Batch 100, position loss: 7061.45361328125 reconstruction loss: 0.0 RMSE(mm): 42.01622785686874


201it [01:25,  2.35it/s]

Epoch 10, Batch 200, position loss: 9797.232421875 reconstruction loss: 0.0 RMSE(mm): 49.49048499932841


230it [01:37,  2.36it/s]


Epoch 10, Val Loss: 15707.013239933895, RMSE(mm): 62.663811805407065
Epoch 10, test Loss: 12781.16532076322, RMSE(mm): 56.52690801902051


1it [00:00,  2.32it/s]

Epoch 11, Batch 0, position loss: 7629.1220703125 reconstruction loss: 0.0 RMSE(mm): 43.67242284987318


101it [00:43,  2.32it/s]

Epoch 11, Batch 100, position loss: 6754.54541015625 reconstruction loss: 0.0 RMSE(mm): 41.09302072784456


155it [01:06,  2.33it/s]


KeyboardInterrupt: 