In [1]:
from importlib import reload
from dataset.EEGEyeNet_MTL import EEGEyeNetDataset
import torch
from models.MTLVit_pretrained_pupil_cat import MTLViT_pretrained
from helper_function_pupil import train
'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
EEGEyeNet = EEGEyeNetDataset('./dataset\MTL_data\Position_task_with_dots_synchronized_min.npz')


loading data...
[[1.000e+00 4.081e+02 3.151e+02 3.323e+03]
 [1.000e+00 6.407e+02 5.191e+02 3.062e+03]
 [1.000e+00 4.042e+02 1.188e+02 3.417e+03]
 ...
 [3.000e+01 1.155e+02 3.061e+02 1.910e+03]
 [3.000e+01 7.320e+02 3.103e+02 1.723e+03]
 [3.000e+01 6.322e+02 3.536e+02 1.763e+03]]


In [2]:
import models.MTLVit_pretrained_pupil_cat as MTLVit_pretrained_pupil_cat
import helper_function_pupil
reload(MTLVit_pretrained_pupil_cat)
reload(helper_function_pupil)
from models.MTLVit_pretrained_pupil_cat import MTLViT_pretrained
from helper_function_pupil import train
batch_size = 64
n_epoch = 30
learning_rate = 1e-4
model_name = 'MTL_pupil_cat_VIT_pre_16stride'
i=0
model = MTLViT_pretrained()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
file_name = f'{model_name}_weight_test_{i}'
train(model,EEGEyeNet, optimizer, scheduler,log_name=file_name, batch_size = batch_size ,n_epoch = n_epoch, subtask_weight=i)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-large-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 1024]) in the checkpoint and torch.Size([1, 15, 1024]) in the model instantiated
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([1024, 3, 16, 16]) in the checkpoint and torch.Size([1024, 256, 129, 1]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


1it [00:00,  1.32it/s]

Epoch 0, Batch 0, position loss: 180431.75 reconstruction loss: 0.0 RMSE(mm): 212.3862931076297


102it [00:13,  8.14it/s]

Epoch 0, Batch 100, position loss: 17713.0078125 reconstruction loss: 0.0 RMSE(mm): 66.54511216554526


202it [00:25,  8.20it/s]

Epoch 0, Batch 200, position loss: 32069.55078125 reconstruction loss: 0.0 RMSE(mm): 89.53986651381886


230it [00:28,  7.96it/s]


Epoch 0, Val Loss: 16859.013315054086, RMSE(mm): 64.92113160415121
Epoch 0, test Loss: 18015.92765925481, RMSE(mm): 67.11171220296575


1it [00:00,  8.22it/s]

Epoch 1, Batch 0, position loss: 13445.4091796875 reconstruction loss: 0.0 RMSE(mm): 57.97717046322522


102it [00:12,  8.07it/s]

Epoch 1, Batch 100, position loss: 15827.5390625 reconstruction loss: 0.0 RMSE(mm): 62.90377385837037


202it [00:24,  8.22it/s]

Epoch 1, Batch 200, position loss: 22947.361328125 reconstruction loss: 0.0 RMSE(mm): 75.7419324550889


230it [00:28,  8.16it/s]


Epoch 1, Val Loss: 16520.08740234375, RMSE(mm): 64.2652460555932
Epoch 1, test Loss: 16332.425555889424, RMSE(mm): 63.899189266941065


1it [00:00,  8.13it/s]

Epoch 2, Batch 0, position loss: 14346.83203125 reconstruction loss: 0.0 RMSE(mm): 59.88913096558089


102it [00:12,  8.13it/s]

Epoch 2, Batch 100, position loss: 15102.2548828125 reconstruction loss: 0.0 RMSE(mm): 61.445615959994456


202it [00:24,  8.10it/s]

Epoch 2, Batch 200, position loss: 21761.8984375 reconstruction loss: 0.0 RMSE(mm): 73.75957300157722


230it [00:28,  8.12it/s]


Epoch 2, Val Loss: 16485.082744891828, RMSE(mm): 64.19712366004381
Epoch 2, test Loss: 15285.89716045673, RMSE(mm): 61.818074137861835


1it [00:00,  8.18it/s]

Epoch 3, Batch 0, position loss: 13996.705078125 reconstruction loss: 0.0 RMSE(mm): 59.153835628226595


102it [00:12,  8.21it/s]

Epoch 3, Batch 100, position loss: 12757.90234375 reconstruction loss: 0.0 RMSE(mm): 56.475442326178374


202it [00:24,  8.13it/s]

Epoch 3, Batch 200, position loss: 20108.64453125 reconstruction loss: 0.0 RMSE(mm): 70.90247621072554


230it [00:28,  8.19it/s]


Epoch 3, Val Loss: 17124.67803485577, RMSE(mm): 65.43064655582995
Epoch 3, test Loss: 15289.80429311899, RMSE(mm): 61.82597409891532


1it [00:00,  8.27it/s]

Epoch 4, Batch 0, position loss: 13537.1044921875 reconstruction loss: 0.0 RMSE(mm): 58.17453156706013


102it [00:12,  8.17it/s]

Epoch 4, Batch 100, position loss: 11898.4833984375 reconstruction loss: 0.0 RMSE(mm): 54.54008479649968


202it [00:24,  8.28it/s]

Epoch 4, Batch 200, position loss: 17986.5234375 reconstruction loss: 0.0 RMSE(mm): 67.05692253134646


230it [00:28,  8.18it/s]


Epoch 4, Val Loss: 17493.17976262019, RMSE(mm): 66.13089248343053
Epoch 4, test Loss: 15409.853553185096, RMSE(mm): 62.06821560425492


1it [00:00,  8.19it/s]

Epoch 5, Batch 0, position loss: 14616.5029296875 reconstruction loss: 0.0 RMSE(mm): 60.44936502910411


102it [00:12,  8.19it/s]

Epoch 5, Batch 100, position loss: 11694.8837890625 reconstruction loss: 0.0 RMSE(mm): 54.07144299226372


202it [00:24,  8.10it/s]

Epoch 5, Batch 200, position loss: 16322.8134765625 reconstruction loss: 0.0 RMSE(mm): 63.88038328893014


230it [00:28,  8.13it/s]


Epoch 5, Val Loss: 16135.69473031851, RMSE(mm): 63.51317723574871
Epoch 5, test Loss: 13912.709528996395, RMSE(mm): 58.9760746595524


1it [00:00,  8.24it/s]

Epoch 6, Batch 0, position loss: 11689.1611328125 reconstruction loss: 0.0 RMSE(mm): 54.05821198673819


102it [00:12,  8.18it/s]

Epoch 6, Batch 100, position loss: 11017.642578125 reconstruction loss: 0.0 RMSE(mm): 52.48247940533345


202it [00:24,  8.13it/s]

Epoch 6, Batch 200, position loss: 11608.603515625 reconstruction loss: 0.0 RMSE(mm): 53.87161477908612


230it [00:28,  8.12it/s]


Epoch 6, Val Loss: 13645.820087139424, RMSE(mm): 58.407662355078514
Epoch 6, test Loss: 11225.789513221154, RMSE(mm): 52.975913189913854


1it [00:00,  8.28it/s]

Epoch 7, Batch 0, position loss: 10267.5849609375 reconstruction loss: 0.0 RMSE(mm): 50.66454618601034


102it [00:12,  8.16it/s]

Epoch 7, Batch 100, position loss: 10270.896484375 reconstruction loss: 0.0 RMSE(mm): 50.67271574618584


202it [00:24,  8.22it/s]

Epoch 7, Batch 200, position loss: 10828.60546875 reconstruction loss: 0.0 RMSE(mm): 52.03029278398787


230it [00:28,  8.21it/s]


Epoch 7, Val Loss: 13727.287043644832, RMSE(mm): 58.58175279821532
Epoch 7, test Loss: 11237.14627779447, RMSE(mm): 53.00270341641658


1it [00:00,  8.18it/s]

Epoch 8, Batch 0, position loss: 10356.080078125 reconstruction loss: 0.0 RMSE(mm): 50.88241365669724


102it [00:12,  8.14it/s]

Epoch 8, Batch 100, position loss: 10041.916015625 reconstruction loss: 0.0 RMSE(mm): 50.10468045907737


202it [00:24,  8.24it/s]

Epoch 8, Batch 200, position loss: 10518.9052734375 reconstruction loss: 0.0 RMSE(mm): 51.28085723112841


230it [00:28,  8.19it/s]


Epoch 8, Val Loss: 13816.19296499399, RMSE(mm): 58.77115143715067
Epoch 8, test Loss: 11258.23270357572, RMSE(mm): 53.052409708645


1it [00:00,  8.18it/s]

Epoch 9, Batch 0, position loss: 9393.71484375 reconstruction loss: 0.0 RMSE(mm): 48.460589254955416


102it [00:12,  8.04it/s]

Epoch 9, Batch 100, position loss: 10035.994140625 reconstruction loss: 0.0 RMSE(mm): 50.08990452332935


202it [00:24,  8.08it/s]

Epoch 9, Batch 200, position loss: 10052.4306640625 reconstruction loss: 0.0 RMSE(mm): 50.13090529818532


230it [00:28,  8.10it/s]


Epoch 9, Val Loss: 14046.070040189303, RMSE(mm): 59.25805860849076
Epoch 9, test Loss: 11429.788677509014, RMSE(mm): 53.4550948869914


1it [00:00,  8.16it/s]

Epoch 10, Batch 0, position loss: 9093.05078125 reconstruction loss: 0.0 RMSE(mm): 47.67874469103082


102it [00:12,  8.16it/s]

Epoch 10, Batch 100, position loss: 9657.8193359375 reconstruction loss: 0.0 RMSE(mm): 49.13710241746429


202it [00:24,  8.19it/s]

Epoch 10, Batch 200, position loss: 9602.35546875 reconstruction loss: 0.0 RMSE(mm): 48.9958045876124


230it [00:28,  8.21it/s]


Epoch 10, Val Loss: 14284.771503155049, RMSE(mm): 59.75945846298109
Epoch 10, test Loss: 11615.736328125, RMSE(mm): 53.888162726439745


1it [00:00,  8.03it/s]

Epoch 11, Batch 0, position loss: 8276.86328125 reconstruction loss: 0.0 RMSE(mm): 45.48863396841567


102it [00:12,  8.09it/s]

Epoch 11, Batch 100, position loss: 9091.853515625 reconstruction loss: 0.0 RMSE(mm): 47.67560570046541


202it [00:24,  8.23it/s]

Epoch 11, Batch 200, position loss: 8838.0458984375 reconstruction loss: 0.0 RMSE(mm): 47.00544090431846


202it [00:24,  8.11it/s]


KeyboardInterrupt: 