In [1]:
from models.MTLVit import MTLViT_pretrained
from helper_function_test import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch


In [2]:
'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained()
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
create dataloader...
HI
training...


1it [00:01,  1.13s/it]

Epoch 0, Batch 0, Loss: 169089.71875 RMSE(mm): 205.60260136365005


101it [00:30,  3.37it/s]

Epoch 0, Batch 100, Loss: 66942.265625 RMSE(mm): 129.3660172002292


201it [01:00,  3.36it/s]

Epoch 0, Batch 200, Loss: 33310.97265625 RMSE(mm): 91.25646916280785


236it [01:10,  3.34it/s]


Epoch 0, Val Loss: 27971.92677774235, RMSE(mm): 83.62404973711563
Epoch 0, test Loss: 28100.397365196077, RMSE(mm): 83.81586568961166


1it [00:00,  3.36it/s]

Epoch 1, Batch 0, Loss: 25980.76953125 RMSE(mm): 80.59275639170372


101it [00:30,  3.35it/s]

Epoch 1, Batch 100, Loss: 25462.453125 RMSE(mm): 79.78479354645219


201it [01:00,  3.35it/s]

Epoch 1, Batch 200, Loss: 26982.6875 RMSE(mm): 82.13203927213789


236it [01:10,  3.35it/s]


Epoch 1, Val Loss: 23764.381018813776, RMSE(mm): 77.07850059973562
Epoch 1, test Loss: 22832.524739583332, RMSE(mm): 75.5521752492662


1it [00:00,  3.34it/s]

Epoch 2, Batch 0, Loss: 20776.599609375 RMSE(mm): 72.07045096531414


101it [00:30,  3.36it/s]

Epoch 2, Batch 100, Loss: 22995.46484375 RMSE(mm): 75.82127808826161


201it [00:59,  3.34it/s]

Epoch 2, Batch 200, Loss: 22908.251953125 RMSE(mm): 75.67736113449814


236it [01:10,  3.36it/s]


Epoch 2, Val Loss: 18700.42024075255, RMSE(mm): 68.37473992775503
Epoch 2, test Loss: 17156.085037530636, RMSE(mm): 65.4906196289412


1it [00:00,  3.39it/s]

Epoch 3, Batch 0, Loss: 15815.8935546875 RMSE(mm): 62.88062808744737


101it [00:30,  3.35it/s]

Epoch 3, Batch 100, Loss: 17825.8515625 RMSE(mm): 66.75674415836201


201it [00:59,  3.35it/s]

Epoch 3, Batch 200, Loss: 21908.28515625 RMSE(mm): 74.00723808562579


236it [01:10,  3.36it/s]


Epoch 3, Val Loss: 16260.353276466836, RMSE(mm): 63.75804513249061
Epoch 3, test Loss: 13910.05832567402, RMSE(mm): 58.970455156955545


1it [00:00,  3.36it/s]

Epoch 4, Batch 0, Loss: 13607.5068359375 RMSE(mm): 58.32560937516534


101it [00:30,  3.36it/s]

Epoch 4, Batch 100, Loss: 13573.6533203125 RMSE(mm): 58.2530113391413


201it [00:59,  3.35it/s]

Epoch 4, Batch 200, Loss: 17025.451171875 RMSE(mm): 65.24080619496321


236it [01:10,  3.36it/s]


Epoch 4, Val Loss: 15884.564473054847, RMSE(mm): 63.01699071094804
Epoch 4, test Loss: 13202.013308057598, RMSE(mm): 57.45000719768797


1it [00:00,  3.34it/s]

Epoch 5, Batch 0, Loss: 11819.154296875 RMSE(mm): 54.357966980183775


101it [00:30,  3.36it/s]

Epoch 5, Batch 100, Loss: 11905.44140625 RMSE(mm): 54.55602947028403


201it [00:59,  3.37it/s]

Epoch 5, Batch 200, Loss: 15480.044921875 RMSE(mm): 62.20941432346675


236it [01:10,  3.36it/s]


Epoch 5, Val Loss: 16057.45240752551, RMSE(mm): 63.35900174309391
Epoch 5, test Loss: 13206.907111672794, RMSE(mm): 57.46065417238302


1it [00:00,  3.37it/s]

Epoch 6, Batch 0, Loss: 10969.74609375 RMSE(mm): 52.36827783532222


101it [00:30,  3.35it/s]

Epoch 6, Batch 100, Loss: 13238.9248046875 RMSE(mm): 57.53026335044778


201it [00:59,  3.37it/s]

Epoch 6, Batch 200, Loss: 13349.2373046875 RMSE(mm): 57.769449765181896


236it [01:10,  3.36it/s]


Epoch 6, Val Loss: 14965.694913903062, RMSE(mm): 61.16717852309166
Epoch 6, test Loss: 12528.22403492647, RMSE(mm): 55.964774713489355


1it [00:00,  3.37it/s]

Epoch 7, Batch 0, Loss: 9517.9736328125 RMSE(mm): 48.78005133456836


101it [00:30,  3.36it/s]

Epoch 7, Batch 100, Loss: 12594.48828125 RMSE(mm): 56.11258388554656


201it [00:59,  3.36it/s]

Epoch 7, Batch 200, Loss: 12736.37890625 RMSE(mm): 56.42778328591776


236it [01:10,  3.35it/s]


Epoch 7, Val Loss: 14861.674465880102, RMSE(mm): 60.95423378625988
Epoch 7, test Loss: 12478.949065563726, RMSE(mm): 55.85460828249475


1it [00:00,  3.36it/s]

Epoch 8, Batch 0, Loss: 9020.6748046875 RMSE(mm): 47.48861654303982


101it [00:30,  3.35it/s]

Epoch 8, Batch 100, Loss: 11761.064453125 RMSE(mm): 54.22422072544012


201it [00:59,  3.36it/s]

Epoch 8, Batch 200, Loss: 12071.357421875 RMSE(mm): 54.93486466233215


236it [01:10,  3.36it/s]


Epoch 8, Val Loss: 14845.48219268176, RMSE(mm): 60.92101893575353
Epoch 8, test Loss: 12464.136967677696, RMSE(mm): 55.82144965798921


1it [00:00,  3.38it/s]

Epoch 9, Batch 0, Loss: 8701.271484375 RMSE(mm): 46.64030307677846


101it [00:30,  3.35it/s]

Epoch 9, Batch 100, Loss: 11112.24609375 RMSE(mm): 52.707319448417216


201it [00:59,  3.35it/s]

Epoch 9, Batch 200, Loss: 11572.59765625 RMSE(mm): 53.788004369585046


236it [01:10,  3.36it/s]


Epoch 9, Val Loss: 14869.17994658801, RMSE(mm): 60.96962347470257
Epoch 9, test Loss: 12443.922889859068, RMSE(mm): 55.7761662582215


1it [00:00,  3.36it/s]

Epoch 10, Batch 0, Loss: 8711.5361328125 RMSE(mm): 46.6678051037664


101it [00:30,  3.37it/s]

Epoch 10, Batch 100, Loss: 10810.484375 RMSE(mm): 51.98673959530449


201it [00:59,  3.35it/s]

Epoch 10, Batch 200, Loss: 10639.091796875 RMSE(mm): 51.572986623025336


236it [01:10,  3.36it/s]


Epoch 10, Val Loss: 14948.372110172193, RMSE(mm): 61.131767744300085
Epoch 10, test Loss: 12436.539119944853, RMSE(mm): 55.759616031552916


1it [00:00,  3.39it/s]

Epoch 11, Batch 0, Loss: 8420.09765625 RMSE(mm): 45.880545049753934


101it [00:30,  3.22it/s]

Epoch 11, Batch 100, Loss: 10472.1318359375 RMSE(mm): 51.16671729732498


201it [00:57,  3.71it/s]

Epoch 11, Batch 200, Loss: 9938.357421875 RMSE(mm): 49.84565533192186


236it [01:07,  3.52it/s]


Epoch 11, Val Loss: 15003.343560666453, RMSE(mm): 61.24406820392171
Epoch 11, test Loss: 12419.346622242647, RMSE(mm): 55.72106114891085


1it [00:00,  3.71it/s]

Epoch 12, Batch 0, Loss: 8051.6005859375 RMSE(mm): 44.86535574900053


101it [00:27,  3.71it/s]

Epoch 12, Batch 100, Loss: 11511.060546875 RMSE(mm): 53.6448053097292


201it [00:54,  3.71it/s]

Epoch 12, Batch 200, Loss: 8871.439453125 RMSE(mm): 47.09415954533269


236it [01:04,  3.68it/s]


Epoch 12, Val Loss: 14754.736706792091, RMSE(mm): 60.73453858142023
Epoch 12, test Loss: 12047.20778760723, RMSE(mm): 54.87988654235546


1it [00:00,  3.72it/s]

Epoch 13, Batch 0, Loss: 7636.3564453125 RMSE(mm): 43.693124302664884


101it [00:27,  3.72it/s]

Epoch 13, Batch 100, Loss: 11443.201171875 RMSE(mm): 53.48644962014912


201it [00:54,  3.71it/s]

Epoch 13, Batch 200, Loss: 8739.146484375 RMSE(mm): 46.74170109328232


236it [01:03,  3.72it/s]


Epoch 13, Val Loss: 14716.408940529336, RMSE(mm): 60.65560349326626
Epoch 13, test Loss: 12003.314079733456, RMSE(mm): 54.77981854600619


1it [00:00,  3.72it/s]

Epoch 14, Batch 0, Loss: 7598.98583984375 RMSE(mm): 43.58608103467135


101it [00:27,  3.71it/s]

Epoch 14, Batch 100, Loss: 11569.6513671875 RMSE(mm): 53.781156939925296


201it [00:54,  3.71it/s]

Epoch 14, Batch 200, Loss: 8829.46484375 RMSE(mm): 46.982616050380805


236it [01:03,  3.72it/s]


Epoch 14, Val Loss: 14713.163125797193, RMSE(mm): 60.648914099506335
Epoch 14, test Loss: 11995.387274050245, RMSE(mm): 54.76172768012859
