In [3]:
from models.MTLVit import MTLViT_pretrained
from helper_function_test import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
for i in range(1, 11):
    model = MTLViT_pretrained()
    EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')
    batch_size = 64
    n_epoch = 15
    learning_rate = 1e-4
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
    train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch, reconstruction_weight=i*0.1)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
create dataloader...
HI
training...


1it [00:08,  8.63s/it]

Epoch 0, Batch 0, position loss: 169169.125                    reconstruction loss: 80.14128875732422 + RMSE(mm): 205.65087223252908


101it [00:44,  3.09it/s]

Epoch 0, Batch 100, position loss: 105967.1328125                    reconstruction loss: 53.155582427978516 + RMSE(mm): 162.7629663133632


201it [01:17,  3.22it/s]

Epoch 0, Batch 200, position loss: 45534.453125                    reconstruction loss: 114.72272491455078 + RMSE(mm): 106.69401708273055


236it [01:28,  2.68it/s]


Epoch 0, Val Loss: 38823.9837372449, RMSE(mm): 98.51901305997347
Epoch 0, test Loss: 40178.22794117647, RMSE(mm): 100.22253731219399


1it [00:00,  3.17it/s]

Epoch 1, Batch 0, position loss: 39897.7265625                    reconstruction loss: 79.29247283935547 + RMSE(mm): 99.87207638086333


101it [00:31,  3.22it/s]

Epoch 1, Batch 100, position loss: 28997.5625                    reconstruction loss: 53.12081527709961 + RMSE(mm): 85.14335338122407


201it [01:02,  3.24it/s]

Epoch 1, Batch 200, position loss: 30364.0078125                    reconstruction loss: 114.77759552001953 + RMSE(mm): 87.12635624841084


236it [01:14,  3.17it/s]


Epoch 1, Val Loss: 24099.402383609693, RMSE(mm): 77.61991107893917
Epoch 1, test Loss: 23938.82372089461, RMSE(mm): 77.36088113655151


1it [00:00,  2.56it/s]

Epoch 2, Batch 0, position loss: 23327.662109375                    reconstruction loss: 79.12995147705078 + RMSE(mm): 76.36697929958831


101it [00:38,  2.72it/s]

Epoch 2, Batch 100, position loss: 24850.361328125                    reconstruction loss: 52.821563720703125 + RMSE(mm): 78.81998688169931


201it [01:17,  2.56it/s]

Epoch 2, Batch 200, position loss: 25028.9453125                    reconstruction loss: 114.51458740234375 + RMSE(mm): 79.10269482214244


236it [01:31,  2.59it/s]


Epoch 2, Val Loss: 19878.884685905614, RMSE(mm): 70.49624934332608
Epoch 2, test Loss: 18897.272843903185, RMSE(mm): 68.73367596001101


1it [00:00,  2.67it/s]

Epoch 3, Batch 0, position loss: 19285.78125                    reconstruction loss: 78.81832122802734 + RMSE(mm): 69.43662803232887


101it [00:37,  3.20it/s]

Epoch 3, Batch 100, position loss: 17728.103515625                    reconstruction loss: 52.31048583984375 + RMSE(mm): 66.57346227218657


101it [00:38,  2.65it/s]


KeyboardInterrupt: 