In [1]:
from models.MTLVit_pretrained_pupil import MTLViT_pretrained
from helper_function_pupil import train
from dataset.EEGEyeNet_MTL import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
EEGEyeNet = EEGEyeNetDataset('./dataset\MTL_data\Position_task_with_dots_synchronized_min.npz')
batch_size = 64
n_epoch = 30
learning_rate = 1e-4
model_name = 'MTL_pupil_VIT_pre'
i=0.0005
model = MTLViT_pretrained()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
file_name = f'{model_name}_weight_test_{i}'
train(model,EEGEyeNet, optimizer, scheduler,log_name=file_name, batch_size = batch_size ,n_epoch = n_epoch, subtask_weight=i)

loading data...
[[1.000e+00 4.081e+02 3.151e+02 3.323e+03]
 [1.000e+00 6.407e+02 5.191e+02 3.062e+03]
 [1.000e+00 4.042e+02 1.188e+02 3.417e+03]
 ...
 [3.000e+01 1.155e+02 3.061e+02 1.910e+03]
 [3.000e+01 7.320e+02 3.103e+02 1.723e+03]
 [3.000e+01 6.322e+02 3.536e+02 1.763e+03]]


Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


1it [00:07,  7.96s/it]

Epoch 0, Batch 0, position loss: 168865.40625 reconstruction loss: 9829259.0 RMSE(mm): 205.46618106759078


11it [00:12,  1.18s/it]


KeyboardInterrupt: 

create dataloader...
HI
training...


0it [00:00, ?it/s]


AttributeError: 'MTLViT_pretrained' object has no attribute 'ViT_model'