In [1]:
from models.MTLVit import MTLViT_pretrained
from helper_function_test import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
model_name = 'MTL_Recon_VIT_pre'

model = MTLViT_pretrained()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
file_name = f'{model_name}_weight_{0}'
train(model,EEGEyeNet, optimizer, scheduler,log_name=file_name, batch_size = batch_size ,n_epoch = n_epoch, reconstruction_weight=0)

loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]


Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


1it [00:02,  2.93s/it]

Epoch 0, Batch 0, position loss: 169040.046875 reconstruction loss: 80.14862060546875 RMSE(mm): 205.5724001872576


101it [00:33,  3.29it/s]

Epoch 0, Batch 100, position loss: 102164.546875 reconstruction loss: 53.623661041259766 RMSE(mm): 159.81594638442687


201it [01:03,  3.27it/s]

Epoch 0, Batch 200, position loss: 42124.43359375 reconstruction loss: 115.27992248535156 RMSE(mm): 102.62118883757633


236it [01:14,  3.16it/s]


Epoch 0, Val Loss: 37758.584064094386, RMSE(mm): 97.15784073364124
Epoch 0, test Loss: 40526.005420918365, RMSE(mm): 100.65535929710644


1it [00:00,  3.28it/s]

Epoch 1, Batch 0, position loss: 38875.859375 reconstruction loss: 80.22846221923828 RMSE(mm): 98.58481041088429


101it [00:30,  3.33it/s]

Epoch 1, Batch 100, position loss: 38886.87109375 reconstruction loss: 53.64055252075195 RMSE(mm): 98.59877166292438


201it [01:00,  3.27it/s]

Epoch 1, Batch 200, position loss: 32995.96875 reconstruction loss: 115.26582336425781 RMSE(mm): 90.82396262826238


236it [01:11,  3.31it/s]


Epoch 1, Val Loss: 26272.24577487245, RMSE(mm): 81.04357743657489
Epoch 1, test Loss: 27366.187619579083, RMSE(mm): 82.71364400686727


1it [00:00,  3.38it/s]

Epoch 2, Batch 0, position loss: 24567.79296875 reconstruction loss: 80.2202377319336 RMSE(mm): 78.37058276029023


101it [00:30,  3.28it/s]

Epoch 2, Batch 100, position loss: 25706.51171875 reconstruction loss: 53.63770294189453 RMSE(mm): 80.16625181263935


201it [01:00,  3.28it/s]

Epoch 2, Batch 200, position loss: 25260.12109375 reconstruction loss: 115.2901840209961 RMSE(mm): 79.46716475021303


236it [01:11,  3.30it/s]


Epoch 2, Val Loss: 22200.879663584183, RMSE(mm): 74.49979809298846
Epoch 2, test Loss: 22792.848054846938, RMSE(mm): 75.48650219550336


1it [00:00,  3.23it/s]

Epoch 3, Batch 0, position loss: 21028.62890625 reconstruction loss: 80.2297134399414 RMSE(mm): 72.50625646495963


101it [00:30,  3.26it/s]

Epoch 3, Batch 100, position loss: 23309.330078125 reconstruction loss: 53.64381408691406 RMSE(mm): 76.3369669264587


201it [01:01,  3.30it/s]

Epoch 3, Batch 200, position loss: 24194.177734375 reconstruction loss: 115.28157806396484 RMSE(mm): 77.77238863243015


236it [01:12,  3.27it/s]


Epoch 3, Val Loss: 20238.195452008928, RMSE(mm): 71.13050585369284
Epoch 3, test Loss: 20414.709582270407, RMSE(mm): 71.44002656471791


1it [00:00,  3.25it/s]

Epoch 4, Batch 0, position loss: 19025.021484375 reconstruction loss: 80.23310089111328 RMSE(mm): 68.96561006105688


101it [00:30,  3.27it/s]

Epoch 4, Batch 100, position loss: 18263.75390625 reconstruction loss: 53.63727569580078 RMSE(mm): 67.57172838223468


201it [01:01,  3.26it/s]

Epoch 4, Batch 200, position loss: 20356.255859375 reconstruction loss: 115.26786041259766 RMSE(mm): 71.3376756338735


236it [01:12,  3.27it/s]


Epoch 4, Val Loss: 16422.936124840562, RMSE(mm): 64.07600199146432
Epoch 4, test Loss: 15104.151048309948, RMSE(mm): 61.4494732449147


1it [00:00,  3.29it/s]

Epoch 5, Batch 0, position loss: 14868.5244140625 reconstruction loss: 80.22640228271484 RMSE(mm): 60.96827948626749


101it [00:30,  3.28it/s]

Epoch 5, Batch 100, position loss: 14846.6591796875 reconstruction loss: 53.63240432739258 RMSE(mm): 60.923433873361695


201it [01:01,  3.24it/s]

Epoch 5, Batch 200, position loss: 17807.130859375 reconstruction loss: 115.26830291748047 RMSE(mm): 66.72168099533876


236it [01:12,  3.27it/s]


Epoch 5, Val Loss: 16053.942303093112, RMSE(mm): 63.35207633356051
Epoch 5, test Loss: 14467.717613998724, RMSE(mm): 60.140912892137585


1it [00:00,  3.24it/s]

Epoch 6, Batch 0, position loss: 13511.4482421875 reconstruction loss: 80.21968841552734 RMSE(mm): 58.11937766826891


101it [00:30,  3.28it/s]

Epoch 6, Batch 100, position loss: 13028.5673828125 reconstruction loss: 53.6326789855957 RMSE(mm): 57.07137501149876


201it [01:01,  3.21it/s]

Epoch 6, Batch 200, position loss: 14618.216796875 reconstruction loss: 115.2744369506836 RMSE(mm): 60.452908939262386


236it [01:12,  3.27it/s]


Epoch 6, Val Loss: 15183.041394292091, RMSE(mm): 61.60974231867086
Epoch 6, test Loss: 13557.787607621174, RMSE(mm): 58.21895655115517


1it [00:00,  3.25it/s]

Epoch 7, Batch 0, position loss: 12288.091796875 reconstruction loss: 80.22200012207031 RMSE(mm): 55.42583286896779


101it [00:30,  3.29it/s]

Epoch 7, Batch 100, position loss: 12517.560546875 reconstruction loss: 53.63156509399414 RMSE(mm): 55.94095223285665


201it [01:01,  3.28it/s]

Epoch 7, Batch 200, position loss: 14056.66015625 reconstruction loss: 115.27362823486328 RMSE(mm): 59.280393378101834


236it [01:12,  3.27it/s]


Epoch 7, Val Loss: 15092.36009247449, RMSE(mm): 61.425483499266186
Epoch 7, test Loss: 13429.909956951531, RMSE(mm): 57.943744176898704


1it [00:00,  3.25it/s]

Epoch 8, Batch 0, position loss: 11875.62890625 reconstruction loss: 80.22123718261719 RMSE(mm): 54.48767958504473


101it [00:30,  3.29it/s]

Epoch 8, Batch 100, position loss: 11929.884765625 reconstruction loss: 53.63103485107422 RMSE(mm): 54.61200592732563


201it [01:01,  3.28it/s]

Epoch 8, Batch 200, position loss: 13532.51171875 reconstruction loss: 115.27279663085938 RMSE(mm): 58.164662207284415


236it [01:12,  3.28it/s]


Epoch 8, Val Loss: 15049.324687101403, RMSE(mm): 61.33784453153983
Epoch 8, test Loss: 13347.233777104591, RMSE(mm): 57.765114422773784


1it [00:00,  3.30it/s]

Epoch 9, Batch 0, position loss: 11632.498046875 reconstruction loss: 80.2205581665039 RMSE(mm): 53.92702950950247


101it [00:30,  3.29it/s]

Epoch 9, Batch 100, position loss: 11716.0986328125 reconstruction loss: 53.63035583496094 RMSE(mm): 54.120464319914376


201it [01:01,  3.27it/s]

Epoch 9, Batch 200, position loss: 13172.556640625 reconstruction loss: 115.27188110351562 RMSE(mm): 57.385879449183754


236it [01:12,  3.27it/s]


Epoch 9, Val Loss: 15023.122708067602, RMSE(mm): 61.284424424293164
Epoch 9, test Loss: 13284.693678252552, RMSE(mm): 57.629622760895614


1it [00:00,  3.29it/s]

Epoch 10, Batch 0, position loss: 11294.20703125 reconstruction loss: 80.21994018554688 RMSE(mm): 53.137103400660635


101it [00:30,  3.27it/s]

Epoch 10, Batch 100, position loss: 11666.0810546875 reconstruction loss: 53.62986755371094 RMSE(mm): 54.00481704137025


201it [01:01,  3.29it/s]

Epoch 10, Batch 200, position loss: 13126.06640625 reconstruction loss: 115.27104949951172 RMSE(mm): 57.284523228901016


236it [01:12,  3.27it/s]


Epoch 10, Val Loss: 14996.271534199617, RMSE(mm): 61.22963239763819
Epoch 10, test Loss: 13209.675462372448, RMSE(mm): 57.46667613141648


1it [00:00,  3.23it/s]

Epoch 11, Batch 0, position loss: 11160.287109375 reconstruction loss: 80.21931457519531 RMSE(mm): 52.82113002713734


101it [00:30,  3.26it/s]

Epoch 11, Batch 100, position loss: 11208.419921875 reconstruction loss: 53.629234313964844 RMSE(mm): 52.934912680278885


201it [01:01,  3.26it/s]

Epoch 11, Batch 200, position loss: 12731.18359375 reconstruction loss: 115.27011108398438 RMSE(mm): 56.41627334765653


236it [01:12,  3.27it/s]


Epoch 11, Val Loss: 14962.033073580995, RMSE(mm): 61.159694802992995
Epoch 11, test Loss: 13126.07766661352, RMSE(mm): 57.28454780002527


1it [00:00,  3.26it/s]

Epoch 12, Batch 0, position loss: 10712.361328125 reconstruction loss: 80.21907043457031 RMSE(mm): 51.75026890781583


101it [00:31,  3.29it/s]

Epoch 12, Batch 100, position loss: 10916.615234375 reconstruction loss: 53.62723159790039 RMSE(mm): 52.2413036647608


201it [01:01,  3.29it/s]

Epoch 12, Batch 200, position loss: 11919.53515625 reconstruction loss: 115.26899719238281 RMSE(mm): 54.58831183561642


236it [01:12,  3.26it/s]


Epoch 12, Val Loss: 14748.645208864797, RMSE(mm): 60.7220001499967
Epoch 12, test Loss: 12777.799954161352, RMSE(mm): 56.51946557196324


1it [00:00,  3.25it/s]

Epoch 13, Batch 0, position loss: 10980.8046875 reconstruction loss: 80.22122192382812 RMSE(mm): 52.39466739922108


101it [00:30,  3.28it/s]

Epoch 13, Batch 100, position loss: 10903.216796875 reconstruction loss: 53.62740707397461 RMSE(mm): 52.209234807826384


201it [01:01,  3.26it/s]

Epoch 13, Batch 200, position loss: 11969.4921875 reconstruction loss: 115.26880645751953 RMSE(mm): 54.702587204582926


236it [01:11,  3.28it/s]


Epoch 13, Val Loss: 14727.47877471301, RMSE(mm): 60.678412089294596
Epoch 13, test Loss: 12753.200304926659, RMSE(mm): 56.465034102811494


1it [00:00,  3.27it/s]

Epoch 14, Batch 0, position loss: 10832.546875 reconstruction loss: 80.22108459472656 RMSE(mm): 52.039760940553904


101it [00:30,  3.26it/s]

Epoch 14, Batch 100, position loss: 10732.6875 reconstruction loss: 53.627323150634766 RMSE(mm): 51.79934241860605


201it [01:01,  3.27it/s]

Epoch 14, Batch 200, position loss: 11797.990234375 reconstruction loss: 115.2686767578125 RMSE(mm): 54.309276910982256


236it [01:12,  3.27it/s]


Epoch 14, Val Loss: 14731.835857780612, RMSE(mm): 60.687387194087975
Epoch 14, test Loss: 12750.258669483419, RMSE(mm): 56.45852165413876


In [1]:
from models.MTLVit import MTLViT_pretrained
from helper_function_test import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
model_name = 'MTL_Recon_VIT_pre'
for i in range(50, 201, 10):
    model = MTLViT_pretrained()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
    file_name = f'{model_name}_weight_{i}'
    train(model,EEGEyeNet, optimizer, scheduler,log_name=file_name, batch_size = batch_size ,n_epoch = n_epoch, reconstruction_weight=i)

loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]


Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


TypeError: train() got multiple values for argument 'log_name'