In [1]:
from models.MTLVit2 import MTLViT_pretrained
from helper_function_test import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
model_name = 'MTL_Recon_VIT_pre'
i=0
model = MTLViT_pretrained()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
file_name = f'{model_name}_weight_test_{i}'
train(model,EEGEyeNet, optimizer, scheduler,log_name=file_name, batch_size = batch_size ,n_epoch = n_epoch, reconstruction_weight=i)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]


Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


1it [00:08,  8.41s/it]

Epoch 0, Batch 0, position loss: 168857.25 reconstruction loss: 80.1269760131836 RMSE(mm): 205.4612189684467


101it [03:43,  1.74it/s]

Epoch 0, Batch 100, position loss: 66169.8125 reconstruction loss: 53.60430908203125 RMSE(mm): 128.61746819542049


201it [04:42,  1.78it/s]

Epoch 0, Batch 200, position loss: 35726.03125 reconstruction loss: 115.2521743774414 RMSE(mm): 94.5066548582691


236it [05:01,  1.28s/it]


Epoch 0, Val Loss: 28261.314453125, RMSE(mm): 84.05550911916036
Epoch 0, test Loss: 29605.651985012755, RMSE(mm): 86.03146515231035


1it [00:01,  1.59s/it]

Epoch 1, Batch 0, position loss: 26748.654296875 reconstruction loss: 80.19401550292969 RMSE(mm): 81.77507917586354


101it [04:47,  2.78s/it]

Epoch 1, Batch 100, position loss: 25733.15234375 reconstruction loss: 53.614227294921875 RMSE(mm): 80.2077807069707


201it [05:56,  1.62it/s]

Epoch 1, Batch 200, position loss: 32550.66796875 reconstruction loss: 115.2536392211914 RMSE(mm): 90.2090183528648


236it [06:17,  1.60s/it]


Epoch 1, Val Loss: 23892.25681600765, RMSE(mm): 77.28560153095732
Epoch 1, test Loss: 23598.64114317602, RMSE(mm): 76.80924609572733


1it [00:00,  1.62it/s]

Epoch 2, Batch 0, position loss: 21620.55859375 reconstruction loss: 80.17729949951172 RMSE(mm): 73.51965484438499


101it [01:03,  1.67it/s]

Epoch 2, Batch 100, position loss: 22634.2890625 reconstruction loss: 53.603858947753906 RMSE(mm): 75.22348214238025


201it [02:04,  1.63it/s]

Epoch 2, Batch 200, position loss: 23033.65625 reconstruction loss: 115.24030303955078 RMSE(mm): 75.88421484406358


236it [02:26,  1.61it/s]


Epoch 2, Val Loss: 19497.23676658163, RMSE(mm): 69.81625306220184
Epoch 2, test Loss: 18378.467474489797, RMSE(mm): 67.78360324313284


1it [00:00,  1.56it/s]

Epoch 3, Batch 0, position loss: 17555.6953125 reconstruction loss: 80.16666412353516 RMSE(mm): 66.24895341154455


101it [01:07,  1.46it/s]

Epoch 3, Batch 100, position loss: 16748.28125 reconstruction loss: 53.59172439575195 RMSE(mm): 64.70757538727595


201it [02:15,  1.52it/s]

Epoch 3, Batch 200, position loss: 19412.1796875 reconstruction loss: 115.22434997558594 RMSE(mm): 69.6637992207933


236it [02:38,  1.49it/s]


Epoch 3, Val Loss: 16509.541115274234, RMSE(mm): 64.24472958008741
Epoch 3, test Loss: 14658.457669005102, RMSE(mm): 60.536058818288424


1it [00:00,  1.35it/s]

Epoch 4, Batch 0, position loss: 13797.701171875 reconstruction loss: 80.16239166259766 RMSE(mm): 58.73180818746133


101it [01:08,  1.50it/s]

Epoch 4, Batch 100, position loss: 13696.7646484375 reconstruction loss: 53.61094665527344 RMSE(mm): 58.51658877710982


201it [02:17,  1.45it/s]

Epoch 4, Batch 200, position loss: 18068.61328125 reconstruction loss: 115.22573852539062 RMSE(mm): 67.20977101815257


236it [02:40,  1.47it/s]


Epoch 4, Val Loss: 15795.116968271685, RMSE(mm): 62.83931287074932
Epoch 4, test Loss: 13434.399334343112, RMSE(mm): 57.95342814351691


1it [00:00,  1.38it/s]

Epoch 5, Batch 0, position loss: 11832.173828125 reconstruction loss: 80.17711639404297 RMSE(mm): 54.387898075134785


101it [01:08,  1.61it/s]

Epoch 5, Batch 100, position loss: 11945.9443359375 reconstruction loss: 53.59894561767578 RMSE(mm): 54.648751897773245


201it [02:10,  1.50it/s]

Epoch 5, Batch 200, position loss: 17694.75390625 reconstruction loss: 115.23932647705078 RMSE(mm): 66.5108147338649


236it [02:33,  1.53it/s]


Epoch 5, Val Loss: 16292.194614955357, RMSE(mm): 63.82044072034319
Epoch 5, test Loss: 13953.078882334185, RMSE(mm): 59.06157566966484


1it [00:00,  1.54it/s]

Epoch 6, Batch 0, position loss: 11513.2734375 reconstruction loss: 80.17855834960938 RMSE(mm): 53.649961410750336


101it [01:02,  1.65it/s]

Epoch 6, Batch 100, position loss: 12204.4912109375 reconstruction loss: 53.606693267822266 RMSE(mm): 55.23696952887961


201it [02:05,  1.62it/s]

Epoch 6, Batch 200, position loss: 12517.689453125 reconstruction loss: 115.23387908935547 RMSE(mm): 55.94124027299761


236it [02:25,  1.62it/s]


Epoch 6, Val Loss: 15134.197544642857, RMSE(mm): 61.51056320796221
Epoch 6, test Loss: 13192.44700653699, RMSE(mm): 57.42918902121331


1it [00:00,  1.37it/s]

Epoch 7, Batch 0, position loss: 11171.283203125 reconstruction loss: 80.17736053466797 RMSE(mm): 52.84714562567452


101it [01:04,  1.53it/s]

Epoch 7, Batch 100, position loss: 11992.763671875 reconstruction loss: 53.607425689697266 RMSE(mm): 54.75573867613102


201it [02:06,  1.59it/s]

Epoch 7, Batch 200, position loss: 11798.2421875 reconstruction loss: 115.23287200927734 RMSE(mm): 54.309856811402106


236it [02:29,  1.58it/s]


Epoch 7, Val Loss: 15132.288374920281, RMSE(mm): 61.5066833257173
Epoch 7, test Loss: 13099.139947385203, RMSE(mm): 57.22573710181723


1it [00:00,  1.30it/s]

Epoch 8, Batch 0, position loss: 10723.0263671875 reconstruction loss: 80.1772232055664 RMSE(mm): 51.77602332930635


101it [01:02,  1.64it/s]

Epoch 8, Batch 100, position loss: 11207.841796875 reconstruction loss: 53.606834411621094 RMSE(mm): 52.93354748379094


201it [02:04,  1.64it/s]

Epoch 8, Batch 200, position loss: 11272.3720703125 reconstruction loss: 115.23328399658203 RMSE(mm): 53.085713874620964


236it [02:27,  1.60it/s]


Epoch 8, Val Loss: 15143.862553810586, RMSE(mm): 61.53020102724065
Epoch 8, test Loss: 13053.68798828125, RMSE(mm): 57.12636866693272


1it [00:00,  1.37it/s]

Epoch 9, Batch 0, position loss: 9924.7568359375 reconstruction loss: 80.17740631103516 RMSE(mm): 49.81153690646751


101it [01:00,  1.82it/s]

Epoch 9, Batch 100, position loss: 10819.451171875 reconstruction loss: 53.607154846191406 RMSE(mm): 52.008295424564245


201it [08:46, 57.02s/it]

Epoch 9, Batch 200, position loss: 10828.3193359375 reconstruction loss: 115.23230743408203 RMSE(mm): 52.02960536064419


236it [10:36,  2.70s/it]


Epoch 9, Val Loss: 15175.375368702169, RMSE(mm): 61.594186756345294
Epoch 9, test Loss: 13053.642139668367, RMSE(mm): 57.12626834405597


1it [00:25, 25.45s/it]

Epoch 10, Batch 0, position loss: 9112.9482421875 reconstruction loss: 80.17662048339844 RMSE(mm): 47.73088162339844


3it [03:03, 61.28s/it]


KeyboardInterrupt: 

In [ ]:
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
model_name = 'MTL_Recon_VIT_pre'
i=90
model = MTLViT_pretrained()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
file_name = f'{model_name}_weight_test_{i}'
train(model,EEGEyeNet, optimizer, scheduler,log_name=file_name, batch_size = batch_size ,n_epoch = n_epoch, reconstruction_weight=i)

In [ ]:
from models.MTLVit import MTLViT_pretrained
from helper_function_test import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch
model = MTLViT_pretrained()

In [4]:
from models.MTLVit import MTLViT_pretrained
from helper_function_test import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
model_name = 'MTL_Recon_VIT_pre'
for i in [0,90]:
    model = MTLViT_pretrained()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
    file_name = f'{model_name}_weight_{i}'
    train(model,EEGEyeNet, optimizer, scheduler,log_name=file_name, batch_size = batch_size ,n_epoch = n_epoch, reconstruction_weight=i)

loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]


Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


1it [00:00,  1.88it/s]

Epoch 0, Batch 0, position loss: 168967.28125 reconstruction loss: 80.14228057861328 RMSE(mm): 205.52814968393017


101it [00:30,  3.34it/s]

Epoch 0, Batch 100, position loss: 66875.6875 reconstruction loss: 53.62712860107422 RMSE(mm): 129.30167003948557


201it [01:00,  3.36it/s]

Epoch 0, Batch 200, position loss: 34536.9296875 reconstruction loss: 115.26946258544922 RMSE(mm): 92.92057049908271


236it [01:10,  3.34it/s]


Epoch 0, Val Loss: 28618.087252869896, RMSE(mm): 84.58440644242575
Epoch 0, test Loss: 30378.91087372449, RMSE(mm): 87.14773501606982


1it [00:00,  3.37it/s]

Epoch 1, Batch 0, position loss: 26788.484375 reconstruction loss: 80.1847915649414 RMSE(mm): 81.83594011038181


101it [00:30,  3.35it/s]

Epoch 1, Batch 100, position loss: 26107.72265625 reconstruction loss: 53.62800216674805 RMSE(mm): 80.78942173368058


201it [00:59,  3.36it/s]

Epoch 1, Batch 200, position loss: 31078.794921875 reconstruction loss: 115.2453842163086 RMSE(mm): 88.14589457523674


236it [01:10,  3.37it/s]


Epoch 1, Val Loss: 23510.533083545917, RMSE(mm): 76.66572422462647
Epoch 1, test Loss: 23777.613121811224, RMSE(mm): 77.09995642315764


1it [00:00,  3.35it/s]

Epoch 2, Batch 0, position loss: 21304.3203125 reconstruction loss: 80.21294403076172 RMSE(mm): 72.9799977947725


101it [00:30,  3.38it/s]

Epoch 2, Batch 100, position loss: 24054.90625 reconstruction loss: 53.643287658691406 RMSE(mm): 77.54822088545939


201it [00:59,  3.36it/s]

Epoch 2, Batch 200, position loss: 23917.83984375 reconstruction loss: 115.2670669555664 RMSE(mm): 77.32696787626875


236it [01:10,  3.36it/s]


Epoch 2, Val Loss: 20560.699816645407, RMSE(mm): 71.69501345394498
Epoch 2, test Loss: 20351.86326132015, RMSE(mm): 71.3299783774679


1it [00:00,  3.30it/s]

Epoch 3, Batch 0, position loss: 18408.646484375 reconstruction loss: 80.21436309814453 RMSE(mm): 67.83923364170434


101it [00:30,  3.34it/s]

Epoch 3, Batch 100, position loss: 18164.41015625 reconstruction loss: 53.630157470703125 RMSE(mm): 67.38770317396565


201it [01:00,  3.36it/s]

Epoch 3, Batch 200, position loss: 21127.1953125 reconstruction loss: 115.24337768554688 RMSE(mm): 72.67598522294004


236it [01:10,  3.34it/s]


Epoch 3, Val Loss: 16320.353156887755, RMSE(mm): 63.875568797639204
Epoch 3, test Loss: 15291.50924744898, RMSE(mm): 61.829421086261554


1it [00:00,  3.36it/s]

Epoch 4, Batch 0, position loss: 14888.2109375 reconstruction loss: 80.1931381225586 RMSE(mm): 61.008628360052484


101it [00:30,  3.36it/s]

Epoch 4, Batch 100, position loss: 13619.3974609375 reconstruction loss: 53.61178970336914 RMSE(mm): 58.35108709556639


201it [01:00,  3.36it/s]

Epoch 4, Batch 200, position loss: 19545.53515625 reconstruction loss: 115.22675323486328 RMSE(mm): 69.9026736903711


236it [01:10,  3.35it/s]


Epoch 4, Val Loss: 15541.163683832909, RMSE(mm): 62.3321018493539
Epoch 4, test Loss: 13950.331652582909, RMSE(mm): 59.05576104958539


1it [00:00,  3.35it/s]

Epoch 5, Batch 0, position loss: 13575.6015625 reconstruction loss: 80.18529510498047 RMSE(mm): 58.2571917502466


101it [00:30,  3.38it/s]

Epoch 5, Batch 100, position loss: 13367.0234375 reconstruction loss: 53.60824966430664 RMSE(mm): 57.80792211604738


201it [00:59,  3.35it/s]

Epoch 5, Batch 200, position loss: 17495.0546875 reconstruction loss: 115.22806549072266 RMSE(mm): 66.13443635410376


236it [01:10,  3.36it/s]


Epoch 5, Val Loss: 15262.661332110969, RMSE(mm): 61.77107197570512
Epoch 5, test Loss: 13641.19921875, RMSE(mm): 58.39777225791666


1it [00:00,  3.34it/s]

Epoch 6, Batch 0, position loss: 11431.98828125 reconstruction loss: 80.18358612060547 RMSE(mm): 53.46023821788021


101it [00:30,  3.37it/s]

Epoch 6, Batch 100, position loss: 12247.986328125 reconstruction loss: 53.611820220947266 RMSE(mm): 55.33531044488004


201it [00:59,  3.35it/s]

Epoch 6, Batch 200, position loss: 13511.703125 reconstruction loss: 115.2406997680664 RMSE(mm): 58.119925853789596


236it [01:10,  3.36it/s]


Epoch 6, Val Loss: 14760.130420918367, RMSE(mm): 60.74563856960919
Epoch 6, test Loss: 12985.784817442602, RMSE(mm): 56.97759388005649


1it [00:00,  3.36it/s]

Epoch 7, Batch 0, position loss: 10398.3486328125 reconstruction loss: 80.18341064453125 RMSE(mm): 50.986146728333225


101it [00:30,  3.35it/s]

Epoch 7, Batch 100, position loss: 11221.3974609375 reconstruction loss: 53.61124038696289 RMSE(mm): 52.965548852384934


201it [00:59,  3.36it/s]

Epoch 7, Batch 200, position loss: 13192.75 reconstruction loss: 115.240234375 RMSE(mm): 57.42984851103127


236it [01:10,  3.36it/s]


Epoch 7, Val Loss: 14773.033442283164, RMSE(mm): 60.77218410235715
Epoch 7, test Loss: 12902.434231505102, RMSE(mm): 56.794441258597445


1it [00:00,  3.36it/s]

Epoch 8, Batch 0, position loss: 9760.263671875 reconstruction loss: 80.18223571777344 RMSE(mm): 49.39702337154284


101it [00:30,  3.35it/s]

Epoch 8, Batch 100, position loss: 10494.31640625 reconstruction loss: 53.610450744628906 RMSE(mm): 51.220885403929714


201it [00:59,  3.36it/s]

Epoch 8, Batch 200, position loss: 12480.73828125 reconstruction loss: 115.2407455444336 RMSE(mm): 55.858612319968174


236it [01:10,  3.36it/s]


Epoch 8, Val Loss: 14858.156469228315, RMSE(mm): 60.947018937000344
Epoch 8, test Loss: 12911.597556600766, RMSE(mm): 56.81460542105517


1it [00:00,  3.31it/s]

Epoch 9, Batch 0, position loss: 9680.705078125 reconstruction loss: 80.18260192871094 RMSE(mm): 49.19528706625514


101it [00:30,  3.35it/s]

Epoch 9, Batch 100, position loss: 9971.384765625 reconstruction loss: 53.6113395690918 RMSE(mm): 49.928410663731825


201it [00:59,  3.35it/s]

Epoch 9, Batch 200, position loss: 11787.125 reconstruction loss: 115.24041748046875 RMSE(mm): 54.28426337346764


236it [01:10,  3.36it/s]


Epoch 9, Val Loss: 14901.492287149234, RMSE(mm): 61.035834325315065
Epoch 9, test Loss: 12893.899912308674, RMSE(mm): 56.77565480095468


1it [00:00,  3.39it/s]

Epoch 10, Batch 0, position loss: 9238.7216796875 reconstruction loss: 80.18265533447266 RMSE(mm): 48.05913461478343


101it [00:30,  3.36it/s]

Epoch 10, Batch 100, position loss: 9276.21875 reconstruction loss: 53.61261749267578 RMSE(mm): 48.15656432408774


201it [00:59,  3.35it/s]

Epoch 10, Batch 200, position loss: 10943.998046875 reconstruction loss: 115.2414779663086 RMSE(mm): 52.30678265501282


236it [01:10,  3.36it/s]


Epoch 10, Val Loss: 15003.671137595664, RMSE(mm): 61.24473678936759
Epoch 10, test Loss: 12937.532156808036, RMSE(mm): 56.87163650891373


1it [00:00,  3.33it/s]

Epoch 11, Batch 0, position loss: 9083.7265625 reconstruction loss: 80.18450927734375 RMSE(mm): 47.65429299260456


101it [00:30,  3.36it/s]

Epoch 11, Batch 100, position loss: 8496.0869140625 reconstruction loss: 53.6124382019043 RMSE(mm): 46.0871102209243


201it [00:59,  3.37it/s]

Epoch 11, Batch 200, position loss: 10487.609375 reconstruction loss: 115.24040985107422 RMSE(mm): 51.20451487662001


236it [01:10,  3.36it/s]


Epoch 11, Val Loss: 15269.799525669643, RMSE(mm): 61.785515142445895
Epoch 11, test Loss: 13263.414680325255, RMSE(mm): 57.58344961949843


1it [00:00,  3.36it/s]

Epoch 12, Batch 0, position loss: 9108.921875 reconstruction loss: 80.18470764160156 RMSE(mm): 47.72033600835183


101it [00:30,  3.36it/s]

Epoch 12, Batch 100, position loss: 9587.55078125 reconstruction loss: 53.61418914794922 RMSE(mm): 48.95801972417287


201it [01:00,  3.31it/s]

Epoch 12, Batch 200, position loss: 9880.609375 reconstruction loss: 115.24188232421875 RMSE(mm): 49.70062719674672


236it [01:10,  3.35it/s]


Epoch 12, Val Loss: 14704.719168526786, RMSE(mm): 60.63150824556236
Epoch 12, test Loss: 12402.823670679209, RMSE(mm): 55.68398259526524


1it [00:00,  3.35it/s]

Epoch 13, Batch 0, position loss: 8401.046875 reconstruction loss: 80.18545532226562 RMSE(mm): 45.82861244626549


101it [00:30,  3.36it/s]

Epoch 13, Batch 100, position loss: 9093.283203125 reconstruction loss: 53.614097595214844 RMSE(mm): 47.67935403066247


201it [01:00,  3.36it/s]

Epoch 13, Batch 200, position loss: 9883.95703125 reconstruction loss: 115.2415771484375 RMSE(mm): 49.70904603603352


236it [01:10,  3.35it/s]


Epoch 13, Val Loss: 14681.813496492347, RMSE(mm): 60.584266721015005
Epoch 13, test Loss: 12347.906230070153, RMSE(mm): 55.56056656944328


1it [00:00,  3.38it/s]

Epoch 14, Batch 0, position loss: 8441.669921875 reconstruction loss: 80.18556213378906 RMSE(mm): 45.939280365159725


101it [00:30,  3.35it/s]

Epoch 14, Batch 100, position loss: 8785.1484375 reconstruction loss: 53.614200592041016 RMSE(mm): 46.86456133769951


201it [00:59,  3.35it/s]

Epoch 14, Batch 200, position loss: 9818.9873046875 reconstruction loss: 115.24142456054688 RMSE(mm): 49.54540166525926


236it [01:10,  3.36it/s]


Epoch 14, Val Loss: 14681.444674744898, RMSE(mm): 60.58350574773817
Epoch 14, test Loss: 12341.700992506378, RMSE(mm): 55.5466042897907


Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


1it [00:00,  2.43it/s]

Epoch 0, Batch 0, position loss: 169123.578125 reconstruction loss: 80.13531494140625 RMSE(mm): 205.62318578227018


101it [00:30,  3.36it/s]

Epoch 0, Batch 100, position loss: 65780.0 reconstruction loss: 53.60019302368164 RMSE(mm): 128.2380598730346


201it [01:00,  3.36it/s]

Epoch 0, Batch 200, position loss: 33335.03515625 reconstruction loss: 115.25703430175781 RMSE(mm): 91.28942320478589


236it [01:10,  3.35it/s]


Epoch 0, Val Loss: 41268.57605229592, RMSE(mm): 85.79988053233085
Epoch 0, test Loss: 53376.486607142855, RMSE(mm): 87.45998851725363


1it [00:00,  3.33it/s]

Epoch 1, Batch 0, position loss: 26400.0859375 reconstruction loss: 80.18507385253906 RMSE(mm): 81.24051627343957


101it [00:30,  3.36it/s]

Epoch 1, Batch 100, position loss: 26630.103515625 reconstruction loss: 52.93452072143555 RMSE(mm): 81.5936632276444


201it [00:59,  3.36it/s]

Epoch 1, Batch 200, position loss: 30396.205078125 reconstruction loss: 114.81181335449219 RMSE(mm): 87.17253735856981


236it [01:10,  3.36it/s]


Epoch 1, Val Loss: 35740.86419802296, RMSE(mm): 77.45452616371863
Epoch 1, test Loss: 47071.25530133928, RMSE(mm): 78.0583651413654


1it [00:00,  3.33it/s]

Epoch 2, Batch 0, position loss: 22532.3515625 reconstruction loss: 79.13522338867188 RMSE(mm): 75.05389990283649


101it [00:30,  3.36it/s]

Epoch 2, Batch 100, position loss: 23325.080078125 reconstruction loss: 52.54619598388672 RMSE(mm): 76.36275282839959


201it [01:00,  3.35it/s]

Epoch 2, Batch 200, position loss: 25480.828125 reconstruction loss: 114.24993896484375 RMSE(mm): 79.8135767351019


236it [01:10,  3.35it/s]


Epoch 2, Val Loss: 33244.23297991072, RMSE(mm): 73.40484911098868
Epoch 2, test Loss: 44335.6790497449, RMSE(mm): 73.63923645210292


1it [00:00,  3.34it/s]

Epoch 3, Batch 0, position loss: 20651.876953125 reconstruction loss: 78.25579071044922 RMSE(mm): 71.85380461938846


101it [00:30,  3.35it/s]

Epoch 3, Batch 100, position loss: 20304.759765625 reconstruction loss: 52.308956146240234 RMSE(mm): 71.24738550575908


201it [00:59,  3.36it/s]

Epoch 3, Batch 200, position loss: 23692.6953125 reconstruction loss: 113.83158111572266 RMSE(mm): 76.96215841649064


236it [01:10,  3.36it/s]


Epoch 3, Val Loss: 30642.57194674745, RMSE(mm): 68.9131508949542
Epoch 3, test Loss: 40517.22672193877, RMSE(mm): 66.92545395674688


1it [00:00,  3.34it/s]

Epoch 4, Batch 0, position loss: 17181.38671875 reconstruction loss: 77.78571319580078 RMSE(mm): 65.53889440391484


101it [00:30,  3.36it/s]

Epoch 4, Batch 100, position loss: 15943.84765625 reconstruction loss: 51.46481704711914 RMSE(mm): 63.13447484585977


201it [00:59,  3.36it/s]

Epoch 4, Batch 200, position loss: 22499.326171875 reconstruction loss: 113.39501953125 RMSE(mm): 74.99887694471664


236it [01:10,  3.36it/s]


Epoch 4, Val Loss: 28050.330715880104, RMSE(mm): 64.32067265478271
Epoch 4, test Loss: 36940.39680325255, RMSE(mm): 60.16230083205138


1it [00:00,  3.34it/s]

Epoch 5, Batch 0, position loss: 13400.505859375 reconstruction loss: 75.56697845458984 RMSE(mm): 57.88027699349537


101it [00:30,  3.37it/s]

Epoch 5, Batch 100, position loss: 14994.2421875 reconstruction loss: 48.40497970581055 RMSE(mm): 61.225489355945534


201it [00:59,  3.35it/s]

Epoch 5, Batch 200, position loss: 18446.265625 reconstruction loss: 109.4415512084961 RMSE(mm): 67.90851497603228


236it [01:10,  3.36it/s]


Epoch 5, Val Loss: 26703.909797512755, RMSE(mm): 62.625118465125844
Epoch 5, test Loss: 35697.52913743623, RMSE(mm): 58.50715735816679


1it [00:00,  3.35it/s]

Epoch 6, Batch 0, position loss: 11879.8427734375 reconstruction loss: 69.22386169433594 RMSE(mm): 54.49734574600285


101it [00:30,  3.35it/s]

Epoch 6, Batch 100, position loss: 14791.39453125 reconstruction loss: 43.75233840942383 RMSE(mm): 60.809938602275366


201it [00:59,  3.35it/s]

Epoch 6, Batch 200, position loss: 13929.07421875 reconstruction loss: 104.79861450195312 RMSE(mm): 59.01074948420415


236it [01:10,  3.36it/s]


Epoch 6, Val Loss: 26324.780373086734, RMSE(mm): 62.13619816122325
Epoch 6, test Loss: 35295.64375398597, RMSE(mm): 57.96188844058802


1it [00:00,  3.34it/s]

Epoch 7, Batch 0, position loss: 11128.8154296875 reconstruction loss: 67.56571197509766 RMSE(mm): 52.746600434737736


101it [00:30,  3.36it/s]

Epoch 7, Batch 100, position loss: 14583.76171875 reconstruction loss: 42.71520233154297 RMSE(mm): 60.38162327800984


201it [00:59,  3.36it/s]

Epoch 7, Batch 200, position loss: 13041.8828125 reconstruction loss: 103.76907348632812 RMSE(mm): 57.10053154853289


236it [01:10,  3.36it/s]


Epoch 7, Val Loss: 26140.653140943876, RMSE(mm): 61.97660855493739
Epoch 7, test Loss: 35091.3476961097, RMSE(mm): 57.73369391840959


1it [00:00,  3.31it/s]

Epoch 8, Batch 0, position loss: 10793.4990234375 reconstruction loss: 66.26739501953125 RMSE(mm): 51.9458829538913


101it [00:30,  3.36it/s]

Epoch 8, Batch 100, position loss: 13961.640625 reconstruction loss: 41.60625457763672 RMSE(mm): 59.07969326469121


201it [00:59,  3.36it/s]

Epoch 8, Batch 200, position loss: 12587.001953125 reconstruction loss: 102.67011260986328 RMSE(mm): 56.09590438063415


236it [01:10,  3.36it/s]


Epoch 8, Val Loss: 25995.959283322703, RMSE(mm): 61.89673183577576
Epoch 8, test Loss: 34933.533940529334, RMSE(mm): 57.6048648293608


1it [00:00,  3.35it/s]

Epoch 9, Batch 0, position loss: 10465.607421875 reconstruction loss: 64.96466827392578 RMSE(mm): 51.15077570740008


101it [00:30,  3.34it/s]

Epoch 9, Batch 100, position loss: 13706.2119140625 reconstruction loss: 40.46763610839844 RMSE(mm): 58.5367660408023


201it [01:00,  3.35it/s]

Epoch 9, Batch 200, position loss: 12118.6611328125 reconstruction loss: 101.52851867675781 RMSE(mm): 55.0423953258134


236it [01:10,  3.34it/s]


Epoch 9, Val Loss: 25854.751136001276, RMSE(mm): 61.8202919379758
Epoch 9, test Loss: 34737.336933992345, RMSE(mm): 57.3878974165284


1it [00:00,  3.30it/s]

Epoch 10, Batch 0, position loss: 10480.830078125 reconstruction loss: 63.756591796875 RMSE(mm): 51.187962642903166


101it [00:30,  3.36it/s]

Epoch 10, Batch 100, position loss: 13663.2255859375 reconstruction loss: 39.27959060668945 RMSE(mm): 58.44490051736229


201it [01:00,  3.35it/s]

Epoch 10, Batch 200, position loss: 11397.544921875 reconstruction loss: 100.35432434082031 RMSE(mm): 53.37964247228292


236it [01:10,  3.35it/s]


Epoch 10, Val Loss: 25757.952726403062, RMSE(mm): 61.83266559479993
Epoch 10, test Loss: 34620.04157366072, RMSE(mm): 57.340000198881384


1it [00:00,  3.32it/s]

Epoch 11, Batch 0, position loss: 10185.9853515625 reconstruction loss: 62.4779167175293 RMSE(mm): 50.46282134295134


101it [00:30,  3.36it/s]

Epoch 11, Batch 100, position loss: 13394.0625 reconstruction loss: 38.18421936035156 RMSE(mm): 57.86636004623066


201it [00:59,  3.36it/s]

Epoch 11, Batch 200, position loss: 10694.142578125 reconstruction loss: 99.22235870361328 RMSE(mm): 51.706243767375426


236it [01:10,  3.36it/s]


Epoch 11, Val Loss: 25688.04426419005, RMSE(mm): 61.891677866593824
Epoch 11, test Loss: 34505.59948979592, RMSE(mm): 57.29321800910616


1it [00:00,  3.31it/s]

Epoch 12, Batch 0, position loss: 9754.1650390625 reconstruction loss: 61.29492950439453 RMSE(mm): 49.38158826694039


101it [00:30,  3.34it/s]

Epoch 12, Batch 100, position loss: 13255.8701171875 reconstruction loss: 37.57217025756836 RMSE(mm): 57.56706983421056


201it [01:00,  3.36it/s]

Epoch 12, Batch 200, position loss: 9858.689453125 reconstruction loss: 98.82605743408203 RMSE(mm): 49.64546669416303


236it [01:10,  3.35it/s]


Epoch 12, Val Loss: 25585.96342873087, RMSE(mm): 61.725873394137835
Epoch 12, test Loss: 34246.16226881377, RMSE(mm): 56.76980301550152


1it [00:00,  3.35it/s]

Epoch 13, Batch 0, position loss: 10304.0 reconstruction loss: 61.151973724365234 RMSE(mm): 50.75431016179808


101it [00:30,  3.36it/s]

Epoch 13, Batch 100, position loss: 13295.388671875 reconstruction loss: 37.450538635253906 RMSE(mm): 57.65281578525675


201it [01:00,  3.34it/s]

Epoch 13, Batch 200, position loss: 10038.501953125 reconstruction loss: 98.67308807373047 RMSE(mm): 50.09616241072015


236it [01:10,  3.35it/s]


Epoch 13, Val Loss: 25565.629085618624, RMSE(mm): 61.71515549950018
Epoch 13, test Loss: 34202.311244419645, RMSE(mm): 56.704186538615104


1it [00:00,  3.34it/s]

Epoch 14, Batch 0, position loss: 10146.671875 reconstruction loss: 60.98173522949219 RMSE(mm): 50.36534491840595


101it [00:30,  3.35it/s]

Epoch 14, Batch 100, position loss: 13406.9423828125 reconstruction loss: 37.323089599609375 RMSE(mm): 57.894175835770604


201it [01:00,  3.34it/s]

Epoch 14, Batch 200, position loss: 9884.099609375 reconstruction loss: 98.52637481689453 RMSE(mm): 49.709404566377074


236it [01:10,  3.35it/s]


Epoch 14, Val Loss: 25565.817621970662, RMSE(mm): 61.743243573633094
Epoch 14, test Loss: 34187.265644929845, RMSE(mm): 56.69942936202509


In [4]:
for i in range(70, 100, 10):
    model = MTLViT_pretrained()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
    file_name = f'{model_name}_weight_{i}'
    train(model,EEGEyeNet, optimizer, scheduler,log_name=file_name, batch_size = batch_size ,n_epoch = n_epoch, reconstruction_weight=i)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


1it [00:00,  2.59it/s]

Epoch 0, Batch 0, position loss: 169237.421875 reconstruction loss: 80.13710021972656 RMSE(mm): 205.69238067743296


101it [00:27,  3.70it/s]

Epoch 0, Batch 100, position loss: 105031.9296875 reconstruction loss: 52.864830017089844 RMSE(mm): 162.0431498764295


201it [00:54,  3.69it/s]

Epoch 0, Batch 200, position loss: 44886.3671875 reconstruction loss: 109.80570983886719 RMSE(mm): 105.93201497599769


236it [01:03,  3.70it/s]


Epoch 0, Val Loss: 46273.61949936225, RMSE(mm): 97.8422580572152
Epoch 0, test Loss: 57830.33314732143, RMSE(mm): 101.50642633769925


1it [00:00,  3.70it/s]

Epoch 1, Batch 0, position loss: 39375.26953125 reconstruction loss: 62.87421417236328 RMSE(mm): 99.21601374179724


101it [00:27,  3.70it/s]

Epoch 1, Batch 100, position loss: 32340.1953125 reconstruction loss: 39.735599517822266 RMSE(mm): 89.91689956912994


201it [00:54,  3.69it/s]

Epoch 1, Batch 200, position loss: 29390.89453125 reconstruction loss: 94.0777359008789 RMSE(mm): 85.7188639262823


236it [01:03,  3.70it/s]


Epoch 1, Val Loss: 33144.256297831635, RMSE(mm): 80.06402149944695
Epoch 1, test Loss: 42600.77861926021, RMSE(mm): 81.32285759104238


1it [00:00,  3.70it/s]

Epoch 2, Batch 0, position loss: 23271.337890625 reconstruction loss: 56.00068283081055 RMSE(mm): 76.27473023653542


101it [00:27,  3.70it/s]

Epoch 2, Batch 100, position loss: 26372.880859375 reconstruction loss: 30.11887550354004 RMSE(mm): 81.19864663184818


201it [00:54,  3.70it/s]

Epoch 2, Batch 200, position loss: 26629.55859375 reconstruction loss: 88.64044952392578 RMSE(mm): 81.59282841302598


236it [01:03,  3.71it/s]


Epoch 2, Val Loss: 29424.539859693876, RMSE(mm): 74.55786410332068
Epoch 2, test Loss: 38534.68036511479, RMSE(mm): 75.3430944531491


1it [00:00,  3.72it/s]

Epoch 3, Batch 0, position loss: 20781.41015625 reconstruction loss: 51.142635345458984 RMSE(mm): 72.07879396231945


101it [00:27,  3.70it/s]

Epoch 3, Batch 100, position loss: 20048.20703125 reconstruction loss: 27.863767623901367 RMSE(mm): 70.79584562537903


201it [00:54,  3.71it/s]

Epoch 3, Batch 200, position loss: 23423.703125 reconstruction loss: 88.5316390991211 RMSE(mm): 76.52402094277326


236it [01:03,  3.71it/s]


Epoch 3, Val Loss: 24494.576092155614, RMSE(mm): 66.02279226127237
Epoch 3, test Loss: 32422.043447066328, RMSE(mm): 64.6694556379314


1it [00:00,  3.69it/s]

Epoch 4, Batch 0, position loss: 15773.720703125 reconstruction loss: 48.94576644897461 RMSE(mm): 62.796736983550744


101it [00:27,  3.68it/s]

Epoch 4, Batch 100, position loss: 15981.59765625 reconstruction loss: 26.25568199157715 RMSE(mm): 63.20917191407035


201it [00:54,  3.68it/s]

Epoch 4, Batch 200, position loss: 22427.380859375 reconstruction loss: 85.30419921875 RMSE(mm): 74.87887028290257


236it [01:03,  3.70it/s]


Epoch 4, Val Loss: 23246.430843431124, RMSE(mm): 63.849226678238786
Epoch 4, test Loss: 30639.215660873724, RMSE(mm): 61.359366636264326


1it [00:00,  3.70it/s]

Epoch 5, Batch 0, position loss: 13523.3466796875 reconstruction loss: 47.397247314453125 RMSE(mm): 58.14496254983638


101it [00:27,  3.69it/s]

Epoch 5, Batch 100, position loss: 14397.935546875 reconstruction loss: 25.479379653930664 RMSE(mm): 59.99569890182754


201it [00:54,  3.69it/s]

Epoch 5, Batch 200, position loss: 20514.01171875 reconstruction loss: 85.21058654785156 RMSE(mm): 71.61356665945009


236it [01:03,  3.70it/s]


Epoch 5, Val Loss: 22853.262057557396, RMSE(mm): 63.19960447802069
Epoch 5, test Loss: 29835.99067283163, RMSE(mm): 59.827260301765804


1it [00:00,  3.68it/s]

Epoch 6, Batch 0, position loss: 12863.7509765625 reconstruction loss: 46.51823043823242 RMSE(mm): 56.70923861365646


101it [00:27,  3.70it/s]

Epoch 6, Batch 100, position loss: 13690.44140625 reconstruction loss: 25.618375778198242 RMSE(mm): 58.50307984681234


201it [00:54,  3.69it/s]

Epoch 6, Batch 200, position loss: 14699.0625 reconstruction loss: 80.96692657470703 RMSE(mm): 60.61984514166957


236it [01:03,  3.71it/s]


Epoch 6, Val Loss: 22093.566904496172, RMSE(mm): 61.7433760367447
Epoch 6, test Loss: 29120.791812818876, RMSE(mm): 58.380008279454565


1it [00:00,  3.71it/s]

Epoch 7, Batch 0, position loss: 11587.73046875 reconstruction loss: 45.93209457397461 RMSE(mm): 53.823160601988995


101it [00:27,  3.69it/s]

Epoch 7, Batch 100, position loss: 13058.251953125 reconstruction loss: 25.206066131591797 RMSE(mm): 57.136354348884126


201it [00:54,  3.70it/s]

Epoch 7, Batch 200, position loss: 14608.212890625 reconstruction loss: 80.81102752685547 RMSE(mm): 60.43222007055714


236it [01:03,  3.70it/s]


Epoch 7, Val Loss: 22014.372867506376, RMSE(mm): 61.612421001901566
Epoch 7, test Loss: 28944.157625159438, RMSE(mm): 58.02510149357985


1it [00:00,  3.69it/s]

Epoch 8, Batch 0, position loss: 10954.775390625 reconstruction loss: 45.686222076416016 RMSE(mm): 52.33253144704783


101it [00:27,  3.70it/s]

Epoch 8, Batch 100, position loss: 12556.4140625 reconstruction loss: 24.99095916748047 RMSE(mm): 56.0277031085962


201it [00:54,  3.69it/s]

Epoch 8, Batch 200, position loss: 14356.4453125 reconstruction loss: 80.60693359375 RMSE(mm): 59.90919235079872


236it [01:03,  3.70it/s]


Epoch 8, Val Loss: 22019.884028220662, RMSE(mm): 61.64518777084659
Epoch 8, test Loss: 28834.906887755104, RMSE(mm): 57.80748849279845


1it [00:00,  3.70it/s]

Epoch 9, Batch 0, position loss: 10455.966796875 reconstruction loss: 45.49930953979492 RMSE(mm): 51.127210946997195


101it [00:27,  3.70it/s]

Epoch 9, Batch 100, position loss: 11608.126953125 reconstruction loss: 24.88254165649414 RMSE(mm): 53.87050898479845


201it [00:54,  3.70it/s]

Epoch 9, Batch 200, position loss: 13247.822265625 reconstruction loss: 80.4644775390625 RMSE(mm): 57.54959223492596


236it [01:03,  3.71it/s]


Epoch 9, Val Loss: 21977.478017378828, RMSE(mm): 61.57895317793082
Epoch 9, test Loss: 28690.149513711734, RMSE(mm): 57.5103256364201


1it [00:00,  3.71it/s]

Epoch 10, Batch 0, position loss: 10374.9375 reconstruction loss: 45.37114715576172 RMSE(mm): 50.928718568210606


101it [00:27,  3.70it/s]

Epoch 10, Batch 100, position loss: 11191.1796875 reconstruction loss: 24.773221969604492 RMSE(mm): 52.8941860876505


201it [00:54,  3.70it/s]

Epoch 10, Batch 200, position loss: 12573.8095703125 reconstruction loss: 80.36309814453125 RMSE(mm): 56.06649973538677


236it [01:03,  3.70it/s]


Epoch 10, Val Loss: 22104.72905373087, RMSE(mm): 61.84930170867804
Epoch 10, test Loss: 28730.59303252551, RMSE(mm): 57.607215681968405


1it [00:00,  3.68it/s]

Epoch 11, Batch 0, position loss: 10325.7041015625 reconstruction loss: 45.24081802368164 RMSE(mm): 50.807735881365794


101it [00:27,  3.69it/s]

Epoch 11, Batch 100, position loss: 10805.7958984375 reconstruction loss: 24.747364044189453 RMSE(mm): 51.97546512162614


201it [00:54,  3.69it/s]

Epoch 11, Batch 200, position loss: 11645.0986328125 reconstruction loss: 80.30244445800781 RMSE(mm): 53.95622909547261


236it [01:03,  3.70it/s]


Epoch 11, Val Loss: 22217.665457589286, RMSE(mm): 62.088307499022
Epoch 11, test Loss: 28675.756796077807, RMSE(mm): 57.49525901387058


1it [00:00,  3.69it/s]

Epoch 12, Batch 0, position loss: 10010.462890625 reconstruction loss: 45.15732955932617 RMSE(mm): 50.0261503881345


101it [00:27,  3.68it/s]

Epoch 12, Batch 100, position loss: 10414.953125 reconstruction loss: 25.09856605529785 RMSE(mm): 51.026838832618274


201it [00:54,  3.70it/s]

Epoch 12, Batch 200, position loss: 9818.39453125 reconstruction loss: 80.02660369873047 RMSE(mm): 49.54390611177625


236it [01:03,  3.70it/s]


Epoch 12, Val Loss: 21892.304906728317, RMSE(mm): 61.430786153720405
Epoch 12, test Loss: 28324.392538265307, RMSE(mm): 56.7254497443307


1it [00:00,  3.69it/s]

Epoch 13, Batch 0, position loss: 8825.859375 reconstruction loss: 45.08085250854492 RMSE(mm): 46.97302251026647


101it [00:27,  3.70it/s]

Epoch 13, Batch 100, position loss: 10412.5810546875 reconstruction loss: 25.066116333007812 RMSE(mm): 51.021027661855996


201it [00:54,  3.69it/s]

Epoch 13, Batch 200, position loss: 9567.6435546875 reconstruction loss: 80.04619598388672 RMSE(mm): 48.90716602576636


236it [01:03,  3.70it/s]


Epoch 13, Val Loss: 21902.631935586734, RMSE(mm): 61.45039745402509
Epoch 13, test Loss: 28329.980169802297, RMSE(mm): 56.735118969557085


1it [00:00,  3.72it/s]

Epoch 14, Batch 0, position loss: 8797.4501953125 reconstruction loss: 45.06415557861328 RMSE(mm): 46.897361853606704


101it [00:27,  3.69it/s]

Epoch 14, Batch 100, position loss: 10235.111328125 reconstruction loss: 25.070131301879883 RMSE(mm): 50.584363513157406


201it [00:54,  3.69it/s]

Epoch 14, Batch 200, position loss: 9895.525390625 reconstruction loss: 80.05618286132812 RMSE(mm): 49.73812770557664


236it [01:03,  3.70it/s]


Epoch 14, Val Loss: 21923.072405133928, RMSE(mm): 61.49138476073482
Epoch 14, test Loss: 28343.59915098852, RMSE(mm): 56.76368626950036


Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


1it [00:00,  2.59it/s]

Epoch 0, Batch 0, position loss: 168894.125 reconstruction loss: 80.14488220214844 RMSE(mm): 205.4836520261405


101it [00:27,  3.70it/s]

Epoch 0, Batch 100, position loss: 103678.796875 reconstruction loss: 52.68852233886719 RMSE(mm): 160.99596025599524


201it [00:54,  3.69it/s]

Epoch 0, Batch 200, position loss: 43915.1640625 reconstruction loss: 111.17869567871094 RMSE(mm): 104.77972616696896


236it [01:03,  3.70it/s]


Epoch 0, Val Loss: 44719.29631696428, RMSE(mm): 93.83929909439894
Epoch 0, test Loss: 57003.18343431123, RMSE(mm): 97.08351443531289


1it [00:00,  3.69it/s]

Epoch 1, Batch 0, position loss: 34816.796875 reconstruction loss: 67.11009979248047 RMSE(mm): 93.29629799059553


101it [00:27,  3.70it/s]

Epoch 1, Batch 100, position loss: 28139.181640625 reconstruction loss: 34.988739013671875 RMSE(mm): 83.8736872335791


201it [00:54,  3.69it/s]

Epoch 1, Batch 200, position loss: 31162.2578125 reconstruction loss: 97.34790802001953 RMSE(mm): 88.264174233519


236it [01:03,  3.71it/s]


Epoch 1, Val Loss: 31473.631696428572, RMSE(mm): 75.74203343051185
Epoch 1, test Loss: 41839.57362085459, RMSE(mm): 76.5544469421594


1it [00:00,  3.69it/s]

Epoch 2, Batch 0, position loss: 21215.734375 reconstruction loss: 55.04960632324219 RMSE(mm): 72.82810991471631


101it [00:27,  3.70it/s]

Epoch 2, Batch 100, position loss: 20140.861328125 reconstruction loss: 30.171499252319336 RMSE(mm): 70.95925120821985


201it [00:54,  3.69it/s]

Epoch 2, Batch 200, position loss: 22387.017578125 reconstruction loss: 92.66990661621094 RMSE(mm): 74.81145897876374


236it [01:03,  3.70it/s]


Epoch 2, Val Loss: 26296.38911033163, RMSE(mm): 67.18177657159958
Epoch 2, test Loss: 34991.12370455995, RMSE(mm): 64.98538015805792


1it [00:00,  3.70it/s]

Epoch 3, Batch 0, position loss: 16359.28515625 reconstruction loss: 51.185176849365234 RMSE(mm): 63.9517106030988


101it [00:27,  3.70it/s]

Epoch 3, Batch 100, position loss: 17454.7734375 reconstruction loss: 27.379064559936523 RMSE(mm): 66.0582573140936


201it [00:54,  3.69it/s]

Epoch 3, Batch 200, position loss: 18929.54296875 reconstruction loss: 88.39746856689453 RMSE(mm): 68.792337815977


236it [01:03,  3.70it/s]


Epoch 3, Val Loss: 24002.627531090562, RMSE(mm): 63.12801730671453
Epoch 3, test Loss: 32018.88602120536, RMSE(mm): 59.34264714191867


1it [00:00,  3.72it/s]

Epoch 4, Batch 0, position loss: 13302.53125 reconstruction loss: 49.05059051513672 RMSE(mm): 57.6682998925753


101it [00:27,  3.70it/s]

Epoch 4, Batch 100, position loss: 14021.6455078125 reconstruction loss: 26.077577590942383 RMSE(mm): 59.206514649598525


201it [00:54,  3.69it/s]

Epoch 4, Batch 200, position loss: 16790.30078125 reconstruction loss: 86.84977722167969 RMSE(mm): 64.78869650882397


236it [01:03,  3.71it/s]


Epoch 4, Val Loss: 23667.320691167093, RMSE(mm): 62.71377963486622
Epoch 4, test Loss: 31299.781668526786, RMSE(mm): 58.06835371666876


1it [00:00,  3.70it/s]

Epoch 5, Batch 0, position loss: 11743.771484375 reconstruction loss: 47.07837677001953 RMSE(mm): 54.18434156740995


101it [00:27,  3.69it/s]

Epoch 5, Batch 100, position loss: 13173.6015625 reconstruction loss: 25.2278995513916 RMSE(mm): 57.38815549070208


201it [00:54,  3.70it/s]

Epoch 5, Batch 200, position loss: 16351.998046875 reconstruction loss: 84.817138671875 RMSE(mm): 63.93746563415499


236it [01:03,  3.70it/s]


Epoch 5, Val Loss: 23865.84640066964, RMSE(mm): 63.37360116088694
Epoch 5, test Loss: 31432.235391422193, RMSE(mm): 58.590104478430206


1it [00:00,  3.70it/s]

Epoch 6, Batch 0, position loss: 11487.630859375 reconstruction loss: 45.50785446166992 RMSE(mm): 53.590183008119595


101it [00:27,  3.69it/s]

Epoch 6, Batch 100, position loss: 11271.951171875 reconstruction loss: 24.809476852416992 RMSE(mm): 53.08472278319583


201it [00:54,  3.70it/s]

Epoch 6, Batch 200, position loss: 13222.0556640625 reconstruction loss: 80.66413879394531 RMSE(mm): 57.493598913406224


236it [01:03,  3.70it/s]


Epoch 6, Val Loss: 22619.77176339286, RMSE(mm): 60.938254508672756
Epoch 6, test Loss: 30502.50924744898, RMSE(mm): 56.657823743508246


1it [00:00,  3.69it/s]

Epoch 7, Batch 0, position loss: 10020.779296875 reconstruction loss: 44.889122009277344 RMSE(mm): 50.05192128399019


101it [00:27,  3.70it/s]

Epoch 7, Batch 100, position loss: 10621.240234375 reconstruction loss: 24.60817527770996 RMSE(mm): 51.52970074232675


201it [00:54,  3.69it/s]

Epoch 7, Batch 200, position loss: 12367.703125 reconstruction loss: 80.55047607421875 RMSE(mm): 55.605087728102724


236it [01:03,  3.71it/s]


Epoch 7, Val Loss: 22624.731684470662, RMSE(mm): 60.966950628004604
Epoch 7, test Loss: 30386.85226004464, RMSE(mm): 56.41866648489375


1it [00:00,  3.70it/s]

Epoch 8, Batch 0, position loss: 9455.5693359375 reconstruction loss: 44.708614349365234 RMSE(mm): 48.619875914942185


101it [00:27,  3.70it/s]

Epoch 8, Batch 100, position loss: 10056.6328125 reconstruction loss: 24.540287017822266 RMSE(mm): 50.141382142148814


201it [00:54,  3.70it/s]

Epoch 8, Batch 200, position loss: 11317.6845703125 reconstruction loss: 80.36378479003906 RMSE(mm): 53.19230341485622


236it [01:03,  3.70it/s]


Epoch 8, Val Loss: 22645.827566964286, RMSE(mm): 61.03321407369121
Epoch 8, test Loss: 30303.465441645407, RMSE(mm): 56.25111358024708


1it [00:00,  3.69it/s]

Epoch 9, Batch 0, position loss: 9037.9677734375 reconstruction loss: 44.579139709472656 RMSE(mm): 47.5341134697953


101it [00:27,  3.69it/s]

Epoch 9, Batch 100, position loss: 9666.2744140625 reconstruction loss: 24.51806640625 RMSE(mm): 49.15860660673393


201it [00:54,  3.69it/s]

Epoch 9, Batch 200, position loss: 10786.1005859375 reconstruction loss: 80.34956359863281 RMSE(mm): 51.928076668449556


236it [01:03,  3.70it/s]


Epoch 9, Val Loss: 22783.92942841199, RMSE(mm): 61.312312260960724
Epoch 9, test Loss: 30440.80658083546, RMSE(mm): 56.54989099543855


1it [00:00,  3.70it/s]

Epoch 10, Batch 0, position loss: 8356.361328125 reconstruction loss: 44.509193420410156 RMSE(mm): 45.70656771221451


101it [00:27,  3.70it/s]

Epoch 10, Batch 100, position loss: 9503.6015625 reconstruction loss: 24.525882720947266 RMSE(mm): 48.743208661566385


201it [00:54,  3.69it/s]

Epoch 10, Batch 200, position loss: 9755.9326171875 reconstruction loss: 80.25424194335938 RMSE(mm): 49.38606234857032


236it [01:03,  3.70it/s]


Epoch 10, Val Loss: 22843.23736447704, RMSE(mm): 61.444173034328074
Epoch 10, test Loss: 30456.095583545917, RMSE(mm): 56.58952183122398


1it [00:00,  3.73it/s]

Epoch 11, Batch 0, position loss: 7834.287109375 reconstruction loss: 44.406036376953125 RMSE(mm): 44.255754172127155


101it [00:27,  3.70it/s]

Epoch 11, Batch 100, position loss: 8535.345703125 reconstruction loss: 24.521766662597656 RMSE(mm): 46.1934673496291


201it [00:54,  3.69it/s]

Epoch 11, Batch 200, position loss: 8835.61328125 reconstruction loss: 80.11632537841797 RMSE(mm): 46.99897148143244


236it [01:03,  3.70it/s]


Epoch 11, Val Loss: 23084.15254304847, RMSE(mm): 61.942786452876945
Epoch 11, test Loss: 30611.587990274234, RMSE(mm): 56.940443459488456


1it [00:00,  3.70it/s]

Epoch 12, Batch 0, position loss: 7697.2509765625 reconstruction loss: 44.40069580078125 RMSE(mm): 43.86698923040679


101it [00:27,  3.69it/s]

Epoch 12, Batch 100, position loss: 8450.72265625 reconstruction loss: 25.209623336791992 RMSE(mm): 45.96390610101039


201it [00:54,  3.69it/s]

Epoch 12, Batch 200, position loss: 8142.8837890625 reconstruction loss: 79.75630950927734 RMSE(mm): 45.118964386005416


236it [01:03,  3.70it/s]


Epoch 12, Val Loss: 22802.50005978954, RMSE(mm): 61.373041120504574
Epoch 12, test Loss: 30160.20063376913, RMSE(mm): 55.94746744242728


1it [00:00,  3.68it/s]

Epoch 13, Batch 0, position loss: 7365.8837890625 reconstruction loss: 44.35955810546875 RMSE(mm): 42.91236357118569


101it [00:27,  3.70it/s]

Epoch 13, Batch 100, position loss: 8227.8857421875 reconstruction loss: 25.112844467163086 RMSE(mm): 45.35384697626955


201it [00:54,  3.70it/s]

Epoch 13, Batch 200, position loss: 8070.44921875 reconstruction loss: 79.82431030273438 RMSE(mm): 44.91783949265036


236it [01:03,  3.70it/s]


Epoch 13, Val Loss: 22842.39799904337, RMSE(mm): 61.4418322269862
Epoch 13, test Loss: 30179.963189572703, RMSE(mm): 55.9791052626287


1it [00:00,  3.71it/s]

Epoch 14, Batch 0, position loss: 7129.662109375 reconstruction loss: 44.33007049560547 RMSE(mm): 42.21866325860815


101it [00:27,  3.69it/s]

Epoch 14, Batch 100, position loss: 8190.40966796875 reconstruction loss: 25.052019119262695 RMSE(mm): 45.25044106958724


201it [00:54,  3.70it/s]

Epoch 14, Batch 200, position loss: 7735.078125 reconstruction loss: 79.81995391845703 RMSE(mm): 43.97464645963626


236it [01:03,  3.70it/s]


Epoch 14, Val Loss: 22863.97797751913, RMSE(mm): 61.488290849649815
Epoch 14, test Loss: 30209.39646444515, RMSE(mm): 56.047334734734235


Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


1it [00:00,  2.59it/s]

Epoch 0, Batch 0, position loss: 169055.3125 reconstruction loss: 80.1513671875 RMSE(mm): 205.58168236737436


101it [00:27,  3.70it/s]

Epoch 0, Batch 100, position loss: 103432.7421875 reconstruction loss: 53.09626770019531 RMSE(mm): 160.80480573314654


201it [00:54,  3.69it/s]

Epoch 0, Batch 200, position loss: 44173.375 reconstruction loss: 114.11114501953125 RMSE(mm): 105.08731488624115


236it [01:03,  3.70it/s]


Epoch 0, Val Loss: 49860.327646683676, RMSE(mm): 97.87048429648527
Epoch 0, test Loss: 63716.610889668365, RMSE(mm): 101.50683668901799


1it [00:00,  3.73it/s]

Epoch 1, Batch 0, position loss: 39397.25390625 reconstruction loss: 76.09744262695312 RMSE(mm): 99.24370749101678


101it [00:27,  3.69it/s]

Epoch 1, Batch 100, position loss: 28747.640625 reconstruction loss: 43.23530578613281 RMSE(mm): 84.77564600903965


201it [00:54,  3.70it/s]

Epoch 1, Batch 200, position loss: 30122.1953125 reconstruction loss: 107.41170501708984 RMSE(mm): 86.77873488433096


236it [01:03,  3.71it/s]


Epoch 1, Val Loss: 33948.062978316324, RMSE(mm): 76.72982230514387
Epoch 1, test Loss: 45829.68447066326, RMSE(mm): 78.02691878963036


1it [00:00,  3.70it/s]

Epoch 2, Batch 0, position loss: 22341.52734375 reconstruction loss: 65.11972045898438 RMSE(mm): 74.73541219487252


101it [00:27,  3.69it/s]

Epoch 2, Batch 100, position loss: 21974.248046875 reconstruction loss: 33.635711669921875 RMSE(mm): 74.11856725354822


201it [00:54,  3.70it/s]

Epoch 2, Batch 200, position loss: 22607.787109375 reconstruction loss: 96.08468627929688 RMSE(mm): 75.17943054681746


236it [01:03,  3.70it/s]


Epoch 2, Val Loss: 28008.874920280614, RMSE(mm): 67.9181594284025
Epoch 2, test Loss: 38103.5338408801, RMSE(mm): 66.07900015435972


1it [00:00,  3.72it/s]

Epoch 3, Batch 0, position loss: 16981.919921875 reconstruction loss: 54.28668212890625 RMSE(mm): 65.15734786245332


101it [00:27,  3.70it/s]

Epoch 3, Batch 100, position loss: 16753.77734375 reconstruction loss: 27.61092185974121 RMSE(mm): 64.71819169242525


201it [00:54,  3.69it/s]

Epoch 3, Batch 200, position loss: 19495.53125 reconstruction loss: 89.06686401367188 RMSE(mm): 69.81319941458062


236it [01:03,  3.70it/s]


Epoch 3, Val Loss: 25281.020328443876, RMSE(mm): 63.652833871910715
Epoch 3, test Loss: 35255.55514588648, RMSE(mm): 61.41101143617355


1it [00:00,  3.65it/s]

Epoch 4, Batch 0, position loss: 13317.876953125 reconstruction loss: 49.2802619934082 RMSE(mm): 57.70155317044117


101it [00:27,  3.69it/s]

Epoch 4, Batch 100, position loss: 14554.6796875 reconstruction loss: 25.496294021606445 RMSE(mm): 60.32138859372353


201it [00:54,  3.70it/s]

Epoch 4, Batch 200, position loss: 17159.755859375 reconstruction loss: 85.21659088134766 RMSE(mm): 65.49762564279526


236it [01:03,  3.70it/s]


Epoch 4, Val Loss: 24421.142239317604, RMSE(mm): 62.445805066730294
Epoch 4, test Loss: 34063.57386001275, RMSE(mm): 59.40788252662968


1it [00:00,  3.68it/s]

Epoch 5, Batch 0, position loss: 12077.30859375 reconstruction loss: 46.56559753417969 RMSE(mm): 54.94840442121591


101it [00:27,  3.70it/s]

Epoch 5, Batch 100, position loss: 12120.1923828125 reconstruction loss: 24.031980514526367 RMSE(mm): 55.045872649119886


201it [00:54,  3.70it/s]

Epoch 5, Batch 200, position loss: 16206.0966796875 reconstruction loss: 83.16236877441406 RMSE(mm): 63.651584190198086


236it [01:03,  3.71it/s]


Epoch 5, Val Loss: 24391.999123086734, RMSE(mm): 62.702706715168866
Epoch 5, test Loss: 33601.22018494898, RMSE(mm): 58.694134672162114


1it [00:00,  3.69it/s]

Epoch 6, Batch 0, position loss: 10301.8896484375 reconstruction loss: 45.00914001464844 RMSE(mm): 50.74911242681368


101it [00:27,  3.69it/s]

Epoch 6, Batch 100, position loss: 11824.8828125 reconstruction loss: 23.814441680908203 RMSE(mm): 54.371138512311845


201it [00:54,  3.70it/s]

Epoch 6, Batch 200, position loss: 12038.5029296875 reconstruction loss: 79.14616394042969 RMSE(mm): 54.86005589153073


236it [01:03,  3.71it/s]


Epoch 6, Val Loss: 23816.009008290817, RMSE(mm): 61.66582023038294
Epoch 6, test Loss: 33343.33484135842, RMSE(mm): 58.27669414745263


1it [00:00,  3.72it/s]

Epoch 7, Batch 0, position loss: 10164.8955078125 reconstruction loss: 43.90434265136719 RMSE(mm): 50.41055322998474


101it [00:27,  3.69it/s]

Epoch 7, Batch 100, position loss: 10955.54296875 reconstruction loss: 23.52843475341797 RMSE(mm): 52.33436483026712


201it [00:54,  3.69it/s]

Epoch 7, Batch 200, position loss: 12040.8505859375 reconstruction loss: 78.90946960449219 RMSE(mm): 54.86540482384483


236it [01:03,  3.70it/s]


Epoch 7, Val Loss: 23710.287408322703, RMSE(mm): 61.492115700855074
Epoch 7, test Loss: 33186.246273118624, RMSE(mm): 57.97343518338286


1it [00:00,  3.70it/s]

Epoch 8, Batch 0, position loss: 9229.0 reconstruction loss: 43.68096160888672 RMSE(mm): 48.03384223648989


101it [00:27,  3.68it/s]

Epoch 8, Batch 100, position loss: 10477.53125 reconstruction loss: 23.41002082824707 RMSE(mm): 51.1799063353969


201it [00:54,  3.70it/s]

Epoch 8, Batch 200, position loss: 11541.6748046875 reconstruction loss: 78.90133666992188 RMSE(mm): 53.716093502523755


236it [01:03,  3.70it/s]


Epoch 8, Val Loss: 23652.01030373087, RMSE(mm): 61.392518067864025
Epoch 8, test Loss: 33060.735132334186, RMSE(mm): 57.72005057241332


1it [00:00,  3.69it/s]

Epoch 9, Batch 0, position loss: 8538.1875 reconstruction loss: 43.55836486816406 RMSE(mm): 46.20115664136559


101it [00:27,  3.70it/s]

Epoch 9, Batch 100, position loss: 10100.6640625 reconstruction loss: 23.395620346069336 RMSE(mm): 50.251029995662776


201it [00:54,  3.69it/s]

Epoch 9, Batch 200, position loss: 11310.84765625 reconstruction loss: 78.6954574584961 RMSE(mm): 53.17623448555285


236it [01:03,  3.70it/s]


Epoch 9, Val Loss: 23679.840142697703, RMSE(mm): 61.48398857753993
Epoch 9, test Loss: 33079.01773756377, RMSE(mm): 57.787924701192786


1it [00:00,  3.69it/s]

Epoch 10, Batch 0, position loss: 8020.48486328125 reconstruction loss: 43.42268371582031 RMSE(mm): 44.778579877217105


101it [00:27,  3.70it/s]

Epoch 10, Batch 100, position loss: 9309.2578125 reconstruction loss: 23.315906524658203 RMSE(mm): 48.242247596116414


201it [00:54,  3.70it/s]

Epoch 10, Batch 200, position loss: 10645.9912109375 reconstruction loss: 78.72673034667969 RMSE(mm): 51.58970636410305


236it [01:03,  3.70it/s]


Epoch 10, Val Loss: 23738.39863679847, RMSE(mm): 61.608672947808145
Epoch 10, test Loss: 33152.999003507655, RMSE(mm): 57.95252433956441


1it [00:00,  3.69it/s]

Epoch 11, Batch 0, position loss: 7856.8955078125 reconstruction loss: 43.315185546875 RMSE(mm): 44.31956539670854


101it [00:27,  3.70it/s]

Epoch 11, Batch 100, position loss: 8943.37109375 reconstruction loss: 23.27486801147461 RMSE(mm): 47.2846991471607


201it [00:54,  3.71it/s]

Epoch 11, Batch 200, position loss: 9989.076171875 reconstruction loss: 78.47974395751953 RMSE(mm): 49.97268296748484


236it [01:03,  3.71it/s]


Epoch 11, Val Loss: 23917.09347098214, RMSE(mm): 62.00052629037757
Epoch 11, test Loss: 33388.82001355229, RMSE(mm): 58.48486059831553


1it [00:00,  3.70it/s]

Epoch 12, Batch 0, position loss: 7129.68505859375 reconstruction loss: 43.2285041809082 RMSE(mm): 42.21873120604689


101it [00:27,  3.70it/s]

Epoch 12, Batch 100, position loss: 9894.525390625 reconstruction loss: 23.920198440551758 RMSE(mm): 49.735614479528145


201it [00:54,  3.70it/s]

Epoch 12, Batch 200, position loss: 8552.224609375 reconstruction loss: 77.97055053710938 RMSE(mm): 46.239119285987165


236it [01:03,  3.71it/s]


Epoch 12, Val Loss: 23664.01763791454, RMSE(mm): 61.49254347626876
Epoch 12, test Loss: 32890.51393096301, RMSE(mm): 57.41816613907339


1it [00:00,  3.70it/s]

Epoch 13, Batch 0, position loss: 7241.37939453125 reconstruction loss: 43.16444396972656 RMSE(mm): 42.54814741716509


101it [00:27,  3.70it/s]

Epoch 13, Batch 100, position loss: 9705.5185546875 reconstruction loss: 23.86785316467285 RMSE(mm): 49.25829512551033


201it [00:54,  3.69it/s]

Epoch 13, Batch 200, position loss: 8238.6416015625 reconstruction loss: 78.00052642822266 RMSE(mm): 45.38348158075386


236it [01:03,  3.70it/s]


Epoch 13, Val Loss: 23678.56523038903, RMSE(mm): 61.51228657652428
Epoch 13, test Loss: 32865.26012436225, RMSE(mm): 57.35475384728917


1it [00:00,  3.70it/s]

Epoch 14, Batch 0, position loss: 7213.37451171875 reconstruction loss: 43.17136764526367 RMSE(mm): 42.46579362180445


101it [00:27,  3.70it/s]

Epoch 14, Batch 100, position loss: 9818.25 reconstruction loss: 23.824634552001953 RMSE(mm): 49.54354145597588


201it [00:54,  3.69it/s]

Epoch 14, Batch 200, position loss: 8365.8896484375 reconstruction loss: 78.02544403076172 RMSE(mm): 45.73261868851788


236it [01:03,  3.70it/s]


Epoch 14, Val Loss: 23713.63873166454, RMSE(mm): 61.58026170953323
Epoch 14, test Loss: 32872.623286033166, RMSE(mm): 57.36732119782326
