In [1]:
from models.MTLVit import MTLViT_pretrained
from helper_function_test import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = MTLViT_pretrained()
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
create dataloader...
HI
training...


1it [00:00,  1.43it/s]

Epoch 0, Batch 0, Loss: 169056.3125 RMSE(mm): 205.5579297910932


101it [00:31,  3.25it/s]

Epoch 0, Batch 100, Loss: 106343.796875 RMSE(mm): 163.03158244646954


201it [01:02,  3.20it/s]

Epoch 0, Batch 200, Loss: 45238.4453125 RMSE(mm): 106.27918257324667


236it [01:13,  3.20it/s]


Epoch 0, Val Loss: 38629.351801658166, RMSE(mm): 98.27175560869227
Epoch 0, test Loss: 39923.055147058825, RMSE(mm): 99.90377263529494


1it [00:00,  3.19it/s]

Epoch 1, Batch 0, Loss: 39648.69921875 RMSE(mm): 99.5100301163154


101it [00:31,  3.22it/s]

Epoch 1, Batch 100, Loss: 31852.205078125 RMSE(mm): 89.19880468824961


201it [01:02,  3.20it/s]

Epoch 1, Batch 200, Loss: 29805.75 RMSE(mm): 86.23852391949029


236it [01:13,  3.21it/s]


Epoch 1, Val Loss: 24689.065090880104, RMSE(mm): 78.56377201178687
Epoch 1, test Loss: 24561.247280943626, RMSE(mm): 78.36014178289818


1it [00:00,  3.21it/s]

Epoch 2, Batch 0, Loss: 22916.95703125 RMSE(mm): 75.6261976919622


101it [00:31,  3.28it/s]

Epoch 2, Batch 100, Loss: 23785.13671875 RMSE(mm): 77.06921921741034


201it [01:02,  3.18it/s]

Epoch 2, Batch 200, Loss: 30221.841796875 RMSE(mm): 86.83952175744923


236it [01:13,  3.20it/s]


Epoch 2, Val Loss: 21154.08761160714, RMSE(mm): 72.72222427086362
Epoch 2, test Loss: 20781.572878370098, RMSE(mm): 72.07907615662485


1it [00:00,  3.22it/s]

Epoch 3, Batch 0, Loss: 19552.787109375 RMSE(mm): 69.84468679461237


101it [00:31,  3.22it/s]

Epoch 3, Batch 100, Loss: 23055.736328125 RMSE(mm): 75.87696275262012


201it [01:02,  3.22it/s]

Epoch 3, Batch 200, Loss: 24352.482421875 RMSE(mm): 77.93445513298339


236it [01:13,  3.20it/s]


Epoch 3, Val Loss: 20660.765385841838, RMSE(mm): 71.86926565967165
Epoch 3, test Loss: 20181.56294041054, RMSE(mm): 71.03091393965471


1it [00:00,  3.21it/s]

Epoch 4, Batch 0, Loss: 18561.076171875 RMSE(mm): 68.04673686840171


101it [00:31,  3.20it/s]

Epoch 4, Batch 100, Loss: 16993.05859375 RMSE(mm): 65.12810393274934


201it [01:02,  3.21it/s]

Epoch 4, Batch 200, Loss: 23398.197265625 RMSE(mm): 76.3885460061749


236it [01:13,  3.20it/s]


Epoch 4, Val Loss: 17017.10845822704, RMSE(mm): 65.22481977404583
Epoch 4, test Loss: 15295.10950903799, RMSE(mm): 61.8366992752645


1it [00:00,  3.20it/s]

Epoch 5, Batch 0, Loss: 16046.08203125 RMSE(mm): 63.258356198262454


101it [00:31,  3.17it/s]

Epoch 5, Batch 100, Loss: 14999.4765625 RMSE(mm): 61.18234864040649


201it [01:03,  3.15it/s]

Epoch 5, Batch 200, Loss: 20280.162109375 RMSE(mm): 71.10348491041948


236it [01:13,  3.19it/s]


Epoch 5, Val Loss: 15630.991111288266, RMSE(mm): 62.51198107420742
Epoch 5, test Loss: 13191.340628829657, RMSE(mm): 57.42678083618665


1it [00:00,  3.21it/s]

Epoch 6, Batch 0, Loss: 13943.943359375 RMSE(mm): 58.958375892578864


101it [00:31,  3.24it/s]

Epoch 6, Batch 100, Loss: 13235.2958984375 RMSE(mm): 57.4650645399283


201it [01:03,  3.14it/s]

Epoch 6, Batch 200, Loss: 14972.8359375 RMSE(mm): 61.06483091124342


236it [01:14,  3.19it/s]


Epoch 6, Val Loss: 15306.220683195153, RMSE(mm): 61.85915591728349
Epoch 6, test Loss: 13175.781747855392, RMSE(mm): 57.392904064560526


1it [00:00,  3.05it/s]

Epoch 7, Batch 0, Loss: 11571.30078125 RMSE(mm): 53.69298620470019


101it [00:32,  3.03it/s]

Epoch 7, Batch 100, Loss: 13029.65234375 RMSE(mm): 57.01600181432073


201it [01:04,  3.23it/s]

Epoch 7, Batch 200, Loss: 14777.6318359375 RMSE(mm): 60.663941262757156


236it [01:15,  3.14it/s]


Epoch 7, Val Loss: 15162.428053252552, RMSE(mm): 61.567905708356996
Epoch 7, test Loss: 13024.79576439951, RMSE(mm): 57.06311366460717


1it [00:00,  3.26it/s]

Epoch 8, Batch 0, Loss: 11175.1240234375 RMSE(mm): 52.76261975081175


101it [00:31,  3.25it/s]

Epoch 8, Batch 100, Loss: 12459.3251953125 RMSE(mm): 55.75162028194786


201it [01:01,  3.24it/s]

Epoch 8, Batch 200, Loss: 14723.4384765625 RMSE(mm): 60.552175171241785


236it [01:12,  3.25it/s]


Epoch 8, Val Loss: 15005.860152264031, RMSE(mm): 61.24920438720823
Epoch 8, test Loss: 12809.587373621323, RMSE(mm): 56.589723832205884


1it [00:00,  3.29it/s]

Epoch 9, Batch 0, Loss: 10799.94140625 RMSE(mm): 51.8661725358217


101it [00:31,  3.25it/s]

Epoch 9, Batch 100, Loss: 12087.8369140625 RMSE(mm): 54.912396941771036


201it [01:01,  3.26it/s]

Epoch 9, Batch 200, Loss: 14561.544921875 RMSE(mm): 60.217055308276244


236it [01:12,  3.25it/s]


Epoch 9, Val Loss: 14889.715182557398, RMSE(mm): 61.011710315638176
Epoch 9, test Loss: 12645.775620404413, RMSE(mm): 56.226718782987


1it [00:00,  3.22it/s]

Epoch 10, Batch 0, Loss: 10375.2783203125 RMSE(mm): 50.832426136030534


101it [00:31,  3.27it/s]

Epoch 10, Batch 100, Loss: 11749.2451171875 RMSE(mm): 54.13615827533849


201it [01:01,  3.26it/s]

Epoch 10, Batch 200, Loss: 13554.3486328125 RMSE(mm): 58.08868783418055


236it [01:12,  3.25it/s]


Epoch 10, Val Loss: 14774.77682557398, RMSE(mm): 60.775769895522465
Epoch 10, test Loss: 12488.443876378677, RMSE(mm): 55.87585318448989


1it [00:00,  3.26it/s]

Epoch 11, Batch 0, Loss: 10016.712890625 RMSE(mm): 49.94292641042873


101it [00:31,  3.22it/s]

Epoch 11, Batch 100, Loss: 11466.681640625 RMSE(mm): 53.4797439018971


201it [01:01,  3.25it/s]

Epoch 11, Batch 200, Loss: 13311.337890625 RMSE(mm): 57.563390669005074


236it [01:12,  3.25it/s]


Epoch 11, Val Loss: 14663.34547393176, RMSE(mm): 60.5461507321724
Epoch 11, test Loss: 12332.87611060049, RMSE(mm): 55.52674155440892


1it [00:00,  3.26it/s]

Epoch 12, Batch 0, Loss: 9611.0419921875 RMSE(mm): 48.91707148647085


101it [00:31,  3.24it/s]

Epoch 12, Batch 100, Loss: 11593.400390625 RMSE(mm): 53.77512357973364


201it [01:01,  3.26it/s]

Epoch 12, Batch 200, Loss: 10969.724609375 RMSE(mm): 52.23160093964908


236it [01:12,  3.25it/s]


Epoch 12, Val Loss: 14474.810417330995, RMSE(mm): 60.15565313694756
Epoch 12, test Loss: 12292.944843367035, RMSE(mm): 55.43677669960402


1it [00:00,  3.19it/s]

Epoch 13, Batch 0, Loss: 9375.9970703125 RMSE(mm): 48.31272740082317


101it [00:30,  3.28it/s]

Epoch 13, Batch 100, Loss: 11393.8759765625 RMSE(mm): 53.30931262453119


201it [01:01,  3.25it/s]

Epoch 13, Batch 200, Loss: 11142.328125 RMSE(mm): 52.643059827928646


236it [01:12,  3.26it/s]


Epoch 13, Val Loss: 14465.506786112883, RMSE(mm): 60.13631761696272
Epoch 13, test Loss: 12275.111806832108, RMSE(mm): 55.396551803411256


1it [00:00,  3.27it/s]

Epoch 14, Batch 0, Loss: 9260.6279296875 RMSE(mm): 48.01331653253215


101it [00:30,  3.29it/s]

Epoch 14, Batch 100, Loss: 11451.1845703125 RMSE(mm): 53.443521225097996


201it [01:02,  3.25it/s]

Epoch 14, Batch 200, Loss: 11144.69140625 RMSE(mm): 52.648675734918776


236it [01:12,  3.25it/s]


Epoch 14, Val Loss: 14464.810467155612, RMSE(mm): 60.13487022343112
Epoch 14, test Loss: 12265.502096737133, RMSE(mm): 55.37486364935162
