In [2]:
from models.EEGViT_pretrained import EEGViT_pretrained
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch


In [3]:
'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained()
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
create dataloader...
HI
training...


1it [00:01,  1.33s/it]

Epoch 0, Batch 0, Loss: 168965.1875 RMSE(mm): 205.52687628385735


101it [00:33,  3.20it/s]

Epoch 0, Batch 100, Loss: 66881.734375 RMSE(mm): 129.30751561200918


201it [01:04,  3.17it/s]

Epoch 0, Batch 200, Loss: 35367.3203125 RMSE(mm): 94.03100594019507


236it [01:15,  3.13it/s]


Epoch 0, Val Loss: 28839.714245854593, RMSE(mm): 84.91129819678679
Epoch 0, test Loss: 29277.713809742647, RMSE(mm): 85.55365832292422


1it [00:00,  3.20it/s]

Epoch 1, Batch 0, Loss: 28025.11328125 RMSE(mm): 83.70351438447791


101it [00:31,  3.18it/s]

Epoch 1, Batch 100, Loss: 27578.28125 RMSE(mm): 83.03354931893493


201it [01:02,  3.18it/s]

Epoch 1, Batch 200, Loss: 30283.8203125 RMSE(mm): 87.0112353556999


236it [01:13,  3.20it/s]


Epoch 1, Val Loss: 23255.297512755104, RMSE(mm): 76.24843852951204
Epoch 1, test Loss: 22677.50049785539, RMSE(mm): 75.2952530008622


1it [00:00,  3.15it/s]

Epoch 2, Batch 0, Loss: 21253.662109375 RMSE(mm): 72.89317888076874


101it [00:31,  3.18it/s]

Epoch 2, Batch 100, Loss: 23413.1953125 RMSE(mm): 76.50685477867326


201it [01:02,  3.22it/s]

Epoch 2, Batch 200, Loss: 26665.6953125 RMSE(mm): 81.64817100293797


236it [01:13,  3.21it/s]


Epoch 2, Val Loss: 21747.29982461735, RMSE(mm): 73.73482865074236
Epoch 2, test Loss: 20857.43114276961, RMSE(mm): 72.2105102162587


1it [00:00,  3.19it/s]

Epoch 3, Batch 0, Loss: 19913.705078125 RMSE(mm): 70.55796389870707


101it [00:31,  3.19it/s]

Epoch 3, Batch 100, Loss: 20304.0859375 RMSE(mm): 71.2462032979653


201it [01:03,  3.17it/s]

Epoch 3, Batch 200, Loss: 21670.44921875 RMSE(mm): 73.60443128431535


236it [01:14,  3.18it/s]


Epoch 3, Val Loss: 17224.214225924745, RMSE(mm): 65.62052694455589
Epoch 3, test Loss: 15531.76407398897, RMSE(mm): 62.313249140910976


1it [00:00,  2.88it/s]

Epoch 4, Batch 0, Loss: 14995.2158203125 RMSE(mm): 61.22747712488344


101it [00:31,  3.18it/s]

Epoch 4, Batch 100, Loss: 15630.234375 RMSE(mm): 62.51046787338901


201it [01:03,  3.15it/s]

Epoch 4, Batch 200, Loss: 18907.1015625 RMSE(mm): 68.75154827802062


236it [01:14,  3.17it/s]


Epoch 4, Val Loss: 15745.7685546875, RMSE(mm): 62.74107218299569
Epoch 4, test Loss: 13291.745538449755, RMSE(mm): 57.644916381346576


1it [00:00,  3.20it/s]

Epoch 5, Batch 0, Loss: 12360.1357421875 RMSE(mm): 55.5880736808434


101it [00:32,  3.19it/s]

Epoch 5, Batch 100, Loss: 13314.96484375 RMSE(mm): 57.6952442662088


201it [01:04,  3.19it/s]

Epoch 5, Batch 200, Loss: 17872.681640625 RMSE(mm): 66.84437455879328


236it [01:15,  3.14it/s]


Epoch 5, Val Loss: 15967.239357461734, RMSE(mm): 63.180771120376754
Epoch 5, test Loss: 13200.615579044117, RMSE(mm): 57.446965931727235


1it [00:00,  3.20it/s]

Epoch 6, Batch 0, Loss: 10891.2392578125 RMSE(mm): 52.180550154757135


101it [00:31,  3.21it/s]

Epoch 6, Batch 100, Loss: 11844.1376953125 RMSE(mm): 54.4153877485783


201it [01:03,  3.17it/s]

Epoch 6, Batch 200, Loss: 14342.005859375 RMSE(mm): 59.8790569802477


236it [01:14,  3.18it/s]


Epoch 6, Val Loss: 15078.46340880102, RMSE(mm): 61.3971974295265
Epoch 6, test Loss: 12659.061236213236, RMSE(mm): 56.256246844713246


1it [00:00,  3.19it/s]

Epoch 7, Batch 0, Loss: 9341.4423828125 RMSE(mm): 48.32556875716131


101it [00:31,  3.13it/s]

Epoch 7, Batch 100, Loss: 11043.896484375 RMSE(mm): 52.54497236742779


201it [01:03,  3.17it/s]

Epoch 7, Batch 200, Loss: 14050.072265625 RMSE(mm): 59.26650037252284


236it [01:14,  3.17it/s]


Epoch 7, Val Loss: 14947.699597417091, RMSE(mm): 61.130392599379505
Epoch 7, test Loss: 12556.312346813726, RMSE(mm): 56.02747617645677


1it [00:00,  3.44it/s]

Epoch 8, Batch 0, Loss: 8683.798828125 RMSE(mm): 46.59345133204075


101it [00:30,  3.36it/s]

Epoch 8, Batch 100, Loss: 10544.4482421875 RMSE(mm): 51.34308191516044


201it [00:59,  3.40it/s]

Epoch 8, Batch 200, Loss: 13505.8271484375 RMSE(mm): 58.10728686756399


236it [01:09,  3.37it/s]


Epoch 8, Val Loss: 14891.110710299745, RMSE(mm): 61.01456938776948
Epoch 8, test Loss: 12477.005323223038, RMSE(mm): 55.85025810867627


1it [00:00,  3.37it/s]

Epoch 9, Batch 0, Loss: 8109.79150390625 RMSE(mm): 45.027190407314585


101it [00:29,  3.42it/s]

Epoch 9, Batch 100, Loss: 9757.859375 RMSE(mm): 49.3909388830583


201it [00:58,  3.42it/s]

Epoch 9, Batch 200, Loss: 12862.779296875 RMSE(mm): 56.70709677120448


236it [01:08,  3.42it/s]


Epoch 9, Val Loss: 14854.935885682398, RMSE(mm): 60.94041328560711
Epoch 9, test Loss: 12436.491536458334, RMSE(mm): 55.75950936041837


1it [00:00,  3.57it/s]

Epoch 10, Batch 0, Loss: 7551.2783203125 RMSE(mm): 43.44904579019112


101it [00:28,  3.54it/s]

Epoch 10, Batch 100, Loss: 8957.6201171875 RMSE(mm): 47.322352322099064


201it [00:56,  3.54it/s]

Epoch 10, Batch 200, Loss: 12074.1630859375 RMSE(mm): 54.941248361175546


236it [01:06,  3.55it/s]


Epoch 10, Val Loss: 14903.368602519133, RMSE(mm): 61.0396768555485
Epoch 10, test Loss: 12478.870404411764, RMSE(mm): 55.85443224223966


1it [00:00,  3.55it/s]

Epoch 11, Batch 0, Loss: 7138.38818359375 RMSE(mm): 42.24449130831661


101it [00:29,  3.39it/s]

Epoch 11, Batch 100, Loss: 8774.462890625 RMSE(mm): 46.83605152717562


201it [00:58,  3.42it/s]

Epoch 11, Batch 200, Loss: 11056.3232421875 RMSE(mm): 52.57452625128328


236it [01:09,  3.42it/s]


Epoch 11, Val Loss: 14954.63490513393, RMSE(mm): 61.144572337072425
Epoch 11, test Loss: 12528.500995710785, RMSE(mm): 55.96539331522379


1it [00:00,  3.46it/s]

Epoch 12, Batch 0, Loss: 6815.2890625 RMSE(mm): 41.27738201030923


101it [00:29,  3.43it/s]

Epoch 12, Batch 100, Loss: 9195.70703125 RMSE(mm): 47.94712460421897


201it [00:58,  3.41it/s]

Epoch 12, Batch 200, Loss: 8961.443359375 RMSE(mm): 47.33245017790385


236it [01:08,  3.42it/s]


Epoch 12, Val Loss: 14695.584353077169, RMSE(mm): 60.61267267056694
Epoch 12, test Loss: 12322.171396292892, RMSE(mm): 55.50263821723453


1it [00:00,  3.41it/s]

Epoch 13, Batch 0, Loss: 7128.0205078125 RMSE(mm): 42.213802564482684


101it [00:29,  3.42it/s]

Epoch 13, Batch 100, Loss: 8994.05078125 RMSE(mm): 47.41848474289852


201it [00:58,  3.42it/s]

Epoch 13, Batch 200, Loss: 9093.7099609375 RMSE(mm): 47.68047283987833


236it [01:09,  3.41it/s]


Epoch 13, Val Loss: 14677.886768574617, RMSE(mm): 60.57616438949939
Epoch 13, test Loss: 12319.057674632353, RMSE(mm): 55.49562522089546


1it [00:00,  3.42it/s]

Epoch 14, Batch 0, Loss: 6976.23486328125 RMSE(mm): 41.761929024175984


101it [00:29,  3.43it/s]

Epoch 14, Batch 100, Loss: 8917.52734375 RMSE(mm): 47.21633018286682


201it [00:58,  3.42it/s]

Epoch 14, Batch 200, Loss: 9069.603515625 RMSE(mm): 47.617233003464726


236it [01:08,  3.43it/s]


Epoch 14, Val Loss: 14687.217753507653, RMSE(mm): 60.59541598484916
Epoch 14, test Loss: 12337.473939185049, RMSE(mm): 55.53709107250993
