In [1]:
from models.EEGViT_pretrained_large import EEGViT_pretrained
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained()
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')

batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
create dataloader...
HI
training...


1it [00:00,  1.01it/s]

Epoch 0, Batch 0, Loss: 169069.640625 RMSE(mm): 205.59039412445807


101it [00:29,  3.49it/s]

Epoch 0, Batch 100, Loss: 67534.875 RMSE(mm): 129.9373647185443


201it [00:58,  3.45it/s]

Epoch 0, Batch 200, Loss: 35630.8359375 RMSE(mm): 94.38066001239343


236it [01:08,  3.44it/s]


Epoch 0, Val Loss: 30163.380899234693, RMSE(mm): 86.83804019442559
Epoch 0, test Loss: 30391.48207720588, RMSE(mm): 87.16576460572963


1it [00:00,  3.46it/s]

Epoch 1, Batch 0, Loss: 29068.01171875 RMSE(mm): 85.24671799950717


101it [00:29,  3.48it/s]

Epoch 1, Batch 100, Loss: 28118.697265625 RMSE(mm): 83.84315306813222


201it [00:57,  3.47it/s]

Epoch 1, Batch 200, Loss: 32092.466796875 RMSE(mm): 89.57185215913954


236it [01:07,  3.48it/s]


Epoch 1, Val Loss: 23972.7421875, RMSE(mm): 77.41566732177021
Epoch 1, test Loss: 23448.02730545343, RMSE(mm): 76.56374354982492


1it [00:00,  3.47it/s]

Epoch 2, Batch 0, Loss: 22068.3984375 RMSE(mm): 74.27718094660702


101it [00:29,  3.49it/s]

Epoch 2, Batch 100, Loss: 24477.4140625 RMSE(mm): 78.2262968292952


201it [00:58,  3.47it/s]

Epoch 2, Batch 200, Loss: 26516.21875 RMSE(mm): 81.41900691791813


236it [01:08,  3.46it/s]


Epoch 2, Val Loss: 21458.534797512755, RMSE(mm): 73.24365978962403
Epoch 2, test Loss: 20935.11017922794, RMSE(mm): 72.34485154319542


1it [00:00,  3.49it/s]

Epoch 3, Batch 0, Loss: 18951.9453125 RMSE(mm): 68.83303224560865


101it [00:29,  3.45it/s]

Epoch 3, Batch 100, Loss: 19897.4375 RMSE(mm): 70.5291384819069


201it [00:57,  3.54it/s]

Epoch 3, Batch 200, Loss: 23168.4296875 RMSE(mm): 76.10589610453975


236it [01:07,  3.48it/s]


Epoch 3, Val Loss: 17581.892737563776, RMSE(mm): 66.29836486966285
Epoch 3, test Loss: 15813.059110753677, RMSE(mm): 62.87499326193538


1it [00:00,  3.51it/s]

Epoch 4, Batch 0, Loss: 14902.2919921875 RMSE(mm): 61.0374720810657


101it [00:29,  3.45it/s]

Epoch 4, Batch 100, Loss: 15652.8818359375 RMSE(mm): 62.555738817348924


201it [00:58,  3.47it/s]

Epoch 4, Batch 200, Loss: 19848.169921875 RMSE(mm): 70.44176659105555


236it [01:08,  3.46it/s]


Epoch 4, Val Loss: 16087.498485331633, RMSE(mm): 63.4182514843551
Epoch 4, test Loss: 13672.853726256128, RMSE(mm): 58.46548923565108


1it [00:00,  3.46it/s]

Epoch 5, Batch 0, Loss: 12124.095703125 RMSE(mm): 55.05473572528752


101it [00:29,  3.48it/s]

Epoch 5, Batch 100, Loss: 13859.61328125 RMSE(mm): 58.86342939646398


201it [00:57,  3.48it/s]

Epoch 5, Batch 200, Loss: 16441.671875 RMSE(mm): 64.1125414310648


236it [01:07,  3.47it/s]


Epoch 5, Val Loss: 15946.015784438776, RMSE(mm): 63.138767378764165
Epoch 5, test Loss: 13436.884172028187, RMSE(mm): 57.95878745287074


1it [00:00,  3.49it/s]

Epoch 6, Batch 0, Loss: 10546.66015625 RMSE(mm): 51.348466764476036


101it [00:29,  3.46it/s]

Epoch 6, Batch 100, Loss: 11789.1044921875 RMSE(mm): 54.28882134516161


201it [00:58,  3.46it/s]

Epoch 6, Batch 200, Loss: 15955.96875 RMSE(mm): 63.15846885018667


236it [01:08,  3.47it/s]


Epoch 6, Val Loss: 15322.617984693878, RMSE(mm): 61.89228139415665
Epoch 6, test Loss: 13075.508118872549, RMSE(mm): 57.174094043702496


1it [00:00,  3.48it/s]

Epoch 7, Batch 0, Loss: 11289.65625 RMSE(mm): 53.12639704045438


101it [00:29,  3.47it/s]

Epoch 7, Batch 100, Loss: 11457.72265625 RMSE(mm): 53.520376157707446


201it [00:58,  3.51it/s]

Epoch 7, Batch 200, Loss: 15297.66796875 RMSE(mm): 61.84187086584218


236it [01:08,  3.47it/s]


Epoch 7, Val Loss: 15239.799465880102, RMSE(mm): 61.724791344078476
Epoch 7, test Loss: 12872.27330346201, RMSE(mm): 56.728020641174346


1it [00:00,  3.43it/s]

Epoch 8, Batch 0, Loss: 10810.79296875 RMSE(mm): 51.987481591124414


101it [00:29,  3.46it/s]

Epoch 8, Batch 100, Loss: 11134.67578125 RMSE(mm): 52.76048659093754


201it [00:57,  3.52it/s]

Epoch 8, Batch 200, Loss: 14297.052734375 RMSE(mm): 59.78514182966994


236it [01:08,  3.47it/s]


Epoch 8, Val Loss: 15184.189074457909, RMSE(mm): 61.612070802842496
Epoch 8, test Loss: 12765.097005208334, RMSE(mm): 56.491364395826764


1it [00:00,  3.45it/s]

Epoch 9, Batch 0, Loss: 10253.732421875 RMSE(mm): 50.63035754830051


101it [00:29,  3.44it/s]

Epoch 9, Batch 100, Loss: 10625.927734375 RMSE(mm): 51.54107035747075


201it [00:58,  3.44it/s]

Epoch 9, Batch 200, Loss: 13585.1748046875 RMSE(mm): 58.27772903238316


236it [01:08,  3.46it/s]


Epoch 9, Val Loss: 15149.268634406888, RMSE(mm): 61.541182622709826
Epoch 9, test Loss: 12700.445695465687, RMSE(mm): 56.34812706618049


1it [00:00,  3.46it/s]

Epoch 10, Batch 0, Loss: 10005.76171875 RMSE(mm): 50.01440222263483


101it [00:29,  3.46it/s]

Epoch 10, Batch 100, Loss: 10364.8662109375 RMSE(mm): 50.90399348513213


201it [00:58,  3.47it/s]

Epoch 10, Batch 200, Loss: 12801.4208984375 RMSE(mm): 56.571682179420606


236it [01:08,  3.46it/s]


Epoch 10, Val Loss: 15159.617346938776, RMSE(mm): 61.56219892705827
Epoch 10, test Loss: 12661.26114430147, RMSE(mm): 56.261134774152644


1it [00:00,  3.50it/s]

Epoch 11, Batch 0, Loss: 9752.3017578125 RMSE(mm): 49.37687150329722


101it [00:29,  3.52it/s]

Epoch 11, Batch 100, Loss: 10185.28125 RMSE(mm): 50.46107720312756


201it [00:57,  3.51it/s]

Epoch 11, Batch 200, Loss: 12015.353515625 RMSE(mm): 54.80728399497872


236it [01:07,  3.49it/s]


Epoch 11, Val Loss: 15194.842893016581, RMSE(mm): 61.633681727235356
Epoch 11, test Loss: 12652.869734221813, RMSE(mm): 56.24248779664226


1it [00:00,  3.53it/s]

Epoch 12, Batch 0, Loss: 9234.5595703125 RMSE(mm): 48.048307905462444


101it [00:28,  3.53it/s]

Epoch 12, Batch 100, Loss: 10467.9921875 RMSE(mm): 51.15660316005159


201it [00:57,  3.52it/s]

Epoch 12, Batch 200, Loss: 10577.05078125 RMSE(mm): 51.4223948811459


236it [01:06,  3.53it/s]


Epoch 12, Val Loss: 14919.777403539541, RMSE(mm): 61.07327034705842
Epoch 12, test Loss: 12294.923885569853, RMSE(mm): 55.44123890564192


1it [00:00,  3.49it/s]

Epoch 13, Batch 0, Loss: 9395.9521484375 RMSE(mm): 48.46635984999673


101it [00:29,  3.42it/s]

Epoch 13, Batch 100, Loss: 10604.2265625 RMSE(mm): 51.488412683097934


201it [00:58,  3.44it/s]

Epoch 13, Batch 200, Loss: 10311.875 RMSE(mm): 50.77370136202402


236it [01:08,  3.45it/s]


Epoch 13, Val Loss: 14883.916454081633, RMSE(mm): 60.99982879910736
Epoch 13, test Loss: 12245.815391390932, RMSE(mm): 55.33040617822838


1it [00:00,  3.47it/s]

Epoch 14, Batch 0, Loss: 9409.255859375 RMSE(mm): 48.50065942689594


101it [00:29,  3.44it/s]

Epoch 14, Batch 100, Loss: 10524.40234375 RMSE(mm): 51.29425490186498


201it [00:58,  3.43it/s]

Epoch 14, Batch 200, Loss: 10438.9296875 RMSE(mm): 51.08554024256766


236it [01:08,  3.46it/s]


Epoch 14, Val Loss: 14881.551737882653, RMSE(mm): 60.994982863106564
Epoch 14, test Loss: 12233.354540058212, RMSE(mm): 55.3022480104973


In [2]:
from models.EEGViT_pretrained_large_16stride import EEGViT_pretrained
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained()
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')

batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-large-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 1024]) in the checkpoint and torch.Size([1, 113, 1024]) in the model instantiated
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([1024, 3, 16, 16]) in the checkpoint and torch.Size([1024, 256, 16, 1]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
create dataloader...
HI
training...


1it [00:00,  1.69it/s]

Epoch 0, Batch 0, Loss: 168812.6875 RMSE(mm): 205.43410591963547


101it [00:43,  2.33it/s]

Epoch 0, Batch 100, Loss: 55871.546875 RMSE(mm): 118.18581437190336


201it [01:26,  2.33it/s]

Epoch 0, Batch 200, Loss: 33399.70703125 RMSE(mm): 91.37793364818718


236it [01:41,  2.32it/s]


Epoch 0, Val Loss: 26171.514030612245, RMSE(mm): 80.88806158916816
Epoch 0, test Loss: 26245.664636948528, RMSE(mm): 81.00256884344553


1it [00:00,  2.31it/s]

Epoch 1, Batch 0, Loss: 24563.53515625 RMSE(mm): 78.36379131373431


101it [00:43,  2.33it/s]

Epoch 1, Batch 100, Loss: 25196.73046875 RMSE(mm): 79.36739013718103


201it [01:26,  2.33it/s]

Epoch 1, Batch 200, Loss: 29005.78125 RMSE(mm): 85.15541857392282


236it [01:41,  2.33it/s]


Epoch 1, Val Loss: 22191.81393494898, RMSE(mm): 74.48458554450878
Epoch 1, test Loss: 21762.909926470587, RMSE(mm): 73.76128714724037


1it [00:00,  2.33it/s]

Epoch 2, Batch 0, Loss: 21076.888671875 RMSE(mm): 72.58940809766085


101it [00:43,  2.34it/s]

Epoch 2, Batch 100, Loss: 21341.765625 RMSE(mm): 73.04410589671147


201it [01:26,  2.33it/s]

Epoch 2, Batch 200, Loss: 21964.46875 RMSE(mm): 74.10207276115831


236it [01:41,  2.33it/s]


Epoch 2, Val Loss: 17278.576331313776, RMSE(mm): 65.72399929119076
Epoch 2, test Loss: 16228.547411151962, RMSE(mm): 63.695658037169146


1it [00:00,  2.31it/s]

Epoch 3, Batch 0, Loss: 15714.734375 RMSE(mm): 62.67921181500291


101it [00:43,  2.33it/s]

Epoch 3, Batch 100, Loss: 15883.0185546875 RMSE(mm): 63.01392416499606


201it [01:26,  2.35it/s]

Epoch 3, Batch 200, Loss: 19922.65234375 RMSE(mm): 70.57381303243788


236it [01:41,  2.33it/s]


Epoch 3, Val Loss: 15819.16822783801, RMSE(mm): 62.887137452419495
Epoch 3, test Loss: 13624.854051776962, RMSE(mm): 58.36277506205681


1it [00:00,  2.33it/s]

Epoch 4, Batch 0, Loss: 13583.0322265625 RMSE(mm): 58.273133231710005


101it [00:43,  2.32it/s]

Epoch 4, Batch 100, Loss: 14139.6484375 RMSE(mm): 59.45512685525951


201it [01:26,  2.46it/s]

Epoch 4, Batch 200, Loss: 18566.40625 RMSE(mm): 68.12930032298878


236it [01:40,  2.35it/s]


Epoch 4, Val Loss: 16178.977240114797, RMSE(mm): 63.5983043015197
Epoch 4, test Loss: 13956.121725643383, RMSE(mm): 59.06801529940587


1it [00:00,  2.47it/s]

Epoch 5, Batch 0, Loss: 12491.6201171875 RMSE(mm): 55.8829583083866


101it [00:41,  2.48it/s]

Epoch 5, Batch 100, Loss: 13583.564453125 RMSE(mm): 58.27427488421671


201it [01:23,  2.33it/s]

Epoch 5, Batch 200, Loss: 17145.5234375 RMSE(mm): 65.4704579132833


236it [01:38,  2.40it/s]


Epoch 5, Val Loss: 16186.619100765307, RMSE(mm): 63.61332230902051
Epoch 5, test Loss: 13892.048502604166, RMSE(mm): 58.93226727057972


1it [00:00,  2.30it/s]

Epoch 6, Batch 0, Loss: 11777.6796875 RMSE(mm): 54.262509358441946


101it [00:43,  2.33it/s]

Epoch 6, Batch 100, Loss: 13443.6171875 RMSE(mm): 57.97330676160365


201it [01:26,  2.34it/s]

Epoch 6, Batch 200, Loss: 14595.595703125 RMSE(mm): 60.40611662556409


236it [01:41,  2.33it/s]


Epoch 6, Val Loss: 15007.899613360969, RMSE(mm): 61.253366465364515
Epoch 6, test Loss: 12711.2490234375, RMSE(mm): 56.3720875598853


1it [00:00,  2.31it/s]

Epoch 7, Batch 0, Loss: 10671.5400390625 RMSE(mm): 51.6515731586718


101it [00:43,  2.32it/s]

Epoch 7, Batch 100, Loss: 13179.8720703125 RMSE(mm): 57.4018119712098


201it [01:26,  2.32it/s]

Epoch 7, Batch 200, Loss: 14443.25390625 RMSE(mm): 60.090044737564476


236it [01:41,  2.33it/s]


Epoch 7, Val Loss: 14939.71263153699, RMSE(mm): 61.11405859443674
Epoch 7, test Loss: 12616.69265088848, RMSE(mm): 56.162025984842465


1it [00:00,  2.31it/s]

Epoch 8, Batch 0, Loss: 10255.6865234375 RMSE(mm): 50.63518175003794


101it [00:43,  2.33it/s]

Epoch 8, Batch 100, Loss: 12602.09375 RMSE(mm): 56.12952375978261


201it [01:26,  2.33it/s]

Epoch 8, Batch 200, Loss: 14160.4130859375 RMSE(mm): 59.49876697448759


236it [01:41,  2.33it/s]


Epoch 8, Val Loss: 14908.170798788266, RMSE(mm): 61.04951023306466
Epoch 8, test Loss: 12519.259612438726, RMSE(mm): 55.94474866428199


1it [00:00,  2.32it/s]

Epoch 9, Batch 0, Loss: 9900.90234375 RMSE(mm): 49.75163902764913


101it [00:42,  2.48it/s]

Epoch 9, Batch 100, Loss: 12268.044921875 RMSE(mm): 55.38060337761544


201it [01:22,  2.48it/s]

Epoch 9, Batch 200, Loss: 13761.056640625 RMSE(mm): 58.653765097871165


236it [01:36,  2.44it/s]


Epoch 9, Val Loss: 14926.156827965562, RMSE(mm): 61.086325859322976
Epoch 9, test Loss: 12460.62752757353, RMSE(mm): 55.813590476633756


1it [00:00,  2.48it/s]

Epoch 10, Batch 0, Loss: 9623.587890625 RMSE(mm): 49.04994365599465


101it [00:42,  2.29it/s]

Epoch 10, Batch 100, Loss: 11825.8056640625 RMSE(mm): 54.37326011943394


201it [01:25,  2.33it/s]

Epoch 10, Batch 200, Loss: 13271.630859375 RMSE(mm): 57.601282232635675


236it [01:40,  2.34it/s]


Epoch 10, Val Loss: 14946.8251953125, RMSE(mm): 61.12860458760796
Epoch 10, test Loss: 12409.528167126226, RMSE(mm): 55.69903088727448


1it [00:00,  2.30it/s]

Epoch 11, Batch 0, Loss: 9371.115234375 RMSE(mm): 48.40226036657534


101it [00:43,  2.33it/s]

Epoch 11, Batch 100, Loss: 11124.068359375 RMSE(mm): 52.73534952803243


201it [01:26,  2.33it/s]

Epoch 11, Batch 200, Loss: 12924.4296875 RMSE(mm): 56.84283087492212


236it [01:41,  2.33it/s]


Epoch 11, Val Loss: 14980.787986288266, RMSE(mm): 61.19801464567349
Epoch 11, test Loss: 12363.128982843138, RMSE(mm): 55.59480412512292


1it [00:00,  2.31it/s]

Epoch 12, Batch 0, Loss: 9125.3583984375 RMSE(mm): 47.763370898727146


101it [00:43,  2.32it/s]

Epoch 12, Batch 100, Loss: 12604.115234375 RMSE(mm): 56.1340254087817


201it [01:26,  2.33it/s]

Epoch 12, Batch 200, Loss: 11871.6484375 RMSE(mm): 54.47854723994574


236it [01:41,  2.33it/s]


Epoch 12, Val Loss: 14785.02272002551, RMSE(mm): 60.79683939158661
Epoch 12, test Loss: 12145.703144148285, RMSE(mm): 55.103772883869496


1it [00:00,  2.33it/s]

Epoch 13, Batch 0, Loss: 9372.13671875 RMSE(mm): 48.40489830262533


101it [00:43,  2.33it/s]

Epoch 13, Batch 100, Loss: 12126.302734375 RMSE(mm): 55.05974649046025


201it [01:26,  2.33it/s]

Epoch 13, Batch 200, Loss: 11844.1904296875 RMSE(mm): 54.41550888691454


236it [01:41,  2.33it/s]


Epoch 13, Val Loss: 14751.84107940051, RMSE(mm): 60.72857869117412
Epoch 13, test Loss: 12122.664445465687, RMSE(mm): 55.05148600507003


1it [00:00,  2.31it/s]

Epoch 14, Batch 0, Loss: 9237.6455078125 RMSE(mm): 48.05633545073037


101it [00:43,  2.33it/s]

Epoch 14, Batch 100, Loss: 12142.689453125 RMSE(mm): 55.0969360607398


201it [01:26,  2.33it/s]

Epoch 14, Batch 200, Loss: 11851.1953125 RMSE(mm): 54.431597699543964


236it [01:41,  2.33it/s]


Epoch 14, Val Loss: 14741.602459343112, RMSE(mm): 60.70750048252504
Epoch 14, test Loss: 12113.894780177696, RMSE(mm): 55.03156998527685


In [3]:
from models.EEGViT_pretrained_large_129stride import EEGViT_pretrained
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained()
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-large-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 1024]) in the checkpoint and torch.Size([1, 15, 1024]) in the model instantiated
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([1024, 3, 16, 16]) in the checkpoint and torch.Size([1024, 256, 129, 1]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


2it [00:00,  4.70it/s]

Epoch 0, Batch 0, Loss: 169134.125 RMSE(mm): 205.62959721304713


102it [00:13,  8.04it/s]

Epoch 0, Batch 100, Loss: 55035.7890625 RMSE(mm): 117.29853906006247


202it [00:25,  8.23it/s]

Epoch 0, Batch 200, Loss: 29037.609375 RMSE(mm): 85.20212640392258


236it [00:29,  7.98it/s]


Epoch 0, Val Loss: 25828.255062181124, RMSE(mm): 80.3558570705663
Epoch 0, test Loss: 25953.58252910539, RMSE(mm): 80.55057810019956


1it [00:00,  8.30it/s]

Epoch 1, Batch 0, Loss: 24452.119140625 RMSE(mm): 78.18586691439988


102it [00:12,  8.18it/s]

Epoch 1, Batch 100, Loss: 26139.556640625 RMSE(mm): 80.83866129616602


202it [00:24,  8.13it/s]

Epoch 1, Batch 200, Loss: 25886.20703125 RMSE(mm): 80.44595550935112


236it [00:28,  8.19it/s]


Epoch 1, Val Loss: 22020.20651307398, RMSE(mm): 74.19603512498828
Epoch 1, test Loss: 21674.984145220587, RMSE(mm): 73.61213239884542


1it [00:00,  8.32it/s]

Epoch 2, Batch 0, Loss: 20615.0 RMSE(mm): 71.78962320558591


102it [00:12,  8.17it/s]

Epoch 2, Batch 100, Loss: 21475.7109375 RMSE(mm): 73.27296728245008


202it [00:25,  8.08it/s]

Epoch 2, Batch 200, Loss: 22042.224609375 RMSE(mm): 74.23312031932748


236it [00:29,  8.04it/s]


Epoch 2, Val Loss: 16846.70378268495, RMSE(mm): 64.89742634088995
Epoch 2, test Loss: 15296.927830116421, RMSE(mm): 61.84037481717834


1it [00:00,  8.14it/s]

Epoch 3, Batch 0, Loss: 15570.0986328125 RMSE(mm): 62.39010064267508


102it [00:12,  8.11it/s]

Epoch 3, Batch 100, Loss: 15154.638671875 RMSE(mm): 61.552089062587875


202it [00:24,  8.10it/s]

Epoch 3, Batch 200, Loss: 19938.484375 RMSE(mm): 70.60184908166357


236it [00:29,  8.12it/s]


Epoch 3, Val Loss: 15037.29830994898, RMSE(mm): 61.31333115634189
Epoch 3, test Loss: 12762.288181678921, RMSE(mm): 56.48514889260478


1it [00:00,  8.20it/s]

Epoch 4, Batch 0, Loss: 13843.1083984375 RMSE(mm): 58.8283698534081


102it [00:12,  8.26it/s]

Epoch 4, Batch 100, Loss: 13749.859375 RMSE(mm): 58.62989718351892


202it [00:24,  8.09it/s]

Epoch 4, Batch 200, Loss: 19664.0625 RMSE(mm): 70.11430399711602


236it [00:28,  8.16it/s]


Epoch 4, Val Loss: 15472.336156728315, RMSE(mm): 62.19392284767121
Epoch 4, test Loss: 12815.651003370098, RMSE(mm): 56.603116087743125


1it [00:00,  8.28it/s]

Epoch 5, Batch 0, Loss: 13195.005859375 RMSE(mm): 57.43475833364105


102it [00:12,  8.13it/s]

Epoch 5, Batch 100, Loss: 12316.138671875 RMSE(mm): 55.48904998257539


202it [00:24,  8.16it/s]

Epoch 5, Batch 200, Loss: 19178.421875 RMSE(mm): 69.24308968229248


236it [00:28,  8.15it/s]


Epoch 5, Val Loss: 16186.681879783164, RMSE(mm): 63.61344566949499
Epoch 5, test Loss: 13194.255897671568, RMSE(mm): 57.43312610695932


1it [00:00,  7.94it/s]

Epoch 6, Batch 0, Loss: 13169.4423828125 RMSE(mm): 57.37909545908793


102it [00:12,  8.22it/s]

Epoch 6, Batch 100, Loss: 13696.154296875 RMSE(mm): 58.51528496229639


202it [00:24,  8.18it/s]

Epoch 6, Batch 200, Loss: 13849.537109375 RMSE(mm): 58.8420281545746


236it [00:28,  8.16it/s]


Epoch 6, Val Loss: 14766.677614795919, RMSE(mm): 60.75910963550223
Epoch 6, test Loss: 11940.426738664215, RMSE(mm): 54.636129847071466


1it [00:00,  8.24it/s]

Epoch 7, Batch 0, Loss: 12214.3720703125 RMSE(mm): 55.25932516397685


102it [00:12,  8.14it/s]

Epoch 7, Batch 100, Loss: 14013.021484375 RMSE(mm): 59.1883043437954


202it [00:24,  8.12it/s]

Epoch 7, Batch 200, Loss: 14194.2080078125 RMSE(mm): 59.569723870042615


236it [00:29,  8.11it/s]


Epoch 7, Val Loss: 14810.360361527424, RMSE(mm): 60.848911990123995
Epoch 7, test Loss: 11877.885589001226, RMSE(mm): 54.49285638733123


1it [00:00,  8.07it/s]

Epoch 8, Batch 0, Loss: 12216.349609375 RMSE(mm): 55.263798298196534


102it [00:12,  8.16it/s]

Epoch 8, Batch 100, Loss: 13902.287109375 RMSE(mm): 58.95398016541165


202it [00:24,  8.09it/s]

Epoch 8, Batch 200, Loss: 14096.7470703125 RMSE(mm): 59.36486138767718


236it [00:29,  8.12it/s]


Epoch 8, Val Loss: 14870.178591358419, RMSE(mm): 60.97167086311154
Epoch 8, test Loss: 11845.147480085785, RMSE(mm): 54.41770732051697


1it [00:00,  8.18it/s]

Epoch 9, Batch 0, Loss: 11841.515625 RMSE(mm): 54.40936414120275


102it [00:12,  7.99it/s]

Epoch 9, Batch 100, Loss: 13707.484375 RMSE(mm): 58.539483203646405


202it [00:25,  8.14it/s]

Epoch 9, Batch 200, Loss: 13843.1484375 RMSE(mm): 58.828454929353704


236it [00:29,  8.06it/s]


Epoch 9, Val Loss: 14880.186344068878, RMSE(mm): 60.99218463063296
Epoch 9, test Loss: 11778.676461014093, RMSE(mm): 54.26480549355653


1it [00:00,  8.17it/s]

Epoch 10, Batch 0, Loss: 11933.619140625 RMSE(mm): 54.620552772342485


102it [00:12,  8.17it/s]

Epoch 10, Batch 100, Loss: 13658.5751953125 RMSE(mm): 58.434953570856244


202it [00:24,  8.19it/s]

Epoch 10, Batch 200, Loss: 13835.44921875 RMSE(mm): 58.81209318403401


236it [00:29,  8.12it/s]


Epoch 10, Val Loss: 14918.29225127551, RMSE(mm): 61.07023057774449
Epoch 10, test Loss: 11740.915594362745, RMSE(mm): 54.177752801225395


1it [00:00,  8.21it/s]

Epoch 11, Batch 0, Loss: 11735.654296875 RMSE(mm): 54.16561246970951


102it [00:12,  8.18it/s]

Epoch 11, Batch 100, Loss: 13601.5556640625 RMSE(mm): 58.312853780411274


202it [00:24,  8.08it/s]

Epoch 11, Batch 200, Loss: 13293.0859375 RMSE(mm): 57.64782289362713


236it [00:29,  8.13it/s]


Epoch 11, Val Loss: 14917.508669483419, RMSE(mm): 61.06862670284026
Epoch 11, test Loss: 11664.747702205883, RMSE(mm): 54.001730764406716


1it [00:00,  8.24it/s]

Epoch 12, Batch 0, Loss: 11813.205078125 RMSE(mm): 54.344284607778675


102it [00:12,  8.15it/s]

Epoch 12, Batch 100, Loss: 13713.1630859375 RMSE(mm): 58.551607761737635


202it [00:24,  8.12it/s]

Epoch 12, Batch 200, Loss: 13446.0185546875 RMSE(mm): 57.9784842736672


236it [00:29,  8.09it/s]


Epoch 12, Val Loss: 14547.125019929847, RMSE(mm): 60.30573152679985
Epoch 12, test Loss: 11179.514523973652, RMSE(mm): 52.86661168444043


1it [00:00,  8.09it/s]

Epoch 13, Batch 0, Loss: 11595.6689453125 RMSE(mm): 53.841593924475575


102it [00:12,  8.14it/s]

Epoch 13, Batch 100, Loss: 13486.6474609375 RMSE(mm): 58.066012995851324


202it [00:24,  8.11it/s]

Epoch 13, Batch 200, Loss: 13465.849609375 RMSE(mm): 58.02122372325277


236it [00:29,  8.12it/s]


Epoch 13, Val Loss: 14502.108488121812, RMSE(mm): 60.2123502450324
Epoch 13, test Loss: 11122.658949908087, RMSE(mm): 52.73200866150484


1it [00:00,  7.97it/s]

Epoch 14, Batch 0, Loss: 11722.0810546875 RMSE(mm): 54.13427993122172


102it [00:12,  8.12it/s]

Epoch 14, Batch 100, Loss: 13620.21875 RMSE(mm): 58.352846438712824


202it [00:24,  8.19it/s]

Epoch 14, Batch 200, Loss: 13530.923828125 RMSE(mm): 58.161249617174235


236it [00:29,  8.13it/s]


Epoch 14, Val Loss: 14489.392578125, RMSE(mm): 60.18594640388444
Epoch 14, test Loss: 11100.133817784927, RMSE(mm): 52.678586298858015


In [5]:
from models.EEGVit_pretrained_129stride import EEGViT_pretrained
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained()
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 129, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 33, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


2it [00:00,  5.97it/s]

Epoch 0, Batch 0, Loss: 169209.65625 RMSE(mm): 205.67550671506805


103it [00:10,  9.72it/s]

Epoch 0, Batch 100, Loss: 66471.796875 RMSE(mm): 128.9106249257601


202it [00:21,  9.69it/s]

Epoch 0, Batch 200, Loss: 32945.765625 RMSE(mm): 90.75484232948675


236it [00:24,  9.63it/s]


Epoch 0, Val Loss: 26505.066485969386, RMSE(mm): 81.40188340261143
Epoch 0, test Loss: 26794.276922487745, RMSE(mm): 81.8447874370869


2it [00:00,  9.74it/s]

Epoch 1, Batch 0, Loss: 24906.607421875 RMSE(mm): 78.90913670462217


102it [00:10,  9.85it/s]

Epoch 1, Batch 100, Loss: 25761.875 RMSE(mm): 80.25253111273189


203it [00:20,  9.88it/s]

Epoch 1, Batch 200, Loss: 27765.81640625 RMSE(mm): 83.31538934412117


236it [00:23,  9.84it/s]


Epoch 1, Val Loss: 22384.87428252551, RMSE(mm): 74.80787773110114
Epoch 1, test Loss: 22031.836894914217, RMSE(mm): 74.21562654676273


2it [00:00,  9.98it/s]

Epoch 2, Batch 0, Loss: 21701.56640625 RMSE(mm): 73.65725762993421


103it [00:10,  9.68it/s]

Epoch 2, Batch 100, Loss: 20668.462890625 RMSE(mm): 71.88265244588746


202it [00:20,  9.87it/s]

Epoch 2, Batch 200, Loss: 21188.21875 RMSE(mm): 72.78086759238309


236it [00:24,  9.72it/s]


Epoch 2, Val Loss: 17160.15898038903, RMSE(mm): 65.49839498107765
Epoch 2, test Loss: 15898.565448835785, RMSE(mm): 63.04475681774771


1it [00:00,  9.67it/s]

Epoch 3, Batch 0, Loss: 16954.53515625 RMSE(mm): 65.10479083034136


102it [00:10,  9.52it/s]

Epoch 3, Batch 100, Loss: 15677.134765625 RMSE(mm): 62.60418269897188


202it [00:20,  9.59it/s]

Epoch 3, Batch 200, Loss: 19016.6796875 RMSE(mm): 68.950488916867


236it [00:24,  9.65it/s]


Epoch 3, Val Loss: 15287.147122130102, RMSE(mm): 61.82060158662746
Epoch 3, test Loss: 12862.191119025736, RMSE(mm): 56.7058002302801


1it [00:00,  9.81it/s]

Epoch 4, Batch 0, Loss: 13602.89453125 RMSE(mm): 58.31572371850066


103it [00:10,  9.75it/s]

Epoch 4, Batch 100, Loss: 12621.1708984375 RMSE(mm): 56.17199235036421


202it [00:20,  9.72it/s]

Epoch 4, Batch 200, Loss: 18314.33984375 RMSE(mm): 67.66524189668947


236it [00:24,  9.73it/s]


Epoch 4, Val Loss: 15286.353675063776, RMSE(mm): 61.818997231967
Epoch 4, test Loss: 12670.62917432598, RMSE(mm): 56.281944649962966


2it [00:00,  9.75it/s]

Epoch 5, Batch 0, Loss: 12197.92578125 RMSE(mm): 55.22211011282075


102it [00:10,  9.91it/s]

Epoch 5, Batch 100, Loss: 11073.1669921875 RMSE(mm): 52.61455832796542


202it [00:20,  9.81it/s]

Epoch 5, Batch 200, Loss: 17374.17578125 RMSE(mm): 65.9055683938201


236it [00:23,  9.84it/s]


Epoch 5, Val Loss: 15591.278419961734, RMSE(mm): 62.43252041196506
Epoch 5, test Loss: 12893.32825903799, RMSE(mm): 56.77439620779333


1it [00:00,  9.91it/s]

Epoch 6, Batch 0, Loss: 11867.810546875 RMSE(mm): 54.46974056041345


102it [00:10,  9.86it/s]

Epoch 6, Batch 100, Loss: 12989.712890625 RMSE(mm): 56.986210811530974


202it [00:20,  9.71it/s]

Epoch 6, Batch 200, Loss: 13536.1640625 RMSE(mm): 58.17251082448651


236it [00:24,  9.83it/s]


Epoch 6, Val Loss: 14504.360829878826, RMSE(mm): 60.21702589359347
Epoch 6, test Loss: 11773.598785998774, RMSE(mm): 54.253107712827784


1it [00:00,  9.92it/s]

Epoch 7, Batch 0, Loss: 10061.412109375 RMSE(mm): 50.15329527901183


102it [00:10,  9.67it/s]

Epoch 7, Batch 100, Loss: 12693.837890625 RMSE(mm): 56.33346671967073


203it [00:20,  9.67it/s]

Epoch 7, Batch 200, Loss: 12945.595703125 RMSE(mm): 56.8893568761438


236it [00:24,  9.73it/s]


Epoch 7, Val Loss: 14566.239785953443, RMSE(mm): 60.345339061839404
Epoch 7, test Loss: 11647.355286841299, RMSE(mm): 53.961456816049036


1it [00:00,  9.92it/s]

Epoch 8, Batch 0, Loss: 10190.9375 RMSE(mm): 50.47508667649814


103it [00:10,  9.66it/s]

Epoch 8, Batch 100, Loss: 12570.8173828125 RMSE(mm): 56.05982827036777


202it [00:20,  9.71it/s]

Epoch 8, Batch 200, Loss: 13135.91015625 RMSE(mm): 57.3059991542116


236it [00:24,  9.72it/s]


Epoch 8, Val Loss: 14725.876863440688, RMSE(mm): 60.67511199709624
Epoch 8, test Loss: 11535.471717984068, RMSE(mm): 53.7016566736634


0it [00:00, ?it/s]

Epoch 9, Batch 0, Loss: 9929.70703125 RMSE(mm): 49.82395766910232


102it [00:10,  9.67it/s]

Epoch 9, Batch 100, Loss: 12226.0712890625 RMSE(mm): 55.28578318397619


203it [00:20,  9.89it/s]

Epoch 9, Batch 200, Loss: 12699.7861328125 RMSE(mm): 56.34666390482337


236it [00:23,  9.86it/s]


Epoch 9, Val Loss: 14878.390027104591, RMSE(mm): 60.988503070465235
Epoch 9, test Loss: 11517.170505897671, RMSE(mm): 53.659040491555736


2it [00:00,  9.85it/s]

Epoch 10, Batch 0, Loss: 9460.8671875 RMSE(mm): 48.63349459863027


103it [00:10,  9.80it/s]

Epoch 10, Batch 100, Loss: 12115.90625 RMSE(mm): 55.036138695406315


202it [00:20,  9.80it/s]

Epoch 10, Batch 200, Loss: 12690.9140625 RMSE(mm): 56.32697857709927


236it [00:23,  9.85it/s]


Epoch 10, Val Loss: 15000.234016262755, RMSE(mm): 61.237721251412424
Epoch 10, test Loss: 11574.670563342524, RMSE(mm): 53.792821461935155


1it [00:00,  9.75it/s]

Epoch 11, Batch 0, Loss: 8825.8955078125 RMSE(mm): 46.97311866326447


102it [00:10,  9.79it/s]

Epoch 11, Batch 100, Loss: 11638.744140625 RMSE(mm): 53.94150568121222


202it [00:20,  9.84it/s]

Epoch 11, Batch 200, Loss: 12312.9189453125 RMSE(mm): 55.48179644106817


236it [00:23,  9.86it/s]


Epoch 11, Val Loss: 15274.788913026148, RMSE(mm): 61.79560848682159
Epoch 11, test Loss: 11648.225404028799, RMSE(mm): 53.96347237722198


1it [00:00,  9.79it/s]

Epoch 12, Batch 0, Loss: 8317.537109375 RMSE(mm): 45.60026619816764


102it [00:10,  9.85it/s]

Epoch 12, Batch 100, Loss: 11997.3115234375 RMSE(mm): 54.766119826580514


202it [00:20,  9.63it/s]

Epoch 12, Batch 200, Loss: 11967.177734375 RMSE(mm): 54.697298229380124


236it [00:24,  9.70it/s]


Epoch 12, Val Loss: 14909.820890465562, RMSE(mm): 61.05288873277325
Epoch 12, test Loss: 11169.506338082108, RMSE(mm): 52.84294261791755


0it [00:00, ?it/s]

Epoch 13, Batch 0, Loss: 8248.880859375 RMSE(mm): 45.41167487380035


101it [00:10,  9.81it/s]

Epoch 13, Batch 100, Loss: 11862.4609375 RMSE(mm): 54.45746261418172


202it [00:20,  9.79it/s]

Epoch 13, Batch 200, Loss: 12053.26171875 RMSE(mm): 54.89367385853765


236it [00:24,  9.79it/s]


Epoch 13, Val Loss: 14909.459721779336, RMSE(mm): 61.0521492696599
Epoch 13, test Loss: 11137.306640625, RMSE(mm): 52.76671924761146


2it [00:00,  9.76it/s]

Epoch 14, Batch 0, Loss: 8274.46484375 RMSE(mm): 45.4820427304832


102it [00:10,  9.81it/s]

Epoch 14, Batch 100, Loss: 11696.1142578125 RMSE(mm): 54.074287461353805


202it [00:20,  9.73it/s]

Epoch 14, Batch 200, Loss: 12137.4814453125 RMSE(mm): 55.085119236760534


236it [00:24,  9.81it/s]


Epoch 14, Val Loss: 14936.971490353953, RMSE(mm): 61.10845172796058
Epoch 14, test Loss: 11128.252623314951, RMSE(mm): 52.745266667528924
