In [5]:
from models.EEGViT_pretrained import EEGViT_pretrained
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained()
EEGEyeNet = EEGEyeNetDataset('./dataset/MTL_data/Position_task_with_dots_synchronized_min.npz')

batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 225, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...
[[1.0 408.1 315.1]
 [1.0 640.7 519.1]
 [1.0 404.2 118.8]
 ...
 [22.0 115.5 306.1]
 [22.0 732.0 310.3]
 [22.0 632.2 353.6]]
create dataloader...
HI
training...


1it [00:00,  1.32it/s]

Epoch 0, Batch 0, Loss: 168895.0 RMSE(mm): 205.48418430623803


101it [00:33,  3.11it/s]

Epoch 0, Batch 100, Loss: 66847.453125 RMSE(mm): 129.27437209768223


201it [01:02,  3.46it/s]

Epoch 0, Batch 200, Loss: 32269.1640625 RMSE(mm): 89.81809959927342


236it [01:11,  3.28it/s]


Epoch 0, Val Loss: 27853.74928252551, RMSE(mm): 83.44721277928566
Epoch 0, test Loss: 28099.197725183825, RMSE(mm): 83.81407657008431


1it [00:00,  3.62it/s]

Epoch 1, Batch 0, Loss: 25495.20703125 RMSE(mm): 79.836093077082


101it [00:28,  3.57it/s]

Epoch 1, Batch 100, Loss: 27023.22265625 RMSE(mm): 82.19370817807467


201it [00:56,  3.58it/s]

Epoch 1, Batch 200, Loss: 29515.26953125 RMSE(mm): 85.90004297328669


236it [01:05,  3.58it/s]


Epoch 1, Val Loss: 23517.238520408162, RMSE(mm): 76.67665635708198
Epoch 1, test Loss: 22982.929457720587, RMSE(mm): 75.80060926160256


1it [00:00,  3.59it/s]

Epoch 2, Batch 0, Loss: 22178.080078125 RMSE(mm): 74.46153382472893


101it [00:28,  3.58it/s]

Epoch 2, Batch 100, Loss: 24109.955078125 RMSE(mm): 77.63690339993765


201it [00:56,  3.58it/s]

Epoch 2, Batch 200, Loss: 22800.5625 RMSE(mm): 75.49927565877702


236it [01:05,  3.59it/s]


Epoch 2, Val Loss: 19172.89387356505, RMSE(mm): 69.23310962531774
Epoch 2, test Loss: 18141.112515318626, RMSE(mm): 67.34447363243443


1it [00:00,  3.62it/s]

Epoch 3, Batch 0, Loss: 17609.828125 RMSE(mm): 66.35101379217954


101it [00:28,  3.59it/s]

Epoch 3, Batch 100, Loss: 16224.908203125 RMSE(mm): 63.68851584690328


201it [00:56,  3.54it/s]

Epoch 3, Batch 200, Loss: 21350.8359375 RMSE(mm): 73.05962622663081


236it [01:05,  3.59it/s]


Epoch 3, Val Loss: 16048.56810028699, RMSE(mm): 63.34147160487943
Epoch 3, test Loss: 13891.984719669117, RMSE(mm): 58.93213198177442


1it [00:00,  3.62it/s]

Epoch 4, Batch 0, Loss: 13363.283203125 RMSE(mm): 57.799833916554206


101it [00:28,  3.59it/s]

Epoch 4, Batch 100, Loss: 12835.0576171875 RMSE(mm): 56.64595664561483


201it [00:56,  3.57it/s]

Epoch 4, Batch 200, Loss: 17201.47265625 RMSE(mm): 65.5771924075932


236it [01:05,  3.59it/s]


Epoch 4, Val Loss: 15441.659060108419, RMSE(mm): 62.13223611803381
Epoch 4, test Loss: 12957.757199754902, RMSE(mm): 56.91607242193303


1it [00:00,  3.64it/s]

Epoch 5, Batch 0, Loss: 11923.958984375 RMSE(mm): 54.59844087603372


101it [00:28,  3.59it/s]

Epoch 5, Batch 100, Loss: 10147.4921875 RMSE(mm): 50.36738078235754


201it [00:56,  3.57it/s]

Epoch 5, Batch 200, Loss: 15737.0537109375 RMSE(mm): 62.72370706307444


236it [01:05,  3.59it/s]


Epoch 5, Val Loss: 15670.264269770409, RMSE(mm): 62.59046307100309
Epoch 5, test Loss: 13050.463264016544, RMSE(mm): 57.11931211074006


1it [00:00,  3.56it/s]

Epoch 6, Batch 0, Loss: 10537.5205078125 RMSE(mm): 51.3262128639268


101it [00:28,  3.59it/s]

Epoch 6, Batch 100, Loss: 11799.677734375 RMSE(mm): 54.31316077705062


201it [00:55,  3.59it/s]

Epoch 6, Batch 200, Loss: 12795.51171875 RMSE(mm): 56.558623831273515


236it [01:05,  3.60it/s]


Epoch 6, Val Loss: 14758.961206552935, RMSE(mm): 60.74323255835364
Epoch 6, test Loss: 12343.91867723652, RMSE(mm): 55.55159466036173


1it [00:00,  3.60it/s]

Epoch 7, Batch 0, Loss: 10855.701171875 RMSE(mm): 52.09534809336387


101it [00:28,  3.60it/s]

Epoch 7, Batch 100, Loss: 11443.400390625 RMSE(mm): 53.48691520041373


201it [00:56,  3.57it/s]

Epoch 7, Batch 200, Loss: 12097.64453125 RMSE(mm): 54.99464640137711


236it [01:05,  3.58it/s]


Epoch 7, Val Loss: 14778.186832350128, RMSE(mm): 60.78278299064244
Epoch 7, test Loss: 12333.13560814951, RMSE(mm): 55.52732572380357


1it [00:00,  3.57it/s]

Epoch 8, Batch 0, Loss: 10422.953125 RMSE(mm): 51.046432600623525


101it [00:28,  3.57it/s]

Epoch 8, Batch 100, Loss: 10642.9072265625 RMSE(mm): 51.58223343982524


201it [00:56,  3.58it/s]

Epoch 8, Batch 200, Loss: 11549.6943359375 RMSE(mm): 53.734752106847715


236it [01:05,  3.59it/s]


Epoch 8, Val Loss: 14790.789869658802, RMSE(mm): 60.80869565625216
Epoch 8, test Loss: 12297.724417892157, RMSE(mm): 55.447552736554925


1it [00:00,  3.73it/s]

Epoch 9, Batch 0, Loss: 9991.439453125 RMSE(mm): 49.97859405066583


101it [00:27,  3.69it/s]

Epoch 9, Batch 100, Loss: 10253.380859375 RMSE(mm): 50.62948957715997


201it [00:54,  3.70it/s]

Epoch 9, Batch 200, Loss: 10701.072265625 RMSE(mm): 51.72299359478577


236it [01:03,  3.71it/s]


Epoch 9, Val Loss: 14861.21470424107, RMSE(mm): 60.95329093707958
Epoch 9, test Loss: 12333.368451286764, RMSE(mm): 55.52784988473524


1it [00:00,  3.75it/s]

Epoch 10, Batch 0, Loss: 9238.046875 RMSE(mm): 48.05737944114306


101it [00:27,  3.71it/s]

Epoch 10, Batch 100, Loss: 9410.357421875 RMSE(mm): 48.50349838381506


201it [00:54,  3.65it/s]

Epoch 10, Batch 200, Loss: 10061.73046875 RMSE(mm): 50.15408873848173


236it [01:03,  3.71it/s]


Epoch 10, Val Loss: 14923.186633051659, RMSE(mm): 61.080247693202054
Epoch 10, test Loss: 12394.50084252451, RMSE(mm): 55.66529628620625


1it [00:00,  3.75it/s]

Epoch 11, Batch 0, Loss: 8591.3837890625 RMSE(mm): 46.34485890868182


101it [00:27,  3.69it/s]

Epoch 11, Batch 100, Loss: 8820.8359375 RMSE(mm): 46.95965272843274


201it [00:54,  3.71it/s]

Epoch 11, Batch 200, Loss: 9290.373046875 RMSE(mm): 48.19329062970021


236it [01:03,  3.71it/s]


Epoch 11, Val Loss: 15063.65090880102, RMSE(mm): 61.36703290204159
Epoch 11, test Loss: 12593.425455729166, RMSE(mm): 56.11021621712299


1it [00:00,  3.75it/s]

Epoch 12, Batch 0, Loss: 7774.0009765625 RMSE(mm): 44.08514765928118


101it [00:27,  3.71it/s]

Epoch 12, Batch 100, Loss: 10197.3515625 RMSE(mm): 50.49096840648831


201it [00:54,  3.71it/s]

Epoch 12, Batch 200, Loss: 8191.7412109375 RMSE(mm): 45.25411917974291


236it [01:03,  3.71it/s]


Epoch 12, Val Loss: 14723.841906489159, RMSE(mm): 60.670919530054015
Epoch 12, test Loss: 11957.440554151348, RMSE(mm): 54.6750412760506


1it [00:00,  3.75it/s]

Epoch 13, Batch 0, Loss: 7781.4609375 RMSE(mm): 44.10629472507297


101it [00:27,  3.70it/s]

Epoch 13, Batch 100, Loss: 9888.28515625 RMSE(mm): 49.71992849011853


201it [00:54,  3.71it/s]

Epoch 13, Batch 200, Loss: 8109.2587890625 RMSE(mm): 45.0257115131524


236it [01:03,  3.72it/s]


Epoch 13, Val Loss: 14755.117526307398, RMSE(mm): 60.73532235509127
Epoch 13, test Loss: 11931.027889476103, RMSE(mm): 54.61462233110311


1it [00:00,  3.73it/s]

Epoch 14, Batch 0, Loss: 7456.7490234375 RMSE(mm): 43.17623485042871


101it [00:27,  3.70it/s]

Epoch 14, Batch 100, Loss: 9666.36328125 RMSE(mm): 49.15883257678624


201it [00:54,  3.71it/s]

Epoch 14, Batch 200, Loss: 8030.42822265625 RMSE(mm): 44.80632829929342


236it [01:03,  3.71it/s]


Epoch 14, Val Loss: 14800.395069355867, RMSE(mm): 60.82843716008958
Epoch 14, test Loss: 11957.564299938726, RMSE(mm): 54.675324187284716
