In [1]:
from models.EEGViT import EEGViT_raw
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_raw()
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')

batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
create dataloader...
HI
training...


1it [00:01,  1.11s/it]

Epoch 0, Batch 0, Loss: 168868.875 RMSE(mm): 205.46829134929797


101it [00:32,  3.27it/s]

Epoch 0, Batch 100, Loss: 69752.78125 RMSE(mm): 132.05375917595077


201it [01:02,  3.24it/s]

Epoch 0, Batch 200, Loss: 35523.65625 RMSE(mm): 94.23860176435132


236it [01:13,  3.21it/s]


Epoch 0, Val Loss: 31743.243502869896, RMSE(mm): 89.08316830758476
Epoch 0, test Loss: 32456.12974877451, RMSE(mm): 90.07792425002714


1it [00:00,  3.30it/s]

Epoch 1, Batch 0, Loss: 30897.53125 RMSE(mm): 87.88846802908786


101it [00:30,  3.29it/s]

Epoch 1, Batch 100, Loss: 26990.89453125 RMSE(mm): 82.14452892805765


201it [01:01,  3.28it/s]

Epoch 1, Batch 200, Loss: 34286.5859375 RMSE(mm): 92.58318683419253


236it [01:12,  3.27it/s]


Epoch 1, Val Loss: 25801.333227040817, RMSE(mm): 80.3139670714889
Epoch 1, test Loss: 25268.355392156864, RMSE(mm): 79.48011605451526


1it [00:00,  3.25it/s]

Epoch 2, Batch 0, Loss: 23278.85546875 RMSE(mm): 76.28704914457958


101it [00:31,  3.21it/s]

Epoch 2, Batch 100, Loss: 25697.04296875 RMSE(mm): 80.15148621321691


201it [01:01,  3.29it/s]

Epoch 2, Batch 200, Loss: 33206.3046875 RMSE(mm): 91.11298574777912


236it [01:12,  3.26it/s]


Epoch 2, Val Loss: 24358.432397959183, RMSE(mm): 78.03594107518532
Epoch 2, test Loss: 23268.901424632353, RMSE(mm): 76.27073722049688


1it [00:00,  3.33it/s]

Epoch 3, Batch 0, Loss: 22494.7890625 RMSE(mm): 74.99131460125899


101it [00:30,  3.19it/s]

Epoch 3, Batch 100, Loss: 25417.041015625 RMSE(mm): 79.7136139809647


201it [01:01,  3.25it/s]

Epoch 3, Batch 200, Loss: 29502.359375 RMSE(mm): 85.88125432101


236it [01:12,  3.24it/s]


Epoch 3, Val Loss: 22678.70479910714, RMSE(mm): 75.29725227242217
Epoch 3, test Loss: 21627.280254289217, RMSE(mm): 73.53108229566803


1it [00:00,  3.22it/s]

Epoch 4, Batch 0, Loss: 20593.9296875 RMSE(mm): 71.75292622517217


101it [00:31,  3.30it/s]

Epoch 4, Batch 100, Loss: 23177.0703125 RMSE(mm): 76.1200865614655


201it [01:03,  3.23it/s]

Epoch 4, Batch 200, Loss: 27368.482421875 RMSE(mm): 82.71711192654607


236it [01:13,  3.19it/s]


Epoch 4, Val Loss: 21999.993981186224, RMSE(mm): 74.16197472624738
Epoch 4, test Loss: 20768.229396446077, RMSE(mm): 72.05593208828486


1it [00:00,  3.24it/s]

Epoch 5, Batch 0, Loss: 20093.77734375 RMSE(mm): 70.8762607361414


101it [00:31,  3.19it/s]

Epoch 5, Batch 100, Loss: 21781.224609375 RMSE(mm): 73.79231770546139


201it [01:02,  3.29it/s]

Epoch 5, Batch 200, Loss: 26082.21875 RMSE(mm): 80.7499516253725


236it [01:13,  3.22it/s]


Epoch 5, Val Loss: 20364.147799744896, RMSE(mm): 71.35150278681049
Epoch 5, test Loss: 18553.58465456495, RMSE(mm): 68.1057718819869


1it [00:00,  3.30it/s]

Epoch 6, Batch 0, Loss: 17990.19921875 RMSE(mm): 67.06377416077551


101it [00:31,  3.24it/s]

Epoch 6, Batch 100, Loss: 19217.984375 RMSE(mm): 69.31447246967981


201it [01:02,  3.21it/s]

Epoch 6, Batch 200, Loss: 21913.28515625 RMSE(mm): 74.01568272374782


236it [01:13,  3.23it/s]


Epoch 6, Val Loss: 19011.652822066328, RMSE(mm): 68.94137513508548
Epoch 6, test Loss: 17278.347139246325, RMSE(mm): 65.72356339100598


1it [00:00,  3.27it/s]

Epoch 7, Batch 0, Loss: 16156.796875 RMSE(mm): 63.554694702673224


101it [00:30,  3.31it/s]

Epoch 7, Batch 100, Loss: 17835.63671875 RMSE(mm): 66.77506405603442


201it [01:01,  3.32it/s]

Epoch 7, Batch 200, Loss: 21189.931640625 RMSE(mm): 72.78380939574576


236it [01:11,  3.28it/s]


Epoch 7, Val Loss: 18663.672612404338, RMSE(mm): 68.30752632837091
Epoch 7, test Loss: 16897.29034543505, RMSE(mm): 64.99478891694905


1it [00:00,  3.22it/s]

Epoch 8, Batch 0, Loss: 15333.9287109375 RMSE(mm): 61.915120751997044


101it [00:31,  3.35it/s]

Epoch 8, Batch 100, Loss: 17792.962890625 RMSE(mm): 66.6951326759026


201it [01:01,  3.34it/s]

Epoch 8, Batch 200, Loss: 21222.734375 RMSE(mm): 72.84012351547737


236it [01:11,  3.28it/s]


Epoch 8, Val Loss: 18466.36686862245, RMSE(mm): 67.94550549635798
Epoch 8, test Loss: 16653.528109681374, RMSE(mm): 64.52427471440762


1it [00:00,  3.29it/s]

Epoch 9, Batch 0, Loss: 15269.1953125 RMSE(mm): 61.78429272982738


101it [00:30,  3.29it/s]

Epoch 9, Batch 100, Loss: 17967.83203125 RMSE(mm): 67.02207104986013


201it [01:01,  3.30it/s]

Epoch 9, Batch 200, Loss: 19134.57421875 RMSE(mm): 69.163889094581


236it [01:12,  3.27it/s]


Epoch 9, Val Loss: 18303.449896364797, RMSE(mm): 67.64512158383042
Epoch 9, test Loss: 16438.522212009804, RMSE(mm): 64.10640024991616


1it [00:00,  3.24it/s]

Epoch 10, Batch 0, Loss: 15206.75 RMSE(mm): 61.65782594285984


101it [00:30,  3.36it/s]

Epoch 10, Batch 100, Loss: 17772.38671875 RMSE(mm): 66.65655766455015


201it [01:01,  3.31it/s]

Epoch 10, Batch 200, Loss: 21164.3125 RMSE(mm): 72.73979739454875


236it [01:11,  3.28it/s]


Epoch 10, Val Loss: 18131.31098533163, RMSE(mm): 67.32627827477847
Epoch 10, test Loss: 16248.476888020834, RMSE(mm): 63.734756781564705


1it [00:00,  3.27it/s]

Epoch 11, Batch 0, Loss: 15507.4326171875 RMSE(mm): 62.26442125561656


101it [00:30,  3.11it/s]

Epoch 11, Batch 100, Loss: 17041.873046875 RMSE(mm): 65.27226257545199


201it [01:01,  3.30it/s]

Epoch 11, Batch 200, Loss: 20716.599609375 RMSE(mm): 71.96631088463373


236it [01:11,  3.28it/s]


Epoch 11, Val Loss: 18017.877032844386, RMSE(mm): 67.11534294191677
Epoch 11, test Loss: 16087.776482077206, RMSE(mm): 63.41879942508611


1it [00:00,  3.24it/s]

Epoch 12, Batch 0, Loss: 15540.9814453125 RMSE(mm): 62.33173638948401


101it [00:30,  3.36it/s]

Epoch 12, Batch 100, Loss: 17354.82421875 RMSE(mm): 65.86885496718081


201it [01:01,  3.34it/s]

Epoch 12, Batch 200, Loss: 20520.27734375 RMSE(mm): 71.62450234338456


236it [01:11,  3.30it/s]


Epoch 12, Val Loss: 17976.352877869896, RMSE(mm): 67.03796103304063
Epoch 12, test Loss: 15949.726868872549, RMSE(mm): 63.14611403101649


1it [00:00,  3.33it/s]

Epoch 13, Batch 0, Loss: 15360.01953125 RMSE(mm): 61.967772937330096


101it [00:30,  3.28it/s]

Epoch 13, Batch 100, Loss: 17074.916015625 RMSE(mm): 65.33551104802234


201it [01:00,  3.35it/s]

Epoch 13, Batch 200, Loss: 20725.70703125 RMSE(mm): 71.98212804448407


236it [01:11,  3.30it/s]


Epoch 13, Val Loss: 17988.38333067602, RMSE(mm): 67.06038944614775
Epoch 13, test Loss: 15946.159256280638, RMSE(mm): 63.139051418833965


1it [00:00,  3.30it/s]

Epoch 14, Batch 0, Loss: 15685.61328125 RMSE(mm): 62.62110922294893


101it [00:30,  3.31it/s]

Epoch 14, Batch 100, Loss: 18141.591796875 RMSE(mm): 67.34536323473762


201it [01:01,  3.32it/s]

Epoch 14, Batch 200, Loss: 19632.8828125 RMSE(mm): 70.05869470040817


236it [01:11,  3.29it/s]


Epoch 14, Val Loss: 17975.479093590562, RMSE(mm): 67.0363317418073
Epoch 14, test Loss: 15933.125651041666, RMSE(mm): 63.11324276853802
