In [1]:
from models.DeiT_pretrained import DeiT_pretrained
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = DeiT_pretrained()
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')

batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of DeiTForImageClassification were not initialized from the model checkpoint at facebook/deit-base-distilled-patch16-224 and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of DeiTForImageClassification were not initialized from the model checkpoint at facebook/deit-base-distilled-patch16-224 and are newly initialized because the shapes did not match:
- deit.embeddings.position_embeddings: found shape torch.Size([1, 198, 768]) in the checkpoint and torch.Size([1, 226, 768]) in the model instantiated
- deit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 8, 1]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
create dataloader...
HI
training...


1it [00:01,  1.02s/it]

Epoch 0, Batch 0, Loss: 168840.203125 RMSE(mm): 205.45084760411675


101it [00:30,  3.46it/s]

Epoch 0, Batch 100, Loss: 48530.828125 RMSE(mm): 110.14856799454998


201it [01:00,  3.43it/s]

Epoch 0, Batch 200, Loss: 34150.65625 RMSE(mm): 92.3994808562256


236it [01:10,  3.36it/s]


Epoch 0, Val Loss: 28510.083227040817, RMSE(mm): 84.42464573073555
Epoch 0, test Loss: 28614.324640012255, RMSE(mm): 84.57884581857962


1it [00:00,  3.47it/s]

Epoch 1, Batch 0, Loss: 26909.41796875 RMSE(mm): 82.0204516702237


101it [00:29,  3.43it/s]

Epoch 1, Batch 100, Loss: 26161.58984375 RMSE(mm): 80.87272383775323


201it [00:58,  3.44it/s]

Epoch 1, Batch 200, Loss: 31620.4140625 RMSE(mm): 88.91064905637008


236it [01:08,  3.43it/s]


Epoch 1, Val Loss: 25789.434151785714, RMSE(mm): 80.29544531258563
Epoch 1, test Loss: 25757.163909313724, RMSE(mm): 80.24519286118284


1it [00:00,  3.46it/s]

Epoch 2, Batch 0, Loss: 23361.8359375 RMSE(mm): 76.42289568169345


101it [00:29,  3.44it/s]

Epoch 2, Batch 100, Loss: 22250.6953125 RMSE(mm): 74.58333478817504


201it [00:58,  3.42it/s]

Epoch 2, Batch 200, Loss: 28595.0390625 RMSE(mm): 84.55033864878958


236it [01:08,  3.45it/s]


Epoch 2, Val Loss: 23919.132453762755, RMSE(mm): 77.32905736811156
Epoch 2, test Loss: 23137.413028492647, RMSE(mm): 76.05493578409728


1it [00:00,  3.46it/s]

Epoch 3, Batch 0, Loss: 20764.41796875 RMSE(mm): 72.04931985929846


101it [00:29,  3.43it/s]

Epoch 3, Batch 100, Loss: 17525.33203125 RMSE(mm): 66.19163850376043


201it [00:58,  3.44it/s]

Epoch 3, Batch 200, Loss: 26324.208984375 RMSE(mm): 81.12368486511045


236it [01:08,  3.44it/s]


Epoch 3, Val Loss: 20364.44168526786, RMSE(mm): 71.35201764012679
Epoch 3, test Loss: 18679.538009344364, RMSE(mm): 68.33655319326613


1it [00:00,  3.41it/s]

Epoch 4, Batch 0, Loss: 19179.97265625 RMSE(mm): 69.24588914919427


101it [00:29,  3.36it/s]

Epoch 4, Batch 100, Loss: 17212.982421875 RMSE(mm): 65.59912808466855


201it [00:58,  3.44it/s]

Epoch 4, Batch 200, Loss: 22116.51953125 RMSE(mm): 74.35811914520498


236it [01:08,  3.44it/s]


Epoch 4, Val Loss: 18946.88040098852, RMSE(mm): 68.82383380956868
Epoch 4, test Loss: 16259.436408547794, RMSE(mm): 63.756247553764865


1it [00:00,  3.36it/s]

Epoch 5, Batch 0, Loss: 15824.9423828125 RMSE(mm): 62.89861362306108


101it [00:29,  3.43it/s]

Epoch 5, Batch 100, Loss: 13957.927734375 RMSE(mm): 59.07183705958153


201it [00:59,  3.40it/s]

Epoch 5, Batch 200, Loss: 18944.6171875 RMSE(mm): 68.81972316767192


236it [01:09,  3.39it/s]


Epoch 5, Val Loss: 18625.540218431124, RMSE(mm): 68.23770991620235
Epoch 5, test Loss: 15635.510971966913, RMSE(mm): 62.52101840974544


1it [00:00,  3.36it/s]

Epoch 6, Batch 0, Loss: 12854.8037109375 RMSE(mm): 56.6895133841734


101it [00:29,  3.43it/s]

Epoch 6, Batch 100, Loss: 12134.392578125 RMSE(mm): 55.07810948581342


201it [00:59,  3.40it/s]

Epoch 6, Batch 200, Loss: 17971.482421875 RMSE(mm): 67.02887889162962


236it [01:09,  3.40it/s]


Epoch 6, Val Loss: 17599.168905452807, RMSE(mm): 66.33092963590366
Epoch 6, test Loss: 14521.287300857843, RMSE(mm): 60.252152038034794


1it [00:00,  3.41it/s]

Epoch 7, Batch 0, Loss: 10175.162109375 RMSE(mm): 50.4360042761493


101it [00:29,  3.38it/s]

Epoch 7, Batch 100, Loss: 11420.6953125 RMSE(mm): 53.43382662812949


201it [00:59,  3.41it/s]

Epoch 7, Batch 200, Loss: 17273.01171875 RMSE(mm): 65.7134151424768


236it [01:09,  3.38it/s]


Epoch 7, Val Loss: 17797.44915896046, RMSE(mm): 66.70354030889301
Epoch 7, test Loss: 14648.628408394608, RMSE(mm): 60.515759121890326


1it [00:00,  3.32it/s]

Epoch 8, Batch 0, Loss: 9278.84765625 RMSE(mm): 48.163387692961344


101it [00:29,  3.36it/s]

Epoch 8, Batch 100, Loss: 10526.34765625 RMSE(mm): 51.298995253927735


201it [00:59,  3.35it/s]

Epoch 8, Batch 200, Loss: 16100.806640625 RMSE(mm): 63.44447698701795


236it [01:09,  3.39it/s]


Epoch 8, Val Loss: 18067.650550063776, RMSE(mm): 67.20798046003127
Epoch 8, test Loss: 14917.446710324755, RMSE(mm): 61.06849987989871


1it [00:00,  3.36it/s]

Epoch 9, Batch 0, Loss: 8375.0 RMSE(mm): 45.757513044307814


101it [00:30,  3.36it/s]

Epoch 9, Batch 100, Loss: 9960.0859375 RMSE(mm): 49.90011507376511


201it [00:59,  3.40it/s]

Epoch 9, Batch 200, Loss: 14408.865234375 RMSE(mm): 60.01846639654957


236it [01:10,  3.37it/s]


Epoch 9, Val Loss: 18444.937878667093, RMSE(mm): 67.90607093380365
Epoch 9, test Loss: 15301.919136795343, RMSE(mm): 61.85046308799018


1it [00:00,  3.38it/s]

Epoch 10, Batch 0, Loss: 7702.2060546875 RMSE(mm): 43.88110656845238


101it [00:29,  3.40it/s]

Epoch 10, Batch 100, Loss: 9057.01171875 RMSE(mm): 47.584166796188626


201it [00:59,  3.38it/s]

Epoch 10, Batch 200, Loss: 12837.861328125 RMSE(mm): 56.65214322540013


236it [01:09,  3.38it/s]


Epoch 10, Val Loss: 18956.769431600766, RMSE(mm): 68.84179223335336
Epoch 10, test Loss: 15806.512140012255, RMSE(mm): 62.86197606664194


1it [00:00,  3.40it/s]

Epoch 11, Batch 0, Loss: 7031.041015625 RMSE(mm): 41.925651502466245


101it [00:29,  3.36it/s]

Epoch 11, Batch 100, Loss: 8253.5849609375 RMSE(mm): 45.4246215199904


201it [00:59,  3.40it/s]

Epoch 11, Batch 200, Loss: 10946.107421875 RMSE(mm): 52.31182328564691


236it [01:09,  3.38it/s]


Epoch 11, Val Loss: 19624.163016183036, RMSE(mm): 70.04313495301135
Epoch 11, test Loss: 16559.20201439951, RMSE(mm): 64.34128148863587


1it [00:00,  3.35it/s]

Epoch 12, Batch 0, Loss: 6556.3671875 RMSE(mm): 40.48569867095046


101it [00:30,  3.30it/s]

Epoch 12, Batch 100, Loss: 9078.5302734375 RMSE(mm): 47.64066087240368


201it [00:59,  3.41it/s]

Epoch 12, Batch 200, Loss: 8726.53125 RMSE(mm): 46.707952347539276


236it [01:09,  3.37it/s]


Epoch 12, Val Loss: 19326.401028380104, RMSE(mm): 69.5097134010422
Epoch 12, test Loss: 16410.519148284315, RMSE(mm): 64.05177426950075


1it [00:00,  3.37it/s]

Epoch 13, Batch 0, Loss: 6796.5791015625 RMSE(mm): 41.22068382973074


101it [00:29,  3.38it/s]

Epoch 13, Batch 100, Loss: 9138.37890625 RMSE(mm): 47.79743430941142


201it [00:59,  3.40it/s]

Epoch 13, Batch 200, Loss: 8456.99609375 RMSE(mm): 45.980963707141896


236it [01:09,  3.39it/s]


Epoch 13, Val Loss: 19389.230847417093, RMSE(mm): 69.6226092002754
Epoch 13, test Loss: 16444.666743259804, RMSE(mm): 64.11838024946475


1it [00:00,  3.32it/s]

Epoch 14, Batch 0, Loss: 6374.29736328125 RMSE(mm): 39.91959845514872


101it [00:29,  3.41it/s]

Epoch 14, Batch 100, Loss: 9094.888671875 RMSE(mm): 47.68356286991095


201it [00:59,  3.39it/s]

Epoch 14, Batch 200, Loss: 8368.6220703125 RMSE(mm): 45.74008654974458


236it [01:09,  3.40it/s]


Epoch 14, Val Loss: 19473.28220663265, RMSE(mm): 69.7733513001788
Epoch 14, test Loss: 16519.47447533701, RMSE(mm): 64.26405386243738


In [1]:
from models.EEGViT import EEGViT_raw
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_raw()
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')

batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
create dataloader...
HI
training...


1it [00:01,  1.35s/it]

Epoch 0, Batch 0, Loss: 168717.375 RMSE(mm): 205.3761031619794


41it [00:13,  3.02it/s]


KeyboardInterrupt: 

In [3]:
from models.EEGViT_pretrained_large_129stride import EEGViT_pretrained
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained()
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-large-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 1024]) in the checkpoint and torch.Size([1, 15, 1024]) in the model instantiated
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([1024, 3, 16, 16]) in the checkpoint and torch.Size([1024, 256, 129, 1]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


2it [00:00,  4.70it/s]

Epoch 0, Batch 0, Loss: 169134.125 RMSE(mm): 205.62959721304713


102it [00:13,  8.04it/s]

Epoch 0, Batch 100, Loss: 55035.7890625 RMSE(mm): 117.29853906006247


202it [00:25,  8.23it/s]

Epoch 0, Batch 200, Loss: 29037.609375 RMSE(mm): 85.20212640392258


236it [00:29,  7.98it/s]


Epoch 0, Val Loss: 25828.255062181124, RMSE(mm): 80.3558570705663
Epoch 0, test Loss: 25953.58252910539, RMSE(mm): 80.55057810019956


1it [00:00,  8.30it/s]

Epoch 1, Batch 0, Loss: 24452.119140625 RMSE(mm): 78.18586691439988


102it [00:12,  8.18it/s]

Epoch 1, Batch 100, Loss: 26139.556640625 RMSE(mm): 80.83866129616602


202it [00:24,  8.13it/s]

Epoch 1, Batch 200, Loss: 25886.20703125 RMSE(mm): 80.44595550935112


236it [00:28,  8.19it/s]


Epoch 1, Val Loss: 22020.20651307398, RMSE(mm): 74.19603512498828
Epoch 1, test Loss: 21674.984145220587, RMSE(mm): 73.61213239884542


1it [00:00,  8.32it/s]

Epoch 2, Batch 0, Loss: 20615.0 RMSE(mm): 71.78962320558591


102it [00:12,  8.17it/s]

Epoch 2, Batch 100, Loss: 21475.7109375 RMSE(mm): 73.27296728245008


202it [00:25,  8.08it/s]

Epoch 2, Batch 200, Loss: 22042.224609375 RMSE(mm): 74.23312031932748


236it [00:29,  8.04it/s]


Epoch 2, Val Loss: 16846.70378268495, RMSE(mm): 64.89742634088995
Epoch 2, test Loss: 15296.927830116421, RMSE(mm): 61.84037481717834


1it [00:00,  8.14it/s]

Epoch 3, Batch 0, Loss: 15570.0986328125 RMSE(mm): 62.39010064267508


102it [00:12,  8.11it/s]

Epoch 3, Batch 100, Loss: 15154.638671875 RMSE(mm): 61.552089062587875


202it [00:24,  8.10it/s]

Epoch 3, Batch 200, Loss: 19938.484375 RMSE(mm): 70.60184908166357


236it [00:29,  8.12it/s]


Epoch 3, Val Loss: 15037.29830994898, RMSE(mm): 61.31333115634189
Epoch 3, test Loss: 12762.288181678921, RMSE(mm): 56.48514889260478


1it [00:00,  8.20it/s]

Epoch 4, Batch 0, Loss: 13843.1083984375 RMSE(mm): 58.8283698534081


102it [00:12,  8.26it/s]

Epoch 4, Batch 100, Loss: 13749.859375 RMSE(mm): 58.62989718351892


202it [00:24,  8.09it/s]

Epoch 4, Batch 200, Loss: 19664.0625 RMSE(mm): 70.11430399711602


236it [00:28,  8.16it/s]


Epoch 4, Val Loss: 15472.336156728315, RMSE(mm): 62.19392284767121
Epoch 4, test Loss: 12815.651003370098, RMSE(mm): 56.603116087743125


1it [00:00,  8.28it/s]

Epoch 5, Batch 0, Loss: 13195.005859375 RMSE(mm): 57.43475833364105


102it [00:12,  8.13it/s]

Epoch 5, Batch 100, Loss: 12316.138671875 RMSE(mm): 55.48904998257539


202it [00:24,  8.16it/s]

Epoch 5, Batch 200, Loss: 19178.421875 RMSE(mm): 69.24308968229248


236it [00:28,  8.15it/s]


Epoch 5, Val Loss: 16186.681879783164, RMSE(mm): 63.61344566949499
Epoch 5, test Loss: 13194.255897671568, RMSE(mm): 57.43312610695932


1it [00:00,  7.94it/s]

Epoch 6, Batch 0, Loss: 13169.4423828125 RMSE(mm): 57.37909545908793


102it [00:12,  8.22it/s]

Epoch 6, Batch 100, Loss: 13696.154296875 RMSE(mm): 58.51528496229639


202it [00:24,  8.18it/s]

Epoch 6, Batch 200, Loss: 13849.537109375 RMSE(mm): 58.8420281545746


236it [00:28,  8.16it/s]


Epoch 6, Val Loss: 14766.677614795919, RMSE(mm): 60.75910963550223
Epoch 6, test Loss: 11940.426738664215, RMSE(mm): 54.636129847071466


1it [00:00,  8.24it/s]

Epoch 7, Batch 0, Loss: 12214.3720703125 RMSE(mm): 55.25932516397685


102it [00:12,  8.14it/s]

Epoch 7, Batch 100, Loss: 14013.021484375 RMSE(mm): 59.1883043437954


202it [00:24,  8.12it/s]

Epoch 7, Batch 200, Loss: 14194.2080078125 RMSE(mm): 59.569723870042615


236it [00:29,  8.11it/s]


Epoch 7, Val Loss: 14810.360361527424, RMSE(mm): 60.848911990123995
Epoch 7, test Loss: 11877.885589001226, RMSE(mm): 54.49285638733123


1it [00:00,  8.07it/s]

Epoch 8, Batch 0, Loss: 12216.349609375 RMSE(mm): 55.263798298196534


102it [00:12,  8.16it/s]

Epoch 8, Batch 100, Loss: 13902.287109375 RMSE(mm): 58.95398016541165


202it [00:24,  8.09it/s]

Epoch 8, Batch 200, Loss: 14096.7470703125 RMSE(mm): 59.36486138767718


236it [00:29,  8.12it/s]


Epoch 8, Val Loss: 14870.178591358419, RMSE(mm): 60.97167086311154
Epoch 8, test Loss: 11845.147480085785, RMSE(mm): 54.41770732051697


1it [00:00,  8.18it/s]

Epoch 9, Batch 0, Loss: 11841.515625 RMSE(mm): 54.40936414120275


102it [00:12,  7.99it/s]

Epoch 9, Batch 100, Loss: 13707.484375 RMSE(mm): 58.539483203646405


202it [00:25,  8.14it/s]

Epoch 9, Batch 200, Loss: 13843.1484375 RMSE(mm): 58.828454929353704


236it [00:29,  8.06it/s]


Epoch 9, Val Loss: 14880.186344068878, RMSE(mm): 60.99218463063296
Epoch 9, test Loss: 11778.676461014093, RMSE(mm): 54.26480549355653


1it [00:00,  8.17it/s]

Epoch 10, Batch 0, Loss: 11933.619140625 RMSE(mm): 54.620552772342485


102it [00:12,  8.17it/s]

Epoch 10, Batch 100, Loss: 13658.5751953125 RMSE(mm): 58.434953570856244


202it [00:24,  8.19it/s]

Epoch 10, Batch 200, Loss: 13835.44921875 RMSE(mm): 58.81209318403401


236it [00:29,  8.12it/s]


Epoch 10, Val Loss: 14918.29225127551, RMSE(mm): 61.07023057774449
Epoch 10, test Loss: 11740.915594362745, RMSE(mm): 54.177752801225395


1it [00:00,  8.21it/s]

Epoch 11, Batch 0, Loss: 11735.654296875 RMSE(mm): 54.16561246970951


102it [00:12,  8.18it/s]

Epoch 11, Batch 100, Loss: 13601.5556640625 RMSE(mm): 58.312853780411274


202it [00:24,  8.08it/s]

Epoch 11, Batch 200, Loss: 13293.0859375 RMSE(mm): 57.64782289362713


236it [00:29,  8.13it/s]


Epoch 11, Val Loss: 14917.508669483419, RMSE(mm): 61.06862670284026
Epoch 11, test Loss: 11664.747702205883, RMSE(mm): 54.001730764406716


1it [00:00,  8.24it/s]

Epoch 12, Batch 0, Loss: 11813.205078125 RMSE(mm): 54.344284607778675


102it [00:12,  8.15it/s]

Epoch 12, Batch 100, Loss: 13713.1630859375 RMSE(mm): 58.551607761737635


202it [00:24,  8.12it/s]

Epoch 12, Batch 200, Loss: 13446.0185546875 RMSE(mm): 57.9784842736672


236it [00:29,  8.09it/s]


Epoch 12, Val Loss: 14547.125019929847, RMSE(mm): 60.30573152679985
Epoch 12, test Loss: 11179.514523973652, RMSE(mm): 52.86661168444043


1it [00:00,  8.09it/s]

Epoch 13, Batch 0, Loss: 11595.6689453125 RMSE(mm): 53.841593924475575


102it [00:12,  8.14it/s]

Epoch 13, Batch 100, Loss: 13486.6474609375 RMSE(mm): 58.066012995851324


202it [00:24,  8.11it/s]

Epoch 13, Batch 200, Loss: 13465.849609375 RMSE(mm): 58.02122372325277


236it [00:29,  8.12it/s]


Epoch 13, Val Loss: 14502.108488121812, RMSE(mm): 60.2123502450324
Epoch 13, test Loss: 11122.658949908087, RMSE(mm): 52.73200866150484


1it [00:00,  7.97it/s]

Epoch 14, Batch 0, Loss: 11722.0810546875 RMSE(mm): 54.13427993122172


102it [00:12,  8.12it/s]

Epoch 14, Batch 100, Loss: 13620.21875 RMSE(mm): 58.352846438712824


202it [00:24,  8.19it/s]

Epoch 14, Batch 200, Loss: 13530.923828125 RMSE(mm): 58.161249617174235


236it [00:29,  8.13it/s]


Epoch 14, Val Loss: 14489.392578125, RMSE(mm): 60.18594640388444
Epoch 14, test Loss: 11100.133817784927, RMSE(mm): 52.678586298858015


In [5]:
from models.EEGVit_pretrained_129stride import EEGViT_pretrained
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained()
batch_size = 64
n_epoch = 15
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 129, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 33, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


2it [00:00,  5.97it/s]

Epoch 0, Batch 0, Loss: 169209.65625 RMSE(mm): 205.67550671506805


103it [00:10,  9.72it/s]

Epoch 0, Batch 100, Loss: 66471.796875 RMSE(mm): 128.9106249257601


202it [00:21,  9.69it/s]

Epoch 0, Batch 200, Loss: 32945.765625 RMSE(mm): 90.75484232948675


236it [00:24,  9.63it/s]


Epoch 0, Val Loss: 26505.066485969386, RMSE(mm): 81.40188340261143
Epoch 0, test Loss: 26794.276922487745, RMSE(mm): 81.8447874370869


2it [00:00,  9.74it/s]

Epoch 1, Batch 0, Loss: 24906.607421875 RMSE(mm): 78.90913670462217


102it [00:10,  9.85it/s]

Epoch 1, Batch 100, Loss: 25761.875 RMSE(mm): 80.25253111273189


203it [00:20,  9.88it/s]

Epoch 1, Batch 200, Loss: 27765.81640625 RMSE(mm): 83.31538934412117


236it [00:23,  9.84it/s]


Epoch 1, Val Loss: 22384.87428252551, RMSE(mm): 74.80787773110114
Epoch 1, test Loss: 22031.836894914217, RMSE(mm): 74.21562654676273


2it [00:00,  9.98it/s]

Epoch 2, Batch 0, Loss: 21701.56640625 RMSE(mm): 73.65725762993421


103it [00:10,  9.68it/s]

Epoch 2, Batch 100, Loss: 20668.462890625 RMSE(mm): 71.88265244588746


202it [00:20,  9.87it/s]

Epoch 2, Batch 200, Loss: 21188.21875 RMSE(mm): 72.78086759238309


236it [00:24,  9.72it/s]


Epoch 2, Val Loss: 17160.15898038903, RMSE(mm): 65.49839498107765
Epoch 2, test Loss: 15898.565448835785, RMSE(mm): 63.04475681774771


1it [00:00,  9.67it/s]

Epoch 3, Batch 0, Loss: 16954.53515625 RMSE(mm): 65.10479083034136


102it [00:10,  9.52it/s]

Epoch 3, Batch 100, Loss: 15677.134765625 RMSE(mm): 62.60418269897188


202it [00:20,  9.59it/s]

Epoch 3, Batch 200, Loss: 19016.6796875 RMSE(mm): 68.950488916867


236it [00:24,  9.65it/s]


Epoch 3, Val Loss: 15287.147122130102, RMSE(mm): 61.82060158662746
Epoch 3, test Loss: 12862.191119025736, RMSE(mm): 56.7058002302801


1it [00:00,  9.81it/s]

Epoch 4, Batch 0, Loss: 13602.89453125 RMSE(mm): 58.31572371850066


103it [00:10,  9.75it/s]

Epoch 4, Batch 100, Loss: 12621.1708984375 RMSE(mm): 56.17199235036421


202it [00:20,  9.72it/s]

Epoch 4, Batch 200, Loss: 18314.33984375 RMSE(mm): 67.66524189668947


236it [00:24,  9.73it/s]


Epoch 4, Val Loss: 15286.353675063776, RMSE(mm): 61.818997231967
Epoch 4, test Loss: 12670.62917432598, RMSE(mm): 56.281944649962966


2it [00:00,  9.75it/s]

Epoch 5, Batch 0, Loss: 12197.92578125 RMSE(mm): 55.22211011282075


102it [00:10,  9.91it/s]

Epoch 5, Batch 100, Loss: 11073.1669921875 RMSE(mm): 52.61455832796542


202it [00:20,  9.81it/s]

Epoch 5, Batch 200, Loss: 17374.17578125 RMSE(mm): 65.9055683938201


236it [00:23,  9.84it/s]


Epoch 5, Val Loss: 15591.278419961734, RMSE(mm): 62.43252041196506
Epoch 5, test Loss: 12893.32825903799, RMSE(mm): 56.77439620779333


1it [00:00,  9.91it/s]

Epoch 6, Batch 0, Loss: 11867.810546875 RMSE(mm): 54.46974056041345


102it [00:10,  9.86it/s]

Epoch 6, Batch 100, Loss: 12989.712890625 RMSE(mm): 56.986210811530974


202it [00:20,  9.71it/s]

Epoch 6, Batch 200, Loss: 13536.1640625 RMSE(mm): 58.17251082448651


236it [00:24,  9.83it/s]


Epoch 6, Val Loss: 14504.360829878826, RMSE(mm): 60.21702589359347
Epoch 6, test Loss: 11773.598785998774, RMSE(mm): 54.253107712827784


1it [00:00,  9.92it/s]

Epoch 7, Batch 0, Loss: 10061.412109375 RMSE(mm): 50.15329527901183


102it [00:10,  9.67it/s]

Epoch 7, Batch 100, Loss: 12693.837890625 RMSE(mm): 56.33346671967073


203it [00:20,  9.67it/s]

Epoch 7, Batch 200, Loss: 12945.595703125 RMSE(mm): 56.8893568761438


236it [00:24,  9.73it/s]


Epoch 7, Val Loss: 14566.239785953443, RMSE(mm): 60.345339061839404
Epoch 7, test Loss: 11647.355286841299, RMSE(mm): 53.961456816049036


1it [00:00,  9.92it/s]

Epoch 8, Batch 0, Loss: 10190.9375 RMSE(mm): 50.47508667649814


103it [00:10,  9.66it/s]

Epoch 8, Batch 100, Loss: 12570.8173828125 RMSE(mm): 56.05982827036777


202it [00:20,  9.71it/s]

Epoch 8, Batch 200, Loss: 13135.91015625 RMSE(mm): 57.3059991542116


236it [00:24,  9.72it/s]


Epoch 8, Val Loss: 14725.876863440688, RMSE(mm): 60.67511199709624
Epoch 8, test Loss: 11535.471717984068, RMSE(mm): 53.7016566736634


0it [00:00, ?it/s]

Epoch 9, Batch 0, Loss: 9929.70703125 RMSE(mm): 49.82395766910232


102it [00:10,  9.67it/s]

Epoch 9, Batch 100, Loss: 12226.0712890625 RMSE(mm): 55.28578318397619


203it [00:20,  9.89it/s]

Epoch 9, Batch 200, Loss: 12699.7861328125 RMSE(mm): 56.34666390482337


236it [00:23,  9.86it/s]


Epoch 9, Val Loss: 14878.390027104591, RMSE(mm): 60.988503070465235
Epoch 9, test Loss: 11517.170505897671, RMSE(mm): 53.659040491555736


2it [00:00,  9.85it/s]

Epoch 10, Batch 0, Loss: 9460.8671875 RMSE(mm): 48.63349459863027


103it [00:10,  9.80it/s]

Epoch 10, Batch 100, Loss: 12115.90625 RMSE(mm): 55.036138695406315


202it [00:20,  9.80it/s]

Epoch 10, Batch 200, Loss: 12690.9140625 RMSE(mm): 56.32697857709927


236it [00:23,  9.85it/s]


Epoch 10, Val Loss: 15000.234016262755, RMSE(mm): 61.237721251412424
Epoch 10, test Loss: 11574.670563342524, RMSE(mm): 53.792821461935155


1it [00:00,  9.75it/s]

Epoch 11, Batch 0, Loss: 8825.8955078125 RMSE(mm): 46.97311866326447


102it [00:10,  9.79it/s]

Epoch 11, Batch 100, Loss: 11638.744140625 RMSE(mm): 53.94150568121222


202it [00:20,  9.84it/s]

Epoch 11, Batch 200, Loss: 12312.9189453125 RMSE(mm): 55.48179644106817


236it [00:23,  9.86it/s]


Epoch 11, Val Loss: 15274.788913026148, RMSE(mm): 61.79560848682159
Epoch 11, test Loss: 11648.225404028799, RMSE(mm): 53.96347237722198


1it [00:00,  9.79it/s]

Epoch 12, Batch 0, Loss: 8317.537109375 RMSE(mm): 45.60026619816764


102it [00:10,  9.85it/s]

Epoch 12, Batch 100, Loss: 11997.3115234375 RMSE(mm): 54.766119826580514


202it [00:20,  9.63it/s]

Epoch 12, Batch 200, Loss: 11967.177734375 RMSE(mm): 54.697298229380124


236it [00:24,  9.70it/s]


Epoch 12, Val Loss: 14909.820890465562, RMSE(mm): 61.05288873277325
Epoch 12, test Loss: 11169.506338082108, RMSE(mm): 52.84294261791755


0it [00:00, ?it/s]

Epoch 13, Batch 0, Loss: 8248.880859375 RMSE(mm): 45.41167487380035


101it [00:10,  9.81it/s]

Epoch 13, Batch 100, Loss: 11862.4609375 RMSE(mm): 54.45746261418172


202it [00:20,  9.79it/s]

Epoch 13, Batch 200, Loss: 12053.26171875 RMSE(mm): 54.89367385853765


236it [00:24,  9.79it/s]


Epoch 13, Val Loss: 14909.459721779336, RMSE(mm): 61.0521492696599
Epoch 13, test Loss: 11137.306640625, RMSE(mm): 52.76671924761146


2it [00:00,  9.76it/s]

Epoch 14, Batch 0, Loss: 8274.46484375 RMSE(mm): 45.4820427304832


102it [00:10,  9.81it/s]

Epoch 14, Batch 100, Loss: 11696.1142578125 RMSE(mm): 54.074287461353805


202it [00:20,  9.73it/s]

Epoch 14, Batch 200, Loss: 12137.4814453125 RMSE(mm): 55.085119236760534


236it [00:24,  9.81it/s]


Epoch 14, Val Loss: 14936.971490353953, RMSE(mm): 61.10845172796058
Epoch 14, test Loss: 11128.252623314951, RMSE(mm): 52.745266667528924


In [1]:
from models.EEGViT_pretrained_hierarchical import EEGViT_pretrained_hierachical
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained_hierachical()
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')

batch_size = 64
n_epoch = 50
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch)

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 768, 129, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 29, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Positions Shape: torch.Size([1, 2])


Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 768, 129, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 29, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...
[[  1.  408.1 315.1]
 [  1.  640.7 519.1]
 [  1.  404.2 118.8]
 ...
 [177.  115.5 306.1]
 [177.  732.  310.3]
 [177.  632.2 353.6]]
create dataloader...
HI
training...


2it [00:00,  4.21it/s]

Epoch 0, Batch 0, Loss: 168691.5625 RMSE(mm): 205.36039205504065


103it [00:10,  9.51it/s]

Epoch 0, Batch 100, Loss: 65823.828125 RMSE(mm): 128.28077420740024


203it [00:21,  9.47it/s]

Epoch 0, Batch 200, Loss: 31858.486328125 RMSE(mm): 89.2447285952019


236it [00:24,  9.55it/s]


Epoch 0, Val Loss: 27153.670599489797, RMSE(mm): 82.3918542689291
Epoch 0, test Loss: 27582.056717218136, RMSE(mm): 83.03923277165158


1it [00:00,  9.21it/s]

Epoch 1, Batch 0, Loss: 26075.404296875 RMSE(mm): 80.73940224090559


103it [00:10, 10.21it/s]

Epoch 1, Batch 100, Loss: 25318.6640625 RMSE(mm): 79.55919818364814


203it [00:20,  9.75it/s]

Epoch 1, Batch 200, Loss: 24617.5703125 RMSE(mm): 78.44993676304016


236it [00:23,  9.98it/s]


Epoch 1, Val Loss: 22516.736328125, RMSE(mm): 75.02788869501293
Epoch 1, test Loss: 22330.747127757353, RMSE(mm): 74.71737938350982


1it [00:00,  9.78it/s]

Epoch 2, Batch 0, Loss: 22329.0078125 RMSE(mm): 74.71446950306881


102it [00:10,  9.63it/s]

Epoch 2, Batch 100, Loss: 22642.859375 RMSE(mm): 75.23772221266404


202it [00:20,  9.89it/s]

Epoch 2, Batch 200, Loss: 23104.2890625 RMSE(mm): 76.00047543025636


236it [00:23,  9.84it/s]


Epoch 2, Val Loss: 19179.047612404338, RMSE(mm): 69.244219275699
Epoch 2, test Loss: 18422.24249387255, RMSE(mm): 67.86428091027074


2it [00:00,  9.67it/s]

Epoch 3, Batch 0, Loss: 18198.5859375 RMSE(mm): 67.45106733310452


102it [00:10,  9.58it/s]

Epoch 3, Batch 100, Loss: 15729.1083984375 RMSE(mm): 62.70787111367579


203it [00:20,  9.87it/s]

Epoch 3, Batch 200, Loss: 20385.162109375 RMSE(mm): 71.38830805771873


236it [00:24,  9.80it/s]


Epoch 3, Val Loss: 15409.953304368622, RMSE(mm): 62.06841649415712
Epoch 3, test Loss: 13510.386776194853, RMSE(mm): 58.11709468003983


2it [00:00,  9.53it/s]

Epoch 4, Batch 0, Loss: 13453.0283203125 RMSE(mm): 57.99359516427762


102it [00:10,  9.90it/s]

Epoch 4, Batch 100, Loss: 12722.3505859375 RMSE(mm): 56.39669889704871


202it [00:20, 10.17it/s]

Epoch 4, Batch 200, Loss: 18610.396484375 RMSE(mm): 68.20996350309645


236it [00:23,  9.97it/s]


Epoch 4, Val Loss: 15285.603136957909, RMSE(mm): 61.817479601157125
Epoch 4, test Loss: 12929.026022518383, RMSE(mm): 56.852937528588576


1it [00:00,  9.08it/s]

Epoch 5, Batch 0, Loss: 11817.9462890625 RMSE(mm): 54.35518900956582


103it [00:10,  9.96it/s]

Epoch 5, Batch 100, Loss: 11532.5302734375 RMSE(mm): 53.69480951041148


202it [00:20,  9.92it/s]

Epoch 5, Batch 200, Loss: 18248.673828125 RMSE(mm): 67.54382619478444


236it [00:24,  9.82it/s]


Epoch 5, Val Loss: 15219.441764987245, RMSE(mm): 61.68355081581159
Epoch 5, test Loss: 12423.043131510416, RMSE(mm): 55.72935297379294


1it [00:00,  9.70it/s]

Epoch 6, Batch 0, Loss: 11501.556640625 RMSE(mm): 53.62265528819186


102it [00:10, 10.05it/s]

Epoch 6, Batch 100, Loss: 12105.4609375 RMSE(mm): 55.01240982155753


202it [00:20, 10.08it/s]

Epoch 6, Batch 200, Loss: 14236.1044921875 RMSE(mm): 59.65757389507953


236it [00:23, 10.06it/s]


Epoch 6, Val Loss: 14274.699597417091, RMSE(mm): 59.73838715059416
Epoch 6, test Loss: 11598.966260723038, RMSE(mm): 53.84924851082659


0it [00:00, ?it/s]

Epoch 7, Batch 0, Loss: 11123.9013671875 RMSE(mm): 52.73495370052841


103it [00:10,  9.81it/s]

Epoch 7, Batch 100, Loss: 11731.0390625 RMSE(mm): 54.154960674207864


203it [00:20, 10.03it/s]

Epoch 7, Batch 200, Loss: 14161.125 RMSE(mm): 59.50026260446251


236it [00:23,  9.92it/s]


Epoch 7, Val Loss: 14197.03248565051, RMSE(mm): 59.57565040696264
Epoch 7, test Loss: 11434.53502221201, RMSE(mm): 53.46619264126634


2it [00:00,  9.91it/s]

Epoch 8, Batch 0, Loss: 10169.9326171875 RMSE(mm): 50.42304189848997


103it [00:10, 10.00it/s]

Epoch 8, Batch 100, Loss: 11424.189453125 RMSE(mm): 53.44199999327542


203it [00:20,  9.77it/s]

Epoch 8, Batch 200, Loss: 14023.8544921875 RMSE(mm): 59.211178193368816


236it [00:23,  9.93it/s]


Epoch 8, Val Loss: 14215.593789859693, RMSE(mm): 59.61458250684075
Epoch 8, test Loss: 11389.638777190563, RMSE(mm): 53.36112530951386


2it [00:00,  9.93it/s]

Epoch 9, Batch 0, Loss: 9777.228515625 RMSE(mm): 49.439934556047405


101it [00:10, 10.01it/s]

Epoch 9, Batch 100, Loss: 11550.853515625 RMSE(mm): 53.73744857086397


201it [00:20, 10.11it/s]

Epoch 9, Batch 200, Loss: 14028.1640625 RMSE(mm): 59.22027537613279


236it [00:23, 10.00it/s]


Epoch 9, Val Loss: 14173.342334980867, RMSE(mm): 59.52592362782132
Epoch 9, test Loss: 11279.37979664522, RMSE(mm): 53.10221228123462


1it [00:00,  9.57it/s]

Epoch 10, Batch 0, Loss: 9351.8291015625 RMSE(mm): 48.35242781278542


103it [00:10,  9.90it/s]

Epoch 10, Batch 100, Loss: 11382.1875 RMSE(mm): 53.34366761856556


203it [00:20,  9.83it/s]

Epoch 10, Batch 200, Loss: 13869.51171875 RMSE(mm): 58.88444556661377


236it [00:23,  9.94it/s]


Epoch 10, Val Loss: 14216.967693718112, RMSE(mm): 59.61746324215353
Epoch 10, test Loss: 11262.024701286764, RMSE(mm): 53.06134351221886


1it [00:00,  9.63it/s]

Epoch 11, Batch 0, Loss: 8894.41796875 RMSE(mm): 47.15511098690682


102it [00:10,  9.95it/s]

Epoch 11, Batch 100, Loss: 11199.779296875 RMSE(mm): 52.91450485659627


202it [00:20,  9.96it/s]

Epoch 11, Batch 200, Loss: 13617.447265625 RMSE(mm): 58.34690922753535


236it [00:23, 10.01it/s]


Epoch 11, Val Loss: 14265.579251036352, RMSE(mm): 59.71930016970299
Epoch 11, test Loss: 11245.621323529413, RMSE(mm): 53.022686945140315


2it [00:00, 10.12it/s]

Epoch 12, Batch 0, Loss: 8520.318359375 RMSE(mm): 46.152785288038146


103it [00:10,  9.98it/s]

Epoch 12, Batch 100, Loss: 11361.5537109375 RMSE(mm): 53.29529461157312


202it [00:20, 10.15it/s]

Epoch 12, Batch 200, Loss: 13152.84375 RMSE(mm): 57.342924040373106


236it [00:23, 10.04it/s]


Epoch 12, Val Loss: 14090.100944674745, RMSE(mm): 59.35086550479855
Epoch 12, test Loss: 10927.206016390932, RMSE(mm): 52.26663853834234


2it [00:00, 10.00it/s]

Epoch 13, Batch 0, Loss: 8298.4873046875 RMSE(mm): 45.54801670953275


103it [00:10, 10.04it/s]

Epoch 13, Batch 100, Loss: 11354.5546875 RMSE(mm): 53.278876413406095


202it [00:20,  9.93it/s]

Epoch 13, Batch 200, Loss: 13156.7177734375 RMSE(mm): 57.35136827800515


236it [00:23, 10.04it/s]


Epoch 13, Val Loss: 14111.026207748724, RMSE(mm): 59.3949202536478
Epoch 13, test Loss: 10905.339786305147, RMSE(mm): 52.21431744815101


2it [00:00, 10.21it/s]

Epoch 14, Batch 0, Loss: 8556.392578125 RMSE(mm): 46.25038534467848


102it [00:10,  9.98it/s]

Epoch 14, Batch 100, Loss: 11628.576171875 RMSE(mm): 53.9179380444834


203it [00:20,  9.89it/s]

Epoch 14, Batch 200, Loss: 13190.0712890625 RMSE(mm): 57.42401781716101


236it [00:23,  9.94it/s]


Epoch 14, Val Loss: 14136.743871572065, RMSE(mm): 59.44901990691702
Epoch 14, test Loss: 10916.555156632965, RMSE(mm): 52.24115991398202


0it [00:00, ?it/s]

Epoch 15, Batch 0, Loss: 8538.861328125 RMSE(mm): 46.202979687799896


102it [00:10, 10.15it/s]

Epoch 15, Batch 100, Loss: 11473.3095703125 RMSE(mm): 53.55676794372608


202it [00:20, 10.14it/s]

Epoch 15, Batch 200, Loss: 13126.9140625 RMSE(mm): 57.28637286148426


236it [00:23, 10.09it/s]


Epoch 15, Val Loss: 14160.24801698023, RMSE(mm): 59.49842018276668
Epoch 15, test Loss: 10929.22705078125, RMSE(mm): 52.271471786198184


1it [00:00,  9.92it/s]

Epoch 16, Batch 0, Loss: 8371.65625 RMSE(mm): 45.74837770347709


103it [00:10,  9.61it/s]

Epoch 16, Batch 100, Loss: 11264.5234375 RMSE(mm): 53.06722961842836


202it [00:20,  9.66it/s]

Epoch 16, Batch 200, Loss: 13082.947265625 RMSE(mm): 57.19035597376755


236it [00:24,  9.74it/s]


Epoch 16, Val Loss: 14180.337023676659, RMSE(mm): 59.54061014063565
Epoch 16, test Loss: 10941.11398973652, RMSE(mm): 52.29989003271546


2it [00:00,  9.36it/s]

Epoch 17, Batch 0, Loss: 8459.119140625 RMSE(mm): 45.986734882531614


102it [00:10,  9.61it/s]

Epoch 17, Batch 100, Loss: 11309.072265625 RMSE(mm): 53.172060956918436


203it [00:21,  9.70it/s]

Epoch 17, Batch 200, Loss: 13162.8720703125 RMSE(mm): 57.36478028876363


236it [00:24,  9.66it/s]


Epoch 17, Val Loss: 14193.510453204719, RMSE(mm): 59.56826011645111
Epoch 17, test Loss: 10950.576411228554, RMSE(mm): 52.322500922711434


1it [00:00,  9.90it/s]

Epoch 18, Batch 0, Loss: 8291.6611328125 RMSE(mm): 45.52927940570908


103it [00:10,  9.61it/s]

Epoch 18, Batch 100, Loss: 11113.2822265625 RMSE(mm): 52.70977667037326


203it [00:21,  9.61it/s]

Epoch 18, Batch 200, Loss: 13120.82421875 RMSE(mm): 57.273083160307515


236it [00:24,  9.62it/s]


Epoch 18, Val Loss: 14182.218730070153, RMSE(mm): 59.544560477994445
Epoch 18, test Loss: 10940.546310125612, RMSE(mm): 52.29853322542998


2it [00:00,  9.56it/s]

Epoch 19, Batch 0, Loss: 8303.427734375 RMSE(mm): 45.561572992970184


103it [00:10,  9.44it/s]

Epoch 19, Batch 100, Loss: 11192.751953125 RMSE(mm): 52.89790154893907


203it [00:21,  9.59it/s]

Epoch 19, Batch 200, Loss: 13167.0263671875 RMSE(mm): 57.37383194276703


236it [00:24,  9.63it/s]


Epoch 19, Val Loss: 14174.483099489797, RMSE(mm): 59.5283191000086
Epoch 19, test Loss: 10935.00062231924, RMSE(mm): 52.28527666159767


1it [00:00,  9.80it/s]

Epoch 20, Batch 0, Loss: 8462.5966796875 RMSE(mm): 45.99618647150952


103it [00:10,  9.84it/s]

Epoch 20, Batch 100, Loss: 11121.109375 RMSE(mm): 52.728335302283156


203it [00:20,  9.74it/s]

Epoch 20, Batch 200, Loss: 13096.203125 RMSE(mm): 57.219321747553074


236it [00:24,  9.74it/s]


Epoch 20, Val Loss: 14168.943319515307, RMSE(mm): 59.51668530654935
Epoch 20, test Loss: 10930.812844669117, RMSE(mm): 52.27526385554911


1it [00:00,  9.61it/s]

Epoch 21, Batch 0, Loss: 8371.380859375 RMSE(mm): 45.747625237204936


103it [00:10,  9.73it/s]

Epoch 21, Batch 100, Loss: 11180.462890625 RMSE(mm): 52.86885399416418


202it [00:20, 10.17it/s]

Epoch 21, Batch 200, Loss: 12901.5732421875 RMSE(mm): 56.7925462587026


236it [00:24,  9.83it/s]


Epoch 21, Val Loss: 14165.390056999362, RMSE(mm): 59.50922209414134
Epoch 21, test Loss: 10928.468376608456, RMSE(mm): 52.26965749028889


0it [00:00, ?it/s]

Epoch 22, Batch 0, Loss: 8428.462890625 RMSE(mm): 45.903330191351586


102it [00:10, 10.07it/s]

Epoch 22, Batch 100, Loss: 11272.5556640625 RMSE(mm): 53.08614617784592


203it [00:20, 10.03it/s]

Epoch 22, Batch 200, Loss: 13037.458984375 RMSE(mm): 57.09084642999918


236it [00:23, 10.12it/s]


Epoch 22, Val Loss: 14163.006008848852, RMSE(mm): 59.50421415506815
Epoch 22, test Loss: 10927.248200061274, RMSE(mm): 52.26673942399046


2it [00:00, 10.05it/s]

Epoch 23, Batch 0, Loss: 8298.96484375 RMSE(mm): 45.54932722815453


102it [00:10, 10.04it/s]

Epoch 23, Batch 100, Loss: 11256.4658203125 RMSE(mm): 53.04824648447981


202it [00:20,  9.91it/s]

Epoch 23, Batch 200, Loss: 13011.59375 RMSE(mm): 57.03418656823292


236it [00:23,  9.99it/s]


Epoch 23, Val Loss: 14161.571299027424, RMSE(mm): 59.501200195936015
Epoch 23, test Loss: 10926.349982766544, RMSE(mm): 52.26459122285026


1it [00:00,  9.89it/s]

Epoch 24, Batch 0, Loss: 8352.68359375 RMSE(mm): 45.69650860227179


102it [00:10,  9.97it/s]

Epoch 24, Batch 100, Loss: 11065.6640625 RMSE(mm): 52.59673008491117


203it [00:20, 10.03it/s]

Epoch 24, Batch 200, Loss: 13033.6953125 RMSE(mm): 57.08260530253503


236it [00:23,  9.97it/s]


Epoch 24, Val Loss: 14161.336435746174, RMSE(mm): 59.50070679358812
Epoch 24, test Loss: 10926.199860217524, RMSE(mm): 52.26423217702888


0it [00:00, ?it/s]

Epoch 25, Batch 0, Loss: 8431.8623046875 RMSE(mm): 45.91258625008915


103it [00:10, 10.03it/s]

Epoch 25, Batch 100, Loss: 11409.111328125 RMSE(mm): 53.40672085076231


203it [00:20, 10.00it/s]

Epoch 25, Batch 200, Loss: 13147.41796875 RMSE(mm): 57.331095333924154


236it [00:23, 10.03it/s]


Epoch 25, Val Loss: 14161.120944276148, RMSE(mm): 59.500254084071244
Epoch 25, test Loss: 10926.038717830883, RMSE(mm): 52.26384677248433


0it [00:00, ?it/s]

Epoch 26, Batch 0, Loss: 8315.91796875 RMSE(mm): 45.59582757432417


103it [00:10,  9.86it/s]

Epoch 26, Batch 100, Loss: 11260.2646484375 RMSE(mm): 53.05719708116303


202it [00:20, 10.08it/s]

Epoch 26, Batch 200, Loss: 13117.5302734375 RMSE(mm): 57.26589358736468


236it [00:23,  9.89it/s]


Epoch 26, Val Loss: 14160.884466677297, RMSE(mm): 59.49975728244044
Epoch 26, test Loss: 10925.89168772978, RMSE(mm): 52.26349511783961


2it [00:00,  9.78it/s]

Epoch 27, Batch 0, Loss: 8292.970703125 RMSE(mm): 45.532874670739275


102it [00:10,  9.46it/s]

Epoch 27, Batch 100, Loss: 11300.3642578125 RMSE(mm): 53.15158571908391


203it [00:20,  9.94it/s]

Epoch 27, Batch 200, Loss: 12932.708984375 RMSE(mm): 56.86103451480416


236it [00:24,  9.83it/s]


Epoch 27, Val Loss: 14160.630052216198, RMSE(mm): 59.49922279369748
Epoch 27, test Loss: 10925.723403033087, RMSE(mm): 52.26309262527689


1it [00:00,  9.72it/s]

Epoch 28, Batch 0, Loss: 8251.6005859375 RMSE(mm): 45.41916056560684


103it [00:10,  9.61it/s]

Epoch 28, Batch 100, Loss: 11208.7744140625 RMSE(mm): 52.93574976814464


203it [00:21,  9.78it/s]

Epoch 28, Batch 200, Loss: 13135.6875 RMSE(mm): 57.305513478198584


236it [00:24,  9.55it/s]


Epoch 28, Val Loss: 14160.402214205995, RMSE(mm): 59.49874413423782
Epoch 28, test Loss: 10925.599657245712, RMSE(mm): 52.26279665604805


1it [00:00,  8.30it/s]

Epoch 29, Batch 0, Loss: 8265.1875 RMSE(mm): 45.45653830858659


103it [00:10,  9.75it/s]

Epoch 29, Batch 100, Loss: 11313.740234375 RMSE(mm): 53.18303355952676


104it [00:10,  9.52it/s]


KeyboardInterrupt: 

In [1]:
from models.EEGViT_pretrained_stride import EEGViT_pretrained
from helper_functions import train
from dataset.EEGEyeNet import EEGEyeNetDataset
import torch

'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
model = EEGViT_pretrained()
EEGEyeNet = EEGEyeNetDataset('./dataset/Position_task_with_dots_synchronised_min.npz')

batch_size = 64
n_epoch = 30
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
train(model,EEGEyeNet, optimizer, scheduler, batch_size = batch_size ,n_epoch = n_epoch,log_name='EEGViT_pretrained/18stride')

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 129, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 15, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Positions Shape: torch.Size([1, 2])


Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 256, 129, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 15, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


loading data...


KeyboardInterrupt: 