In [2]:
from importlib import reload
from dataset.EEGEyeNet_MTL import EEGEyeNetDataset
import torch
'''
models: EEGViT_pretrained; EEGViT_raw; ViTBase; ViTBase_pretrained
'''
EEGEyeNet = EEGEyeNetDataset('./dataset\MTL_data_2\Position_task_with_dots_synchronized_min.npz')
from models.EEGViT_pretrained_hierarchical_pupil import EEGViT_pretrained_hierachical2
from helper_function_pupil import train
batch_size = 64
n_epoch = 20
learning_rate = 1e-4
model_name = 'MTL_std_pupil_cat_VIT_pre_hei'
i=0
model = EEGViT_pretrained_hierachical2()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=6, gamma=0.1)
file_name = f'{model_name}_weight_test_{i}'
train(model,EEGEyeNet, optimizer, scheduler,log_name=file_name, batch_size = batch_size ,n_epoch = n_epoch, subtask_weight=i)

loading data...
[[ 1.00000000e+00  4.08100000e+02  3.15100000e+02  1.34359272e+00]
 [ 1.00000000e+00  6.40700000e+02  5.19100000e+02  3.45834615e-01]
 [ 1.00000000e+00  4.04200000e+02  1.18800000e+02  1.70293855e+00]
 ...
 [ 3.00000000e+01  1.15500000e+02  3.06100000e+02 -4.09235014e-01]
 [ 3.00000000e+01  7.32000000e+02  3.10300000e+02 -4.81621022e-01]
 [ 3.00000000e+01  6.32200000e+02  3.53600000e+02 -4.66137384e-01]]


Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 768, 129, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 15, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


3it [00:00,  9.74it/s]

Epoch 0, Batch 0, position loss: 168988.453125 reconstruction loss: 0.0 RMSE(mm): 205.5410257862162


103it [00:07, 14.53it/s]

Epoch 0, Batch 100, position loss: 135124.453125 reconstruction loss: 0.0 RMSE(mm): 183.79639082759488


203it [00:14, 14.43it/s]

Epoch 0, Batch 200, position loss: 147830.484375 reconstruction loss: 0.0 RMSE(mm): 192.24365033402273


230it [00:16, 14.33it/s]


Epoch 0, Val Loss: 128878.38025841347, RMSE(mm): 179.49817565814803
Epoch 0, test Loss: 139498.98602764422, RMSE(mm): 186.74781526676838


2it [00:00, 14.09it/s]

Epoch 1, Batch 0, position loss: 142764.53125 reconstruction loss: 0.0 RMSE(mm): 188.92096975322775


104it [00:07, 14.79it/s]

Epoch 1, Batch 100, position loss: 115816.140625 reconstruction loss: 0.0 RMSE(mm): 170.15885271195853


204it [00:13, 14.79it/s]

Epoch 1, Batch 200, position loss: 112698.078125 reconstruction loss: 0.0 RMSE(mm): 167.85267210041667


230it [00:15, 14.75it/s]


Epoch 1, Val Loss: 111037.42788461539, RMSE(mm): 166.61139508195063
Epoch 1, test Loss: 119315.28635817308, RMSE(mm): 172.71022433412352


2it [00:00, 14.41it/s]

Epoch 2, Batch 0, position loss: 100341.65625 reconstruction loss: 0.0 RMSE(mm): 158.3837556774684


104it [00:07, 14.69it/s]

Epoch 2, Batch 100, position loss: 43925.08203125 reconstruction loss: 0.0 RMSE(mm): 104.79155742621874


204it [00:13, 14.66it/s]

Epoch 2, Batch 200, position loss: 24327.87890625 reconstruction loss: 0.0 RMSE(mm): 77.9869843407379


230it [00:15, 14.80it/s]


Epoch 2, Val Loss: 20185.039888822117, RMSE(mm): 71.03703240004842
Epoch 2, test Loss: 19087.821739783652, RMSE(mm): 69.07934159317034


2it [00:00, 14.31it/s]

Epoch 3, Batch 0, position loss: 17397.5390625 reconstruction loss: 0.0 RMSE(mm): 65.94986554667871


104it [00:07, 14.96it/s]

Epoch 3, Batch 100, position loss: 12574.34375 reconstruction loss: 0.0 RMSE(mm): 56.06769067386314


204it [00:13, 14.71it/s]

Epoch 3, Batch 200, position loss: 18178.05859375 reconstruction loss: 0.0 RMSE(mm): 67.41301542311767


230it [00:15, 14.75it/s]


Epoch 3, Val Loss: 19042.351243239184, RMSE(mm): 68.9970130571592
Epoch 3, test Loss: 18134.266920823316, RMSE(mm): 67.33176613015456


2it [00:00, 14.58it/s]

Epoch 4, Batch 0, position loss: 12397.138671875 reconstruction loss: 0.0 RMSE(mm): 55.67121938640064


102it [00:06, 14.56it/s]

Epoch 4, Batch 100, position loss: 12104.171875 reconstruction loss: 0.0 RMSE(mm): 55.00948071696369


202it [00:13, 14.68it/s]

Epoch 4, Batch 200, position loss: 19856.185546875 reconstruction loss: 0.0 RMSE(mm): 70.45598900532694


230it [00:15, 14.68it/s]


Epoch 4, Val Loss: 16017.996694711539, RMSE(mm): 63.28111229804581
Epoch 4, test Loss: 13865.380690354566, RMSE(mm): 58.875675559509645


2it [00:00, 14.81it/s]

Epoch 5, Batch 0, position loss: 11857.8974609375 reconstruction loss: 0.0 RMSE(mm): 54.446986741548656


102it [00:06, 14.84it/s]

Epoch 5, Batch 100, position loss: 11432.765625 reconstruction loss: 0.0 RMSE(mm): 53.46205576153989


202it [00:13, 14.77it/s]

Epoch 5, Batch 200, position loss: 18349.921875 reconstruction loss: 0.0 RMSE(mm): 67.7309417382484


230it [00:15, 14.87it/s]


Epoch 5, Val Loss: 16008.72049654447, RMSE(mm): 63.262786250181215
Epoch 5, test Loss: 14499.517709585336, RMSE(mm): 60.206971584662305


2it [00:00, 14.43it/s]

Epoch 6, Batch 0, position loss: 10471.951171875 reconstruction loss: 0.0 RMSE(mm): 51.166275934141915


102it [00:06, 14.64it/s]

Epoch 6, Batch 100, position loss: 11445.576171875 reconstruction loss: 0.0 RMSE(mm): 53.49199980341687


204it [00:13, 14.77it/s]

Epoch 6, Batch 200, position loss: 12971.1845703125 reconstruction loss: 0.0 RMSE(mm): 56.94555419502145


230it [00:15, 14.78it/s]


Epoch 6, Val Loss: 14477.261286808895, RMSE(mm): 60.16074568771753
Epoch 6, test Loss: 12296.991858849158, RMSE(mm): 55.44590124357516


2it [00:00, 14.51it/s]

Epoch 7, Batch 0, position loss: 8770.2587890625 reconstruction loss: 0.0 RMSE(mm): 46.824829922442056


104it [00:07, 14.63it/s]

Epoch 7, Batch 100, position loss: 11014.1240234375 reconstruction loss: 0.0 RMSE(mm): 52.47409842826625


204it [00:13, 14.73it/s]

Epoch 7, Batch 200, position loss: 12755.3876953125 reconstruction loss: 0.0 RMSE(mm): 56.469876251220214


230it [00:15, 14.76it/s]


Epoch 7, Val Loss: 14583.40508563702, RMSE(mm): 60.38088498365401
Epoch 7, test Loss: 12193.448176457332, RMSE(mm): 55.21197373862243


2it [00:00, 14.06it/s]

Epoch 8, Batch 0, position loss: 8700.2783203125 reconstruction loss: 0.0 RMSE(mm): 46.63764123621739


104it [00:07, 14.71it/s]

Epoch 8, Batch 100, position loss: 10310.3525390625 reconstruction loss: 0.0 RMSE(mm): 50.76995307035082


204it [00:13, 15.17it/s]

Epoch 8, Batch 200, position loss: 12412.232421875 reconstruction loss: 0.0 RMSE(mm): 55.7050994565915


230it [00:15, 14.87it/s]


Epoch 8, Val Loss: 14602.01983173077, RMSE(mm): 60.419408785031095
Epoch 8, test Loss: 12150.136380709135, RMSE(mm): 55.113828529483264


2it [00:00, 15.29it/s]

Epoch 9, Batch 0, position loss: 8462.87890625 reconstruction loss: 0.0 RMSE(mm): 45.9969534487068


102it [00:06, 14.72it/s]

Epoch 9, Batch 100, position loss: 9823.60546875 reconstruction loss: 0.0 RMSE(mm): 49.55705163937318


204it [00:13, 14.70it/s]

Epoch 9, Batch 200, position loss: 12245.0546875 reconstruction loss: 0.0 RMSE(mm): 55.32868760304188


230it [00:15, 14.85it/s]


Epoch 9, Val Loss: 14651.110407902645, RMSE(mm): 60.52088566747566
Epoch 9, test Loss: 12149.111065204326, RMSE(mm): 55.111503030683906


2it [00:00, 14.79it/s]

Epoch 10, Batch 0, position loss: 8112.43798828125 reconstruction loss: 0.0 RMSE(mm): 45.03453671428532


104it [00:07, 15.23it/s]

Epoch 10, Batch 100, position loss: 9436.1484375 reconstruction loss: 0.0 RMSE(mm): 48.569919799964666


204it [00:13, 15.28it/s]

Epoch 10, Batch 200, position loss: 11798.3994140625 reconstruction loss: 0.0 RMSE(mm): 54.31021868410792


230it [00:15, 15.05it/s]


Epoch 10, Val Loss: 14722.321467472957, RMSE(mm): 60.66778689608052
Epoch 10, test Loss: 12184.521474984977, RMSE(mm): 55.19175997145085


2it [00:00, 14.59it/s]

Epoch 11, Batch 0, position loss: 7745.337890625 reconstruction loss: 0.0 RMSE(mm): 44.00380066149116


104it [00:06, 15.33it/s]

Epoch 11, Batch 100, position loss: 9022.67578125 reconstruction loss: 0.0 RMSE(mm): 47.493883241029046


202it [00:13, 14.72it/s]

Epoch 11, Batch 200, position loss: 11224.3203125 reconstruction loss: 0.0 RMSE(mm): 52.97244640494716


230it [00:15, 15.03it/s]


Epoch 11, Val Loss: 14815.23270357572, RMSE(mm): 60.858920265594016


KeyboardInterrupt: 

In [11]:
import models.EEGViT_pretrained_hierarchical_pupil 
reload(models.EEGViT_pretrained_hierarchical_pupil )



Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized because the shapes did not match:
- vit.embeddings.patch_embeddings.projection.weight: found shape torch.Size([768, 3, 16, 16]) in the checkpoint and torch.Size([768, 768, 129, 1]) in the model instantiated
- vit.embeddings.position_embeddings: found shape torch.Size([1, 197, 768]) in the checkpoint and torch.Size([1, 15, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


create dataloader...
HI
training...


0it [00:00, ?it/s]

Unexpected exception formatting exception. Falling back to standard exception



Traceback (most recent call last):
  File "d:\ProgramData\anaconda3\envs\mlteeg\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Liwei\AppData\Local\Temp\ipykernel_29236\2624771002.py", line 15, in <module>
    train(model,EEGEyeNet, optimizer, scheduler,log_name=file_name, batch_size = batch_size ,n_epoch = n_epoch, subtask_weight=i)
  File "f:\OneDrive - The George Washington University\Course\23Fall\6907AppliedML\Code\MTL-VIT2EEG\helper_function_pupil.py", line 90, in train
    positions, predict_pupil_size = model(inputs,pupil_size)
  File "d:\ProgramData\anaconda3\envs\mlteeg\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "d:\ProgramData\anaconda3\envs\mlteeg\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "f:\OneDrive - The Georg